### ISSUE TITLE
Visibility Classes

### ISSUE THREAD

**Issue by maxcook** [zurb/foundation-apps#170]
```
.hide-for-small-only {
  display: block !important; }
  @media only screen and (min-width: 0em) and (max-width: 39.9375rem) {
    .hide-for-small-only {
      display: none !important; } }
```

Can someone explain why that `display: block !important` is necessary? It seriously messes with inline elements, e.g. a link with icon and span/text where the text shall be hidden in small.

**Comment by jmkenz** [comment]
Ah ha! So helpful :) This mixin update just saved my life.

**Comment by gakimball** [comment]
@jmkenz For Foundation 6 we're going to switch to `max-width` media queries to avoid the `display: block` issue altogether. I think eventually we'll transplant that fix to Apps as well.

See zurb/foundation#6687

**Comment by jmkenz** [comment]
Max-width media queries - does that mean developing CSS rules desktop-first?

On Wed, Sep 2, 2015 at 10:59 AM, Geoff Kimball <notifications@github.com>
wrote:

> @jmkenz <https://github.com/jmkenz> For Foundation 6 we're going to
> switch to max-width media queries to avoid the display: block issue
> altogether. I think eventually we'll transplant that fix to Apps as well.
>
> See zurb/foundation#6687 <https://github.com/zurb/foundation/issues/6687>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zurb/foundation-apps/issues/170#issuecomment-137144016>
> .
>



-- 
James McKenzie
Communications Designer
jamesmckenzie.ca

**Comment by gakimball** [comment]
@jmkenz It's only for `.show-for-*` classes, so that you never need to assign `display: block` to an element. We can refactor the visibility classes to only apply `display: none` to an element, negating the need for element-specific visibility classes (`table.show-for-medium` and so on).

It does break our mobile-first rule, which is sort of a tough call to make, but we've only made that call for this specific feature. The class itself still follows mobile first logic: "show this on x size and up", even if the rule in the background is `max-width`.

**Comment by jmkenz** [comment]
That's brilliant - thanks for confirming :)

On Sat, Sep 5, 2015 at 8:31 PM, Geoff Kimball <notifications@github.com>
wrote:

> @jmkenz <https://github.com/jmkenz> It's only for .show-for-* classes, so
> that you never need to assign display: block to an element. We can
> refactor the visibility classes to only apply display: none to an
> element, negating the need for element-specific visibility classes (
> table.show-for-medium and so on).
>
> It does break our mobile-first rule, which is sort of a tough call to
> make, but we've only made that call for this specific feature. The class
> itself still follows mobile first logic: "show this on x size and up", even
> if the rule in the background is max-width.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zurb/foundation-apps/issues/170#issuecomment-138017785>
> .
>



-- 
James McKenzie
Communications Designer
jamesmckenzie.ca
