### ISSUE TITLE
Modal dialog doesn't manage focus

### ISSUE THREAD

**Issue by cvrebert** [zurb/foundation-apps#192]
* After opening a modal, the focus remains on the button that opened the modal
* After manually focusing an element that's inside the modal, elements outside the modal can still be focused by pressing the Tab key enough times
* After closing the modal, the focus isn't returned to the button that opened the modal; the `<body>` gets focused instead. This is bad for accessibility.

**Comment by AntJanus** [comment]
@cvrebert those are all good points. Do you know how to focus on an element that is not a form element? I'll do som

**Comment by AntJanus** [comment]
hmm.. I'm not entirely sure how to prevent that. ideas?

**Comment by cvrebert** [comment]
Bootstrap's modal seems to do it somehow.

**Comment by AntJanus** [comment]
I'll check out their code. Thanks for the tip!
