### ISSUE TITLE
libsass support

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-apps#209]
Thanks to libsass 3.0, which supports maps, our codebase is most of the way towards being compatible with libsass. The stylesheets will compile, but we encountered a few minor bugs with some functions, so a few details will need to be hammered out before we can *really* say the framework is compatible with libsass. This issue will stay open until we're sure we're solid.

**Comment by listepo** [comment]
+1

**Comment by gakimball** [comment]
Alright, I'm going to call libsass support *official*.

Our plan is to eventually compile the documentation and the template stack with libsass by default, and drop our Ruby dependency, but of course we'll keep testing in Ruby Sass as well.

The Foundation 5 CLI gives the user the option to pick their compiler. Would people care if we dropped that choice and just made libsass the default? I feel like if you're savvy enough to want to use the new Sass 3.4 features, you're savvy enough to know how to switch a Sass compiler ;)

**Comment by k-j-kleist** [comment]
> The Foundation 5 CLI gives the user the option to pick their compiler. Would people care if we dropped that choice and just made libsass the default?

Just drop it. Defaulting to libsass is a major step forward for ZFA indeed.

**Comment by circlingthesun** [comment]
+1 for dropping it

**Comment by DiodeDan** [comment]
Libsass all the way. +1 for no more ~ 20 second sass compile times! 

When can we start using this? Will it be in v 1.0.3?

**Comment by gakimball** [comment]
It'll definitely be in 1.0.3 :)
