### ISSUE TITLE
Action Sheet - when to auto toggle off?

### ISSUE THREAD

**Issue by seanmavley** [zurb/foundation-apps#280]
The Action Sheet, upon click brings up the sheet with links nicely. (http://foundation.zurb.com/apps/docs/#!/action-sheet ) 

It toggles off ONLY upon second click on the button. Is that how its supposed to behave? How about option to make it autoclose upon
1) Clicking outside the action sheet popup modal
2) Clicking on one of the links

**Comment by AntJanus** [comment]
Finally fix.
