### ISSUE TITLE
Error on executing command "foundation-apps new ..."

### ISSUE THREAD

**Issue by iamontheinet** [zurb/foundation-apps#294]
Hi,

I followed the instructions on README and was able to successfully get through the first two commands **bower install foundation-apps --save** and **npm install -g foundation-cli bower gulp** but got the following error while running ***foundation-apps new <my-app-name>*** command:

<pre>Downloading the Foundation for Apps template...
Done downloading!

Installing dependencies...
npm  =>  bower  =>  bundler
/usr/local/lib/node_modules/foundation-cli/lib/foundationCLI.js:141
          if (err instanceof Error) throw err;
                                          ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)</pre>

Any ideas/suggestions?

Thanks in advance!
Dash

**Comment by anevaude** [comment]
Hey there. Just reaching out to say I am experiencing the same error. When trying to install, Terminal just freezes at

`Downloading the Foundation for Apps template...
Done downloading!

Installing dependencies...`

Will keep an eye on this thread. Good luck :)

**Comment by gakimball** [comment]
@anevaude Strange, do you see the steps underneath `"Installing dependencies..."`, like `npm => bower => bundler`?

`npm install` would be the first command it's running, so it must be freezing there.

**Comment by bstankowski** [comment]
Hey,

I’ve got similar problems. Running `foundation-apps new myApp` freezes on:

    Installing dependencies...
    npm  =>  bower  =>  bundler

`npm` highlighted and it doesn’t move to `bower`. I let it run for 20 minutes but no change. 

I tried the manual install you suggested @gakimball and `npm install` goes fine until what you can find in [npm_install_err.log](https://dl.dropboxusercontent.com/u/69822/foundation-apps/npm_install_err.log) (too long to paste here). And here’s my [npm-debug.log](https://dl.dropboxusercontent.com/u/69822/foundation-apps/npm-debug.log).

Don’t know why, I’ve never had any problems installing npm stuff.
I’m on OS X 10.10.1.

I tried several times, it worked just once, but then I got this after `foundation-apps watch`:

    > foundation-apps-template@1.0.2 start /Applications/MAMP/htdocs/dev/foundation/apps/myApp
    > gulp
    

    module.js:340
        throw err;
              ^
    Error: Cannot find module 'core-util-is'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/Applications/MAMP/htdocs/dev/foundation/apps/myApp/node_modules/gulp-util/node_modules/multipipe/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:46:12)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
    
    npm ERR! foundation-apps-template@1.0.2 start: `gulp`
    npm ERR! Exit status 8
    npm ERR!
    npm ERR! Failed at the foundation-apps-template@1.0.2 start script.
    npm ERR! This is most likely a problem with the foundation-apps-template package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     gulp
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls foundation-apps-template
    npm ERR! There is likely additional logging output above.
    npm ERR! System Darwin 14.0.0
    npm ERR! command "node" "/usr/local/bin/npm" "start"
    npm ERR! cwd /Applications/MAMP/htdocs/dev/foundation/apps/myApp
    npm ERR! node -v v0.10.30
    npm ERR! npm -v 1.4.9
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     /Applications/MAMP/htdocs/dev/foundation/apps/myApp/npm-debug.log
    npm ERR! not ok code 0

And I’m stuck here.

**Comment by bstankowski** [comment]
Well, as usual, found the issue after posting. I noticed a bunch of other things stopped working, so I eventually updated npm to 2.1.18 and it’s all good now. 

So if anyone has similar problems–start with updating your npm.

**Comment by spsaucier** [comment]
Same issue on multiple machines, but when going through your manual install process instead, there were no errors.
It did require my input in bower asking whether it could monitor data anonymously - could that be holding it up?

**Comment by gakimball** [comment]
@spsaucier Ah yeah, that would be an issue. We should be able to force each install command to be non-interactive.

When you did a manual install, did you ever need to use `sudo`?

**Comment by spsaucier** [comment]
No, no sudo was required.

**Comment by gakimball** [comment]
@spsaucier Hmm, well maybe Bower was the only issue. Did you get hangups in any other step of the process when using `foundation-apps new`, like the `npm` step?

**Comment by spsaucier** [comment]
Nope, that was the only one, & it seems like that was the part that hung in the automated version.

**Comment by gakimball** [comment]
@spsaucier Hm, alrighty then. We're working on [some upgrades](https://github.com/zurb/foundation-cli/pull/6) to the CLI, the last thing we're doing is some Windows testing. I'll add a note to make NPM and Bower noninteractive.

**Comment by bbodine1** [comment]
I had an issue with the CLI locking up trying to install NPM. I deleted what the CLI had made and re ran with the manual process and it worked like a champ. Wrote a post about it [on Codepen](http://codepen.io/bbodine1/blog/how-to-install-foundation-for-apps-manually).

**Comment by iamontheinet** [comment]
@gakimball Sorry for the late response. Your first suggestion to install bundler via `gem install bundler` before running ***foundation-apps new*** did it for me! 

```
Downloading the Foundation for Apps template...
Done downloading!

Installing dependencies...
npm  =>  bower  =>  bundler

You're all set! Now run foundation-apps watch while inside the app folder
```

Thanks!

**Comment by gakimball** [comment]
Awesome! Happy to help. :)

**Comment by resistdesign** [comment]
### What I've found is that sometimes gem doesn't install bundler right and it gets "le broke". So...

**I did the following:**

1. Install bundler again with `sudo`.
1. Uninstall bundler with `sudo`.
1. Install bundler again, but normally.
1. Close and reopen my terminal app. (It seems there is a bash session sourcing issue as well.)
