### ISSUE TITLE
Flicker in bottom panel animation

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#299]
when bottom panel button in [docs](http://foundation.zurb.com/apps/docs/#!/panel) is clicked, panel is appearing with a flicker. 
Panel animations in other directions is smooth

**Comment by AntJanus** [comment]
@gakimball I was thinking of modifying the animation method in FoundationApi (how our various elements animated) to add an `animating` class or similar. Would it make sense so that we can prevent issues like this?

For instance, we could do:

````css
.animating {
  overflow: hidden;
}
````

**Comment by gakimball** [comment]
@AntJanus That sounds good, since the user doesn't really need to interact with an element while it's moving anyway. You could add that class to the motion of `_motion.scss`.

**Comment by AntJanus** [comment]
Urgh, so it turns out it's not a panel issue. There's something about the animation that makes the `grid-block` several parents up get a scroll bar. Removing the `relative` declaration on grid-block fixes this problem; however, I'm not sure how that would play out with the rest of the CSS so I can't foresee a solution to this.

**Comment by gakimball** [comment]
Relative positioning is necessary to position a panel, because they use `position: absolute`. That doesn't mean *every* block needs relative positioning though, as that would cause weird issues.

**Comment by AntJanus** [comment]
Right right, that makes sense. So what would you propose as a solution?

**Comment by gakimball** [comment]
This is an older issue, but we think it's been resolved, partially through moving the HTML of the panels to the right position in the markup: 6aed7d5e654daa5a11e82a89f59ebd406c49e2a1

If you want panels to overlap a grid element, the panels should be *siblings* of the grid block, not *inside* the grid block. This was causing a flicker on some platforms; I saw it on iOS specifically before this fix.

If you see anything else odd let us know.
