### ISSUE TITLE
How to add a new module dependency to the application?

### ISSUE THREAD

**Issue by cgreening** [zurb/foundation-apps#308]
Currently the module dependencies are specified in the app.js in the foundation-apps bower component.

```js
angular.module('application', [
    'ui.router',
    'ngAnimate',
    etc...
```

If you want to add a new module - e.g. 'ngResource'

```js
angular.module('application', [
    'ui.router',
    'ngAnimate',
    etc...
   'ngResource'
```

You need to edit the app.js file in the foundation-apps bower component (which doesn't seem to be sensible as we shouldn't really modify these files).

Or you remove the foundation app.js from the gulp build and copy the code into your own app.js file where you can modify it safely (which also doesn't seem ideal as you'll won't get any updates in your own code).

Is the latter approach the most sensible? Or have I missed something obvious?

**Comment by AntJanus** [comment]
Since Foundation became a module in itself, this topic is a little moot. Closing it out.
