### ISSUE TITLE
couldn't build docs locally

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#318]
I ran following commands on ubuntu 14.04 machine

``` bash
npm install
npm start 
```

in a freshly cloned foundation-apps repo

I am getting following error

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: docs.scss:16:8: Unexpected { in decls
```

**Comment by etcook** [comment]
I've tried to clone and build 3 times now, and each time receive the same error as above:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
```

**Comment by gakimball** [comment]
@etcook This is a fun bug. Go into the Gulpfile and comment out the lines that run Autoprefixer.

```js
// Compile stylesheets with Ruby Sass
gulp.task('sass', function() {
  return sass('docs/assets/scss/', {
      loadPath: ['scss'],
      style: 'nested',
      bundleExec: true
    })
    .on('error', function(err) {
      console.log(err.message);
    })
    // .pipe(autoprefixer({
    //   browsers: ['last 2 versions', 'ie 10']
    // }))
    .pipe(gulp.dest('./build/assets/css/'));
});
```

Now run `npm start` and let it compile—it will run fine. Now quit the process, *uncomment* those lines, and run `npm start` again. It will magically work this time. We're not really sure why.

**Comment by etcook** [comment]
@gakimball What in the world? Is it a timing issue of sorts?

**Comment by gakimball** [comment]
@etcook I think it's an issue with Sass sourcemap files being piped to the `autoprefixer()` function, but I'm not sure why it only sometimes happens.
