### ISSUE TITLE
Distinction between multiple notifications

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#339]
If we click on [dynamic notification](http://foundation.zurb.com/apps/docs/#!/notification) multiple times  notifications are getting stacked on top of each other

But users can't see that there are multiple notifications.
Can we provide a way to distinguish between multiple notifications.
For example, we can provide a slight positional offset between successive notifications.

**Comment by AntJanus** [comment]
#388 fixed this! :)

**Comment by jmkenz** [comment]
Is it possible to limit the number of visible notifications? I want to show only 1 at a time.  I've tried the clearAll() method before each new notification is published, but it has a delayed reaction, leaving both notifications visible at the same time for a full second.
