### ISSUE TITLE
Feedback on Angular helpers

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-apps#34]
# Angular Helpers

In the same way that Foundation 5 allows you to quickly scaffold a page without writing any CSS, a primary goal with Foundation for Apps is to allow developers to quickly build a single-page web app without knowing any JavaScript.

Foundation for Apps will come with Angular, ngAnimate, and UI Router. To make harnessing the power of these tools easier, we're writing a series of "helpers" that tap into some of Angular's core functionality without requiring the user to write any JavaScript. Of course, if you aim to actually make a functioning web app with Foundation for Apps, the expectation is you understand Angular. These helpers are more geared towards rapid prototyping for users who aren't familiar with Angular or even JavaScript.
## Routing

In MVC terminology, a "route" is a specific URL that points to a specific view (i.e., a page). We're using UI Router to handle this stuff. Like with Rails or Django or any other web framework, routes are all defined in one place:

``` js
routerApp.config(function($stateProvider, $urlRouterProvider) {
  $stateProvider.state('home', {
    url: '/url',
    templateUrl: 'partial-home.html',
    controller: 'PageController'
  });    
});
```

At its most basic, a route is a URL and a reference to an HTML template, but a route can also include a controller and a few other fancy things.

We've designed a solution that allows the user to define a route directly on each template, and without writing any JavaScript. A route is defined at the top of each template in a block of YAML, and our custom Gulp task pulls these values out of each file, creating an array of templates/routes that it then turns into actual UI Router code. (The plan is also to condense the helpers into a single Gulp plugin, so you can simply remove it from a pipe if you don't want to use it.)

Defining a basic route looks like this:

```

---
name: about
url: /about

---

<div id="about"></div>
```

Nested child views are also supported:

```

---
name: about.contact
url: /contact

---
```

The URL for this view would be `/about/contact`.

It's also possible to pass in a controller, or insert a dynamic parameter into the URL:

```

---
name: blogPost
url: /post/:id
controller: BlogPostController

---
```
## Animation

In addition to defining routes, you can also define view-specific entrace and exit animations. It will also be possible to define a default in/out animation for a child view container, meaning all child views would animate in and out the same way.

```

---
animationIn: fadeIn
animationOut: fadeOut

---
```

The `fadeIn` and `fadeOut` values are simply CSS classes, meaning you could tap into any animation library with this feature. However, our built-in Motion UI component will include a number of pre-built transitions and animations, as well as a set of Sass mixins allowing you to fine-tune their behavior.

**We think these helpers will be a huge boon for users looking to rapidly prototype,** but we want your feedback, whether you're an Angular developer or not.
- **If you don't currently develop in Angular, do these concepts make sense to you?** The goal with defining routing information directly on each template is to reduce overhead. We think it will be easy for users to understand the very basics of routing: pick a name and a URL for your view, and that's it.
- **If you do develop in Angular, would you just rip this stuff out when you went to production?** As we mentioned before, these helpers are geared towards rapid prototyping, and they deliberately won't include all of the various complexities UI Router offers. However, maybe there's a balance we can strike between keeping the helpers simple, while also offering _just enough_ features to Angular developers that they may consider keeping them. At the same time, we don't really care, and would likely expect, developers to rip that stuff out and use UI Router like normal.

**Comment by dipongkor** [comment]
where is the definition of  fadeIn class. I have added it in templates like following 

name: profile.personalSettings
url: /personalSettings
controller: PersonalSettingsCtrl
animationIn: slideInLeft
animationOut: slideOutRight

But not working.

**Comment by gakimball** [comment]
@dipongkor We've had some issues with view animation, so for now, try animating your views with just in, not out. Like so:

```
---
name: profile.personalSettings
url: /personalSettings
controller: PersonalSettingsCtrl
animationIn: fadeIn
---
```

The animations are fast enough that it will still work pretty good. We're working on an overhaul of view animations, which will make simultaneous in/out animations for views work well: #386

**Comment by vincentmorneau** [comment]
@gakimball I am a not an angular developer, although I know JavaScript well, and one thing I'm missing from the documentation is how do you get the value of your parameters once you've branched to the ui-sref links?

For instance:

```
---
name: blogPost
url: /post/:id
---
```

How do I get the value of ```:id```?

Also, can we pass multiple parameters? What would be the syntax?

Thank you and amazing work on FFA.

**Comment by jeanieshark** [comment]
@vincentmorneau -

You can access your :id params by injecting the '$stateParams' as a dependency of your controller.

https://github.com/angular-ui/ui-router/wiki/URL-Routing#stateparams-service

As you can see in the example, each additional parameter that you add on the url will be available in the object as well.

**Comment by jmkenz** [comment]
I'd like to pass a parameter without making it appear in the URL.  This is supported by ui-router using the 'params' key.  I'd like to request adding support for that into the foundationRoutes logic.

E.g to use a parameter 'portfolioId' that won't appear in the URL:

state('new-nonurl', {
  url: '/new',
  params: {
    portfolioId: null,
  },
  templateUrl: 'new.html'

**Comment by gakimball** [comment]
@jmkenz Opened an issue at zurb/front-router#4 to track this.
