### ISSUE TITLE
Action sheet positioning

### ISSUE THREAD

**Issue by vincentmorneau** [zurb/foundation-apps#348]
I don't think the action sheet should be overflowing the window size, see screenshot:

![image](https://cloud.githubusercontent.com/assets/5391291/5505304/7186295a-875d-11e4-9b85-0145f3d06c3d.png)

Here is my code:

```
       <div zf-toggle="my-actionsheet">
            <img zf-iconic="" data-src="&PATH_ICONIC.cog.svg" class="iconic-md">
        </div>
        <zf-action-sheet id="my-actionsheet">
            <zf-as-content position="bottom">
                <ul>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Logout</a></li>
                </ul>
            </zf-as-content>
        </zf-action-sheet>
```

Am I missing something?

**Comment by hshepherd** [comment]
I'm having the same issue. Did you end up fixing this manually?

**Comment by vincentmorneau** [comment]
Nah, I put it on hold and wait for a fix.

**Comment by hshepherd** [comment]
I see, thank you.

**Comment by soumak77** [comment]
@hshepherd @vincentmorneau Not sure if either of you have solved this already, but I encountered the same issue and resolved it by adding CSS similar to what's shown below:
```css
#my-actionsheet .action-sheet {
  transform: translateX(-70px) translateY(107px);

  &::before, &::after {
    left: 10%;
  }
}
```
Couple things to note:
1. Transform will only move the body of the action sheet.  The other styling will move the attached arrow.
2. The exact numbers (-70px, 107px, 10%) were determine through trial and error and based on personal preference
3. This fix is very fragile and will likely need to be updated if ANY changes are made to the action sheet (e.g. adding more options) or if changes are made to the title bar.

Live Example: https://parents.fiboart.com
