### ISSUE TITLE
Feedback on grid structure and classes

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-apps#36]
# The Grid

In this thread we'd like to get your feedback on the Foundation for Apps grid. We're very excited about the grid, as it's going to allow developers to highly flexible, responsive app layouts that just aren't possible with the CSS floats of yore.

**The grid code can be found in this file:** `scss/components/_grid.scss`.

The grid is very close to feature-complete, and includes these features:
- Sizing on different screen sizes, using the 12-column grid
- Horizontal and vertical orientations, which can also be changed at different screen sizes
- Orienting grid items to the left, right, center, or with even spacing
- Easy source ordering, again with responsive classes
- Offsetting, which is perhaps less needed with the grid alignment options, but still available
## On using Flexbox

To start off, our decision to use Flexbox is pretty much set in stone. We've heard some concerns from the community regarding browser support, which we totally get. We've made the choice to be somewhat bleeding-edge, but this is also something of a long game. We at ZURB think web apps will only become more prominent, and this framework is meant to make web apps more powerful, and easier to develop.

Globally, some form of Flexbox support exists in [over 80%](http://caniuse.com/#feat=flexbox) of web browsers in use worldwide. To recap, we have totally solid support in:
- Google Chrome
- Firefox 28+
- Safari 6.1+ (Mac OS 10.7 "Lion" or newer)
- Internet Explorer 10+
- Opera 12+
- iOS 7.1+
- Android 4.4
- Chrome and Firefox for Android

Support gets a little shaky with iOS 6, Safari 6, and Android 2â€”4.3, which don't support wrapping of flex items. And support doesn't exist at all in Internet Explorer 9.
## The grid syntax

Originally the grid had two core concepts: the "group" and "block". These were roughly analagous to rows and columns in other grid systems, where the former is for layout and the latter is for content. A basic grid might look like:

``` html
<div class="group">
  <div class="small-4 block"></div>
  <div class="small-8 block"></div>
</div>
```

However, because of the... _flexibility_ of Flexbox, groups can be nested immediately inside groups, and be given sizing or ordering classes, just like blocks.

``` html
<div class="group" id="container">
  <!-- A fixed title bar and a scrolling pane of content -->
  <div class="vertical large-4 group" id="sidebar">
    <div class="shrink block" id="sidebarTitle"></div>
    <div class="block" id="sidebarContent"></div>
  </div>
  <!-- The main content area -->
  <div class="large-8 block" id="main"></div>
</div>
```

As you can see, not only are we immediately nesting groups inside groups (contrast this with Foundation 5, wherein you aren't supposed to nest rows inside rows), we have `#sidebar`, a group, and `#main`, a block, as siblings. Current grid systems don't quite work this way, where the "row" and "column" concept intermingle.

Once we realized how similar the two concepts are, we decided to merge them into one concept, using the name block. Now we have a single layout object that can be used for content _or_ layout.

``` html
<!-- This group becomes a block, and functions the exact same -->
<div class="block" id="container">
  <!-- As does this group -->
  <div class="vertical large-4 block" id="sidebar">
    <div class="shrink block" id="sidebarTitle"></div>
    <div class="block" id="sidebarContent"></div>
  </div>
  <div class="large-8 block" id="main"></div>
</div>
```

However, there was one final snag. Blocks are flex containers, which we don't usually want for actual content. So we decided to add the modifider class `content`, which swtiches the block from `display: flex` to `display: block`, and adds a gutter around the whole thing.

``` html
<div class="block" id="container">
  <div class="vertical large-4 block" id="sidebar">
    <!-- This two blocks are for content, not layout -->
    <div class="shrink content block" id="sidebarTitle"></div>
    <div class="content block" id="sidebarContent"></div>
  </div>
  <!-- Same with this one -->
  <div class="large-8 content block" id="main"></div>
</div>
```

**This is how the grid syntax currently works, and we're looking to get feedback on our approach.** Specifically, we're curious to know:
- **Does the distinction between _content_ and _layout_ make sense?** We've run into some trouble explaining the concept to folks, especially because of how fuzzy it can get:
  - _Layout_: I need to immediately nest more layout objects inside of this one.
  - _Content:_ I _don't_ need nest layout objects... but in reality, I might want to eventually, in which case I'll nest a new `block` and build another grid. Mixing content and layout is very common.
- **Would the old two class approach work better than this one-class-plus-a-modifier approach?** At the end of the day there are still two main concepts the developer needs to understand. The challenge is, unlike rows and columns, which each have a distinct purpose, the group and block differed in some ways but also shared some functionality.
- **Are there better class names we can use than `block`, `content`, or `group`?** It's also worth noting that Drupal uses the `block` class quite a bit, and there's always a risk of conflicting with CMSes that use the term `content`.
- **Are 12-column grids old hat?** When we first showed the grid, we received some comments that the 12-column model of sizing may be antiquated, especially for a more modern framework like this one. There are two other options we could explore:
  - _Percentage-based_, the main challenge there being how many, and which, classes you output. There are easy ones like `25`, `50`, and `75`, but how granular do you get? It's also worth noting that, if you use mixins only to build a grid, you could set the `$grid-columns` variable to 100 and basically be able to do this.
  - _Ratio-based_, which is a lot more niche, but is possible, as flex items can be sized relative to each other. (For example, a block with a size of `2` is twice as big as any block with a size of `1`.)

**Comment by djgadd** [comment]
Realise I'm late to give feedback but I figure it would be better here than opening a new issue.

Would quite like to see a {size}-shrink-only set of classes (and ideally that kind of convention echoed across most of the utility classes). I find myself writing a lot of boiler code for that at the moment because my layouts go from vertical to horizontal when moving between small/medium, and shrink is overriding the classic columns syntax.

**Comment by gakimball** [comment]
@djgadd We do need responsive versions of the `shrink` class, and also probably an `expand` class to revert a grid element back to the default behavior, with responsive versions of that class as well.
