### ISSUE TITLE
Enhancement for tabs

### ISSUE THREAD

**Issue by nathanmarks** [zurb/foundation-apps#360]
Would be nice if there was a more sophisticated implementation of the tabs directive that easily allowed for tabs that break up into a proper grid at larger breakpoints.

They are a great way of hiding content on mobile that you may want to show all at once at larger sizes. At the moment the only way is with a generous use of mixins and overriding tab CSS at larger breakpoints.

I'm an avid F5 user for most website work, and I was hoping that the foundation/angular setup would include some out of the box sophistication like this with the pre-made directives.

**Comment by zurbrandon** [comment]
Tabs could use some love for sure, any thoughts or code you'd use would be appreciated. Do you have a specific idea in mind for a PR?

**Comment by spsaucier** [comment]
I've modified mine to include an optional `class` value, which makes it much more useful in dynamic applications.

The biggest problem for me now is that variables aren't rendered inside the `tab-content` - anything like `{{ $index }}` is simply blank.

**Comment by asonnenshine** [comment]
@spsaucier I agree with you. Currently, I'm not able to "set" values in tabs, however, I was able to "get" values by using $parent

**Comment by zurbrandon** [comment]
I like the ideas on here! We're working on some ideas to give tabs more love, If anyone has a specific idea, we'd love a PR, but for now i'll close this.
