### ISSUE TITLE
Adding foundation-apps to an existing Rails Application

### ISSUE THREAD

**Issue by turn2norm** [zurb/foundation-apps#365]
I appologize if this information is readily available, but I couldn't seem to find a clear answer anywhere. Is it possible to add foundation-apps to an existing rails project? From the documentation, it looks like you have to create a brand new project in order to include the foundation-apps files.

Thanks for your help!

**Comment by gakimball** [comment]
The standalone framework files (all Sass, JS, and Iconic assets) are distributed through Bower and NPM. If you want to use our components in a Rails project, you'll want to add the framework to your asset pipeline. There are a few tools that connect Bower and Rails, including [rails-assets](https://github.com/rails-assets/rails-assets/) and [bower-rails](https://github.com/42dev/bower-rails).

**Comment by ahmed1490** [comment]
@gakimball 
I used `bower-rails` to and got ready with node components in my `vendor/assets/bower-components` folder.

Where can i specify which particular foundation components to be included & where should _settings.scss reside...?

**Comment by ahmed1490** [comment]
@gakimball 
I used `bower-rails` to get ready the foundation-app node components in my `vendor/assets/bower-components` folder.

Where can i specify which particular foundation components to be included & where should `_settings.scss` reside...?

I am not sure, if i should be creation a new issue for this..

@turn2norm Did you figured this out yet..?

**Comment by turn2norm** [comment]
@ahmed1490 we actually put this on the back burner for now. We have everything set already with standard foundation and will look into foundation-apps a little later.

**Comment by ahmed1490** [comment]
@jacquesachille Okay cool! I left foundation-apps for now.

**Comment by MsUzoAgu** [comment]
hi @jacquesachille and @ahmed1490: Did you guys figure this out?

**Comment by tunecino** [comment]
why not keeping front and back totally separated and use REST ? Rails and Angular are great with REST

**Comment by MsUzoAgu** [comment]
@tunecino: understand your point but need to get this out asap and don't want to wangle with Angular right now.
