### ISSUE TITLE
Dynamic panel sizes

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#366]
As of now of width of horizontal panel and height of vertical panel is fixed by sass variables.
This fixes the panel size independent of its location.
If  we place a panel in smaller block it overflows it parent

For example if we place below markup in app created with foundation-cli and click on panel button
Panel overflows it parent block and close button in panel is not visible.

```html
<div class='grid-block'>
  <div class='grid-block'>sidebar</div>
  <div class='small-8 grid-block'>
    <div>
      <a class='button' zf-toggle='bp'>
        Panel
      </a>
      <zf-panel id='bp' position='bottom'>
        <a zf-close='' class='close-button'>&times;</a>
        panel content
      </zf-panel>
    </div>
  </div>
</div>
```
![dynamic-panel-size](https://cloud.githubusercontent.com/assets/3403295/5558244/f0bcabd0-8d44-11e4-81cd-b58a175d8da8.png)

Can we make the panel size relative to its parent ?

**Comment by gakimball** [comment]
Sorry, I know this is an older issue, but the markup for this panel is incorrect. Panels should never go inside `.grid-content` elements; they should always anchor to a `.grid-block` element instead. This means a panel and the content it overlaps are sibling elements in the DOM.

Here's how to fix your example:

```html
<div class='grid-block'>
  <!-- Moved the panel up one level -->
  <zf-panel id='bp' position='bottom'>
    <a zf-close='' class='close-button'>&times;</a>
    panel content
  </zf-panel>
  <!-- The sidebar and main content are siblings of the panel -->
  <div class='grid-content'>sidebar</div>
  <div class='small-8 grid-content'>
    <a class='button' zf-toggle='bp'>Panel</a>
  </div>
</div>
```

I added a section to the panel documentation that clarifies this rule.
