### ISSUE TITLE
Using Foundation for Apps (with Gulp) in a Production Environment

### ISSUE THREAD

**Issue by mikehuebner** [zurb/foundation-apps#367]
Hello everyone!

I have had a blast learning the new apps and you guys have done a great job but I've hit a wall.

Using Foundation for Apps or Gulp in a production environment, how difficult would that be? For the `gulp-connect` plugin, just editing the host and port numbers or is there a much deeper process to do this?

I have been experimenting with it as a localhost, but I'm trying to get it to go live as well. How would I go about this?

**Comment by gakimball** [comment]
@mikehuebner Yep, that's it! To expand on what @AntJanus said, Gulp, Grunt, et al. are build tools that are meant to be run in a development environment only, and are primarily used to deliver static code. The servers that you can run with Gulp and Grunt (and even frameworks like Django and Rails) are meant for convenience and testing only, not production.

You could automate this process in Gulp by creating a deployment task that uses rsync, FTP, SSH, etc. to upload the `build` folder for you. [We do this](https://github.com/zurb/foundation-apps/blob/ff33e2da2e0413d4ec9d5fade525c840094e0444/gulpfile.js#L277) to deploy the documentation.
