### ISSUE TITLE
Page animation with custom controller

### ISSUE THREAD

**Issue by shalaby** [zurb/foundation-apps#368]
Thanks guys for your amazing work, the problem is:
```
---
name: about
url: /about
controller: AboutCtrl
animationIn: slideInDown
---
```
animation doesn't work, any solution?

**Comment by AntJanus** [comment]
@LuminusDev not a bad idea. Would you mind writing out some docs on this process [here](https://github.com/zurb/foundation-apps/blob/master/docs/templates/angular.html#L327)? I think a lot of users would appreciate it. If you can't, I can go ahead and write it out.
