### ISSUE TITLE
Fast clicks with AnimationIn set

### ISSUE THREAD

**Issue by andriytyurnikov** [zurb/foundation-apps#369]
If AnimationIn is set (and animationOut is NOT set), then ui-view contains previous views, when route change is done fast:
See screenshot
http://cl.ly/image/0D1J2s2F333H
Every Heading that you see - is a separate template view.

**Comment by gakimball** [comment]
We have a refactor of the animation libraries in progress (#386) so we'll make sure this issue is covered there.

**Comment by gakimball** [comment]
We merged in #386, which does address the scenario where the user clicks to another state mid-transition. The other two states will disappear, and the new one will animate in.

These changes will be in for version 1.1 of the framework, which we're hoping to have out by the end of the week.
