### ISSUE TITLE
foundation-apps build fails

### ISSUE THREAD

**Issue by kencrismontp** [zurb/foundation-apps#375]
When I run foundation-apps watch all is well, when I run foundation-apps build I fail.  Below is the failure.  Wanting to just build the app into the build folder then deploy that to my web server as part of a Continuous Integration build process.  Assuming this is what I want, foundation-apps build

Thoughts?

Ken.Crismon@62PYL12 /c/tfs/VTNG/Branches/Features/VTNG (Dillard)
$ foundation-apps build
npm ERR! Error: ENOENT, open 'c:\tfs\VTNG\Branches\Features\VTNG\node_modules\bu
ild\package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "build"
npm ERR! cwd c:\tfs\VTNG\Branches\Features\VTNG
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path c:\tfs\VTNG\Branches\Features\VTNG\node_modules\build\package.json

npm ERR! code ENOENT
npm ERR! errno 34
npm

**Comment by gakimball** [comment]
Try running `npm start build` manually in your command line and see if that works. Occasionally we've had issues where, for some reason, the user's machine freaks out if you add more arguments after `npm start`.

**Comment by nathanmarks** [comment]
@gakimball I believe this is because of a change in the "npm start" command in a somewhat recent version. @kencrismontp is likely running an older version of NPM and should update to the latest using `sudo npm update npm -g`.

See this commit for more details: https://github.com/npm/npm/commit/df4b0e7fc1abd9a54f98db75ec9e4d03d37d125b

**Comment by gakimball** [comment]
Yep, it looks like version 2.0.0 of npm introduced that change. I added a remark to the Install & Update page advising users to update their system's npm if they aren't installing a new copy of Node.

**Comment by kencrismontp** [comment]
Thanks for looking into this!

All is better.

**Comment by gakimball** [comment]
Awesome, glad to hear it!

**Comment by k-j-kleist** [comment]
But for God's sake: never, never, never run "npm update npm -g" :

https://github.com/npm/npm/issues/4099
https://github.com/npm/npm/issues/6247

**Comment by nathanmarks** [comment]
@k-j-kleist Aren't those issues referring to running `npm update -g` not `npm update npm -g`?

I said to run `sudo npm update npm -g`, which for me recently was the only way I could update NPM **without** it breaking.

**Comment by k-j-kleist** [comment]
Quoting from https://docs.npmjs.com/misc/faq:
### How do I update npm?
`npm install npm -g`

**Comment by nathanmarks** [comment]
Yeah, I did that and it spat an error and broke npm! Hence eventually settling on the other command.
