### ISSUE TITLE
zf-panel not working since upgrade to 1.0.2

### ISSUE THREAD

**Issue by designchief** [zurb/foundation-apps#379]
Having updated my project to 1.0.2, I now do not have my zf-panel working. 
There is no Partials folder in the build folder like there was before, how can I fix this?
I had used a zf-panel like the one on the zurb apps site for the side menu.

**Comment by designchief** [comment]
I hadn’t understood from the docs that I needed to copy the components folder from the bower folder to the client folder. I did that and the zf-panel now appears

**Comment by gakimball** [comment]
You shouldn't have to copy those files yourself out of `bower_components`; Gulp does that for you. However, there was an issue with the template stack's `Gulpfile` not properly copying HTML partials. [This pull request](https://github.com/zurb/foundation-apps-template/pull/18/files) fixed the problem; if you look at how the `Gulpfile` was changed, you can fix the issue in your project.
