### ISSUE TITLE
'is-active" class added to all menu-bar action sheet items

### ISSUE THREAD

**Issue by shoveland** [zurb/foundation-apps#381]
I have a series of 3 action sheets in a menu bar along the top. Upon activating a single action sheet, it adds the 'is-active' class to  all action sheet buttons, changing the color. 

    <ul class="primary menu-bar">
          <li>
              <img class="show-for-large site-logo"src="assets/img/logo.png">
              <a  class="site-logo" zf-toggle="mobileMenu"><img class="hide-for-large-only" src="assets/img/menu.png"></a>
          </li>
          
          <li>
              <div zf-action-sheet id="notifications">
                  <a href="#" zf-hard-toggle="notifications">
                    <i class="fa fa-bell fa-2x"></i>
                    <span class="alert badge">2</span>
                  </a>

                <div zf-as-content="" position="bottom">
                  <ul class="secondary-list">
                    <li><a href="#">Notification 1</a></li>
                    <li><a href="#">Notification 2</a></li>
                    <li><a href="#">Notification 3</a></li>
                  </ul>
                </div>
              </div>
          </li>
          
          <li>
              <div zf-action-sheet id="config">
                  <a href="#"  zf-hard-toggle="config">
                    <i class="fa fa-gear fa-2x"></i>
                  </a>
                
                <div zf-as-content="" position="bottom">
                  <ul class="secondary-list">
                    <li><a href="#">Setting 1</a></li>
                    <li><a href="#">Setting 2</a></li>
                    <li><a href="#">Setting 3</a></li>
                  </ul>
                </div>
              </div>
          </li>
          
          <li>
              <div zf-action-sheet id="user">
                  <a href="#" zf-hard-toggle="user">
                    <i class="fa fa-user fa-2x"></i>
                  </a>

                <div zf-as-content="" position="bottom">
                  <ul class="secondary-list">
                    <li><a href="#">Option 1</a></li>
                    <li><a href="#">Option 2</a></li>
                    <li><a href="#">Option 3</a></li>
                  </ul>
                </div>
              </div>
          </li>
        </ul>

Before:

![image](https://cloud.githubusercontent.com/assets/3876107/5597561/0b732c5e-926a-11e4-88da-4b70403cc4d2.png)

After click of any item:

![image](https://cloud.githubusercontent.com/assets/3876107/5597567/2ca3889c-926a-11e4-85ff-2e66a84d7989.png)

**Comment by akiran** [comment]
While debugging this issue, I found name mismatch between css classes and angular directives

map of css classes names to angular directives
.action-sheet-container -> zf-action-sheet
.action-sheet                -> zf-as-content

There is no is-active class for action-sheet-container, but it is considered in angular directive.
This is the main reason for this issue. 
.

**Comment by gakimball** [comment]
The first issue is one of selector specificity, so adding a bunch of `>`s should help, and won't break any existing code. We had this issue with another component where `is-active` was cascading down too far.

**Comment by akiran** [comment]
It also need cleanup in angular directive because it is adding is-active class for div containing action-sheet-container class.

**Comment by AntJanus** [comment]
@akiran I can take care of that part.

**Comment by akiran** [comment]
@AntJanus, Still few more things need to be taken care of to support this usecase.
Actionsheet is slightly different from other components.
In all other components, zf-closable, id, is-active class is applied on element that is shown/hidden with events.
But in actionsheet, zf-closable and id is applied in zf-action-sheet which is always shown and
is-active is applied on zf-as-content which is shown/hidden with events. Because of this zf-hard-toggle is not working as expected.

I tried to submit a PR for this issue, but couldn't do because of these issues.

**Comment by AntJanus** [comment]
Hmm, I'll look into it further. Thanks for researching this issue.

**Comment by maxcook** [comment]
#381 caused menu bar links to be in color of links instead of black color on white bg

**Comment by AntJanus** [comment]
Can anyone test if this issue is still there? I'm 99% sure I already applied a fix.

**Comment by gakimball** [comment]
Going to close this, if the problem still persists let us know. :)
