### ISSUE TITLE
Abstract matching functionality into a service

### ISSUE THREAD

**Issue by nathanmarks** [zurb/foundation-apps#382]
Would be great to gut the CSS media query matching functionality from `interchange.js` and abstract it into a separate service so that users can re-use the same lines of code and stay dry.

**Comment by AntJanus** [comment]
Not a bad idea. How would you want to structure it? As a separate service maybe? `foundation.interchange.service` that'd be required by `foundation.interchange` by default but could be used separately?

I don't think I'd want to bundle it into FoundationApi (that one has quickly become a bloated service).

**Comment by nathanmarks** [comment]
Yep as a separate service. Might be useful having a factory for matching and a service leveraging it that provides the on resize foundationapi subscription so that functionality is optional. 

I'm happy to put this together and make a pull request. And I agree foundationapi service shouldn't be allowed to get too bloated or we lose the modularity and dependency injection benefits.

**Comment by AntJanus** [comment]
If you can put together a PR, that'd be fantastic. We can further discuss it there and refine it.

**Comment by nathanmarks** [comment]
@AntJanus [window.matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window.matchMedia) has a lot of useful built in functionality via the [MediaQueryList](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList) objects returned from calling the `window.matchMedia(mediaQueryString)` function.

Is there a specific reason why you're using your own resize listener (which at the moment looks to be only being used for interchange) vs the `MediaQueryList` object's listener handlers? You're already returning those objects from the matchMedia browser API in [interchange](https://github.com/zurb/foundation-apps/blob/master/js/angular/components/interchange/interchange.js#L104).

Curious to hear what you think or if there's some drawback I'm not aware of.

**Comment by AntJanus** [comment]
@nathanmarks yep! There are several reasons:

1. This is how it works in Foundation, and the original implementation was a *bitch* to port over.
2. I had *just* found out about this feature
3. By the time I ported it over, I found out about the listeners portion
4. I told myself, "I'll definitely rewrite it and use these fancy listeners!" but forgot.

:) In short, yeah, this is definitely on a list somewhere and thank you for mentioning it!

**Comment by nathanmarks** [comment]
@AntJanus That really is `interchange` specific logic that should be handled separately. The logic doesn't have to be so tightly coupled. With the `MediaQueryListListener` callback we use whatever logic we want based on what's returned.

For `interchange` what we can do is have a `scenarios` array containing an object for each scenario to track the status of the and use the `MediaQueryListListener` callbacks to update the status of these scenarios.

`MediaQueryListListener` callbacks only fire when a media query **matches** or **unmatches**, and for initialization we can just check the `matches` property of the `MediaQueryList` object returned from `matchMedia()` for scenario after registering our listeners. 

When changes are made to the scenario array we can notify `interchange` via a function in the directive controller. 

Optionally, to try and avoid any unnecessary processing we could trigger a function on a small asynchronous timer when the first listener callback is fired. We can keep track of whether this timer is currently in progress to catch the other listener callbacks.

**Comment by nathanmarks** [comment]
@AntJanus To play around with this, I setup a factory and a service that you use by injecting the factory `mqFactory` as a dependency to your controller/service/whatever. There is no use of resize here -- just using the matchMedia API.

The first parameter is a single string or an array of queries to match (names or rule strings) and the 2nd/3rd are the match/unmatch callbacks (optional).

```
var mediumLargeTest = mqFactory( ['medium','large'], function() {
	console.log('matched medium and large');
}, function() {
	console.log('unmatched medium and large');
} );
```

The listeners are registered by a function called by the factory, and what's returned is an object created from the service containing the mql objects and some related functions. The service (used by the factory) is the prototype of the object returned.

The Media queries are setup by the service and can be get/set at any time using the service or an object created via the factory.

**Comment by AntJanus** [comment]
I'd love to see your code! I'm about to merge some refactors in, nothing major but it separates the Media query stuff into its own service (literally just cut/paste code from interchange into a service).

If you already have a working mechanism, it'd be awesome if you could submit a PR. We can either merge that in, or I can take that over.

**Comment by nathanmarks** [comment]
@AntJanus Happy to submit a PR, will prepare it very soon! Do you want me to branch it off your feature branch? When are you planning on merging that to master?

**Comment by AntJanus** [comment]
@nathanmarks Awesome! :) I just merged it in so you're welcome to go off master.

**Comment by nathanmarks** [comment]
@AntJanus Sweet. Will do.
