### ISSUE TITLE
Docs homepage slider stacked on navigation frequently

### ISSUE THREAD

**Issue by zyadsherif** [zurb/foundation-apps#383]
Just noticed that rotating between the slides of the Docs homepage quickly produces several layers of slides stacked on top of each other, see the attached image.

![image](https://cloud.githubusercontent.com/assets/1159370/5612510/d42e4568-94de-11e4-91c1-a8135ca29a86.png)

**Comment by gakimball** [comment]
It's a known issue with Orbit, our slider plugin that comes with Foundation 5.
