### ISSUE TITLE
Is it possible to use the resolve functionality of angular routes

### ISSUE THREAD

**Issue by aaronksaunders** [zurb/foundation-apps#387]
I would like to execute a function which returns a promise, only if that promise is resolved, should the route be rendered/executed.

See this example here -> https://thinkster.io/egghead/resolve-conventions/

This was straightforward in default angular, wondering how one implements that in FA?

Thanks

**Comment by AntJanus** [comment]
Currently there is no way to do this; however, the dynamic routing in FA is meant to be used in the most basic sense and for rapid prototyping. More advanced features should be left to a more conventional routing built out the angular way.

**Comment by FelipeMarcos** [comment]
I'm look for a way to do that as well

**Comment by circlingthesun** [comment]
Ui router supports resolve. This should not be an issue. Unless I'm missing
something.

**Comment by AntJanus** [comment]
UI Router does support it; however, we have not exposed that functionality in the dynamic routing scheme so you can't do something like this:

````yaml
name: mypage
url: /home
controller: MyPageController
resolve: function() { var some; code() };
````

**Comment by FelipeMarcos** [comment]
@AntJanus Are there any alternatives without modifying foundation's core directly?
Thanks

**Comment by AntJanus** [comment]
You don't have to deal with the core at all, just disable the dynamicRouting function and use your own router declaration.

**Comment by escapedcat** [comment]
For whoever is looking at this as well:
[Disabling Front Matter so Developer Can Use Own Routing #501](https://github.com/zurb/foundation-apps/issues/501#issuecomment-76715381)
The resolve entry is shown there as well.

**Comment by GaryWenneker** [comment]
Maybe a little late to ask this but is FA going to support resolvement in the dynamic routing scheme? Or maybe in the future? Love the dynamic routing because the designer can start working woth templates and define all paths without asking me all the time to do it. Afterwards I'll implement the controllers. Problem I'm having is that I get to many issues when scope data is nog set and directives try to fire
