### ISSUE TITLE
Directives do not seem to work with bower install

### ISSUE THREAD

**Issue by dniccum** [zurb/foundation-apps#389]
I have installed Foundation for Apps with bower for my project. I have been able to successfully apply the SCSS files to the project without any issues. However when I attempt to use the (panel feature outlined in your documentation)[http://foundation.zurb.com/apps/docs/#!/pane], nothing seems to work. I am not even getting console errors (which I would have expected). The code that I am using in my view is shown below:

```
<div zf-panel class="panel panel-fixed" position="bottom" id="authorBio">
	<a href="#" zf-close class="close-button">×</a>
</div>
<div class="bio-button button" zf-open="authorBio">View Author Bio</div>
```

**Comment by gakimball** [comment]
If you're adding the components to your own stack, you need to make sure the HTML templates for each directive are being picked up by Angular. In our [template stack](https://github.com/zurb/foundation-apps-template), we copy the partials from `bower_components/foundation-apps/js/angular/components/**/*.html` to `build/components`.

**Comment by gakimball** [comment]
Going to close this, let me know if the above was able to solve your issue, or if you still have problems.

**Comment by zavan** [comment]
@gakimball I had the same issue and your solution works, Thanks!

But on every foundation-apps update, I have to do this manual copy+pasting :/

Is there any way to make my already-pretty-big angular app to pickup up these templates without the manual work?

**Comment by gjungb** [comment]
@zavan A possible and in my eyes nice solution via Gulp is provided via #463.

**Comment by gakimball** [comment]
@gjungb @zavan Yep, until we have a templates JavaScript file in a stable version, you'll have to use a task runner to pull the templates out of the framework files. Below is an example of using the [ng-html2js](https://www.npmjs.com/package/ng-html2js) library with Gulp. There's a Grunt version of the plugin as well.

```js
var partials = gulp.src('bower_components/js/angular/components/**/*.html')
  .pipe($.ngHtml2js({
    prefix: 'components/',
    moduleName: 'foundation',
    declareModule: false
  }))
  .pipe($.concat('templates.js'))
  .pipe($.uglify())
  .pipe(gulp.dest('./dist/js'));
```

**Comment by zavan** [comment]
@gjungb @gakimball That's not ideal, but it's good enough for now. I'm glad to know that there are more plans about integration with pre-existent projects! 
Thank you, guys! I'm loving foundation for apps.

**Comment by gakimball** [comment]
@zavan Glad to hear it! If you make anything interesting with it, let us know. We're building some stuff internally (even for clients now!) so we're learning a lot about how fully-responsive web apps would work. and we'd love to hear what design/technical challenges other developers are running into.

**Comment by zavan** [comment]
@gakimball Sure! I'm pretty new to front-end frameworks, most of my experience is in the back-end, with PHP and Ruby frameworks, but I tend to contribute in every way I can to the projects I use and love.
See ya!
