### ISSUE TITLE
Why use Ruby for SASS?

### ISSUE THREAD

**Issue by Martinspire** [zurb/foundation-apps#39]
I've been working with the node alternative for SASS for a while now and it seems that using the Ruby version is a bit unneeded. The 3.4 additions aren't really major (not for this project anyways) and there are a couple of benefits.
- Using the Node-version is much faster (especially on windows)
- Its easier to get this project going on Windows as they don't have Ruby installed (you really need to watch out for your Windows users too)
- While it may not be on par with Ruby, its stable and deemed production ready by a lot (even though the readme doesn't state this).

You can just include it as a node-module (gulp-sass instead of gulp-ruby-sass) and get it over with. I really like that you won't have an entire dependency before you start and can easily update it too when new versions come out.

**Comment by Martinspire** [comment]
So Foundation 6 is released, but Ruby is still a requirement for Foundation for Apps?

**Comment by gakimball** [comment]
@Martinspire It's not. Our [starter template](https://github.com/zurb/foundation-apps-template) for Apps uses Libsass.
