### ISSUE TITLE
Offset classes are overridden

### ISSUE THREAD

**Issue by michael-zerovapor** [zurb/foundation-apps#395]
In the docs, reviewing the "Offsets" section of the grid page (http://foundation.zurb.com/apps/docs/#!/grid) , the example is broken. The example uses small-offset-2, applying a left margin to offset the 2-col grid-block, but the offset margin is overridden by other grid classes where a margin is also specified.

I'm just getting started with my first build, so I haven't tested this in my own build yet, but the docs, at least, don't show the offset example working properly.

**Comment by michael-zerovapor** [comment]
Also, there is a resource that fails to load:
http://foundation.zurb.com/apps/docs/partials/scss/grid.html

**Comment by gakimball** [comment]
The classes that apply those visual styles to the grid examples were overriding the offset class, so I fixed that. The actual grid won't have that issue under normal circumstances.
