### ISSUE TITLE
$digest/$apply already in progress

### ISSUE THREAD

**Issue by maxcook** [zurb/foundation-apps#396]
$apply already in progress
This error occurs on multiple js components.  `$apply()` always needs a `if (!scope.$root.$$phase) {`.
Currently this check is only applied to the $apply in the notification.js. However it is always required since the Foundation API gets mostly called from angular controllers, so digest is usually already in progress.

https://github.com/zurb/foundation-apps/blob/23fee8743590058f4b084393fd15d593c54d8e7e/js/angular/components/notification/notification.js#L189
https://github.com/zurb/foundation-apps/blob/adc596097368df1d4bbef0839fd203e830e77f89/js/angular/components/modal/modal.js#L56

and many more require
if (!scope.$root.$$phase) {

**Comment by AntJanus** [comment]
I'll be adding these to all the pertinent directives as I build factories for them.

**Comment by AntJanus** [comment]
It's been added to notification and modal. We'll add it as needed. I'll close this out.

**Comment by etcook** [comment]
@AntJanus I'm getting this error when trying to open and close a panel.

**Comment by etcook** [comment]
I'm consistently getting this error when I use

`FoundationApi.publish('id', 'show');`

Is there a workaround in the interim that I can use to squelch the errors?

**Comment by etcook** [comment]
@AntJanus Any update on this? I'm really sorry to keep bothering you.

**Comment by AntJanus** [comment]
@etcook I'm currently off the project. I'll go ahead and reopen this issue for someone to check up on this.

**Comment by hellojeanie** [comment]
Hey @etcook , I went ahead and added the additional conditional checks. This error is no longer showing up for me, but let me know if it still persists for you.

**Comment by ProLoser** [comment]
@jeanieshark @AntJanus this is now how you fix this sort of bug. You are fixing symptoms instead of problems. 

You should hoist the `$scope.$apply()` to the top of the stack trace.
