### ISSUE TITLE
Building docs locally not working with latest commit #32e7866

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#399]
I am getting below error in console when I tried to build docs locally.
Uncaught ReferenceError: angular is not defined

**Comment by AntJanus** [comment]
I've change some things around. Can you do a pull and test it out?

**Comment by thatguynamedandy** [comment]
I had the same issue, it was resolved by a `bower install`

**Comment by gakimball** [comment]
This error doesn't seem to be cropping up anymore, but if you have any more issues compiling the docs locally, let us know.
