### ISSUE TITLE
Modal behavior on phone and tablet

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#400]
When modal is activated on mobile devices, it is occupying entire width and height of phone and tablet even though modal content is small.

I am seeing this behavior with modal demos in docs on android phone and tablet and chrome browser.

Is this the expected behavior ?

**Comment by gakimball** [comment]
This is the intended behavior, although you could make the case that it doesn't need to be full height. Full width seems sensible, however. Modals are kind of like grid rows in that they have a max width.

**Comment by akiran** [comment]
Yes,  modal content is appearing on the top in mobile devices instead of center, which doesn't look good
Does it need to occupy full width on tablets ? 
Can we let grid classes on modal content decide the width of the modal ?

If modal is used as a confirm dialog, it would be nice if users can see overlay, and model content is not occupying entire width and height. User will clearly understand that this is dialog and more content is behind it.

**Comment by gakimball** [comment]
[This commit](75ec5dacfdc8c2c440ed6576fc1c413a434a4014) adds a `.dialog` class which turns off the full-bleed functionality of mobile modals.
