### ISSUE TITLE
How to debug my scripts

### ISSUE THREAD

**Issue by Dillie-O** [zurb/foundation-apps#406]
I think this is more a discussion item or a potential feature for down the road.

Everytime I run gulp, I get a nice minified app.js file that my app runs off of and is very fast, but if I get a Javascript error, debugging this becomes somewhat complicated because I don't have the raw files to work with.

I've seen in a few other gulp/grunt configurations the ability to run the site using the "client" resources, and then when it comes time to build, it complies everything together into the minified versions. So in "dev" you'll see all your individual bower_component references, then your foundation.js, app.js, factories.js, etc.

Then I can gulp build to get the minified versions to push to test/production.

Is this possible with the current setup? I'll help in whatever way I can, but I'm a .Net guy primarily (gasp) and still pretty new to the front end / AngularJS type stuff.

**Comment by gakimball** [comment]
As a temporary workaround, you can comment out the uglify step of the JavaScript build process. It's in the `uglify` task in `Gulpfile.js`:

```js
gulp.src(foundationJS)
    // .pipe(uglify({
    //   beautify: true,
    //   mangle: false
    // }).on('error', function(e) {
    //   console.log(e);
    // }))
    .pipe(concat('foundation.js'))
    .pipe(gulp.dest('./build/assets/js/'))
  ;
```

But, we can look into modifying the Gulpfile to have separate processes for development and production. I'll add it to our internal roadmap.

**Comment by etcook** [comment]
@gakimball Would you guys be receptive to a PR that puts uglify in a gulp-if, and only uglifies with a --production flag?

**Comment by Dillie-O** [comment]
I don't mind a production default, but having a gulp command build-debug or something like that would be great. I might have to try that out myself!

**Comment by gakimball** [comment]
You might be interested in [gulp-if](https://github.com/robrich/gulp-if), which can conditionally run files through a pipe. So only pipe to `uglify()` if `production = true` or something like that.

**Comment by Dillie-O** [comment]
Oooh! I like that idea a lot! Thanks for that!

**Comment by etcook** [comment]
@gakimball Did you see my message earlier? That's exactly what I suggested. Does that mean you'd be receptive?

**Comment by gakimball** [comment]
@etcook Oh! Sorry about that, skipped right over it when I loaded the page. But yes, we'd be interested in seeing what that would look like. A `production` flag should compress the Sass as well, while keeping it expanded while in development. The flag should probably be `false` by default, so that when you download the template you're already in development mode.

**Comment by etcook** [comment]
@gakimball I have this working with gulp, but it doesn't seem like foundation-apps properly passes along the param to gulp. Do you want me to do a pull request for the gulpfile changes in anticipation of a change in foundation-apps?

**Comment by Dillie-O** [comment]
Hey guys! I really appreciate you taking the idea and running with it. I'm still figuring all this out myself and it would have taken a lot longer for me to piece it altogether.

**Comment by etcook** [comment]
@gakimball Just use the changes I made in the PR I referenced.

**Comment by escapedcat** [comment]
This would be sweet!

**Comment by philippeluickx** [comment]
+1

**Comment by gakimball** [comment]
Just got this implemented in the template project, using the code @etcook wrote. [Check it out!](https://github.com/zurb/foundation-apps-template/commit/1a9f6a7fed9ac68f753d6a7e98aada88b0e51b24)

Adding the `--production` flag to `gulp` or `gulp build` will enable compressed mode in node-sass, and Uglify for JavaScript.
