### ISSUE TITLE
[codebase]Use ngAnnotate

### ISSUE THREAD

**Issue by TheSharpieOne** [zurb/foundation-apps#409]
Use [ngAnnotate](https://github.com/olov/ng-annotate) with the convenient [gulp plugin](https://github.com/Kagami/gulp-ng-annotate) by default instead of requiring developers to use `$inject` directly.

**Comment by webnugget** [comment]
i made a [Pull Request](https://github.com/zurb/foundation-apps-template/pull/23) for this issue

**Comment by gakimball** [comment]
We closed out the PR related to this issue last week; you can read [my comment](https://github.com/zurb/foundation-apps-template/pull/23#issuecomment-95379959) on why we closed it. Basically we're trying to keep the template stack as slim on features as possible, to reduce the number of moving parts. It's meant to be a baseline that more experienced users can build on.
