### ISSUE TITLE
How to use Motion-UI transitions in standalone angularjS-APP

### ISSUE THREAD

**Issue by hadokee** [zurb/foundation-apps#414]
I'm building angularJS App without using FoundationApps controller but injecting Foundation as dependency.
I would use transitions provided by MotionUI. I tried

`<div class="slideInDown">`

But it doesn't work.

**Comment by gakimball** [comment]
The CSS classes are written to use Angular's [animation module](https://docs.angularjs.org/guide/animations). So to make the animations work, you either need to use a directive that supports animation (like `ng-show`, `ng-repeat`, etc.) or use the `$animate` service to trigger them yourself.

**Comment by jjn2009** [comment]
I tried this with a fresh project and a few changes to /client/templates/home.html
This doesn't seem to work. Am I missing a class?
Animations seem to work but transitions do not, as per the motion-ui documentation "Motion Classes":
http://foundation.zurb.com/apps/docs/#!/motion-ui
```
---
name: home
url: /
---
Click me: <input type="checkbox" ng-model="checked"><br/>

<div ng-show="checked" class="fadeIn fadeOut linear">
  <h1>Welcome to Foundation for Apps!</h1>
</div>

<p class="lead">This is version <strong>1.0.2 Matterhorn</strong>.</p>
```

**Comment by jeaniec** [comment]
@jjn2009 the motion ui docs are mainly targeting using foundation animations with the foundation components, we haven't exactly integrated the animation directives with any selectable DOM element.

The easiest way for you to accomplish what you're thinking of is the following:

Change the main animation class to be one "fade" class.
```
Click me: <input type="checkbox" ng-model="checked"><br/>

<div ng-show="checked" class="fadeAnimation linear">
  <h1>Welcome to Foundation for Apps!</h1>
</div>

<p class="lead">This is version <strong>1.0.2 Matterhorn</strong>.</p>
```

and your (s)css file should look something like this:

```
.fade-animation {
  opacity: 1;
}

.fade-animation.ng-hide-add.ng-hide-add-active,
.fade-animation.ng-hide-remove.ng-hide-remove-active {
  -webkit-transition: all linear 0.5s;
  transition: all linear 0.5s;
}

.fade-animation.ng-hide {
  opacity: 0;
}
```

The reason for this is because we haven't been able to account for all of the different ng-animation classes that Angular includes, we've only so far accounted for enter/leave. But this work around should be the behavior that you're looking for. Sorry for the misdirection.

**Comment by jjn2009** [comment]
>the motion ui docs are mainly targeting using foundation animations with the foundation components, we haven't exactly integrated the animation directives with any selectable DOM element.

Foundation components? So custom foundation html elements like so: ```<foundation-xyz>```?

Also is that to say my original code will hopefully work in future releases? Not that changing it is a problem I'm just curious about the direction of the project and how I can expect motion-ui to work in the future.

**Comment by saviour123** [comment]
Where can i get a cool tutorial on just motion UI

**Comment by gakimball** [comment]
@saviour123 There aren't any tutorials that I know of specifically about Foundation for Apps's motion library, but our [documentation](http://foundation.zurb.com/apps/docs/#!/motion-ui) does a good job of explaining all of the key pieces: directive/view animation and using the Sass mixins.

Eventually the [new Motion UI](https://github.com/zurb/motion-ui) library will be plugged into this one. We'll likely do that at 1.2 and then remove the existing transition mixins for 1.3.
