### ISSUE TITLE
multiple motion-ui animations in series

### ISSUE THREAD

**Issue by jjn2009** [zurb/foundation-apps#419]
This is my template for home:
```
---
name: home
url: /
controller: HomeController
---
Click me: <input type="checkbox" ng-model="checked"><br/>

<div ng-show="checked" class="linear" ng-class="animateText" ng-click="animate('Text')">
  <h1>Welcome to Foundation for Apps!</h1>
</div>

<p class="lead">This is version <strong>1.0.2 Matterhorn</strong>.</p>
```

The only other thing I've modified is adding a controller to app:
```
  angular.module('application', [
    'ui.router',
    'ngAnimate',

    //foundation
    'foundation',
    'foundation.dynamicRouting',
    'foundation.dynamicRouting.animations'
  ])
    .config(config)
    .run(run)
    .controller('HomeController', HomeController);
  ;
...
...
...
  HomeController.$inject = ['$scope', '$state', '$animate', '$window', 'FoundationApi'];
  function HomeController($scope, $state, $animate, $window, FoundationApi) {
    $scope.animate = function(type) {
      if(type === 'Text') {

        $scope.animateText = 'wiggle';
        console.log($scope.animateText);
        setTimeout(function() {
          console.log('timeout');
          $scope.animateText = '';

          console.log($scope.animateText);
        }, 1500);
      }

    }
  }
```

The problem is that I cannot seem to get 'wiggle' to happen more than once. How does one reset the state of the dom element? Using the check button to hide the element (and check again to show) will reset the state, but even if I did find a way to do that programmatically it would likely be overkill.

**Comment by gakimball** [comment]
Take a look at [this CSS Tricks article](http://css-tricks.com/restart-css-animation/), which gets into a few methods for restarting animations. The two solutions it references are:

1. **Remove the animation class, *force a reflow*, and then re-add the class.** If you just remove the class and then immediately re-add it, the browser doesn't perceive it as an actual change in state. There are a few ways to do this—the one referenced in the article is `element.offsetWidth = element.offsetWidth;`.
2. **Reset the play state.** The CSS property is called `animation-play-state`, and the JavaScript version is `animationPlayState`. Change it to `paused`, and then immediately change it to `running`, and the animation will play again. Of course, the property is vendor prefixed, so you'll need to modify `webkitAnimationPlayState` and so on.

Hope that helps!

**Comment by jjn2009** [comment]
I see, I'm more of a back-end javascript developer myself so I wasn't aware of these options. That helps a lot, thanks for the thorough response. My issue personal issue is resolved but do you see something like a ```wiggle-once``` and a ```wiggle``` class being implemented to automate this?

**Comment by gakimball** [comment]
There is an `infinite` class you can apply to an animating element, and that will make the animation play forever. It seemed like your use case, though, was needing to get the animation to play again at some point. But, if you just need the animation to play forever without stopping, you can just add the class `infinite`.
