### ISSUE TITLE
Close animation on panel triggered when panel is already in close state 

### ISSUE THREAD

**Issue by dday34** [zurb/foundation-apps#420]
When closing a panel using the zf-close directive, if the panel is already closed the animation is still triggered resulting in an undesirable visual effect (the open directive should have the same issue as well).

```
    <div id="mypanel" zf-panel=""></div>
    <a zf-close="sub-navigation">Close</a>
```

In the example above if you click on the link, given that the panel is closed, you will still see the closing animation.

**Comment by gakimball** [comment]
Merged #421 which fixes this.
