### ISSUE TITLE
<code/> Wrapped around HTML fails

### ISSUE THREAD

**Issue by sime** [zurb/foundation-apps#425]
Doc fails when trying to wrap HTML inside <code>&lt;code/&gt;</code>

![screen shot 2015-01-29 at 21 52 57](https://cloud.githubusercontent.com/assets/216917/5966049/39e02464-a801-11e4-804a-a13f372658fa.png)

https://github.com/zurb/foundation-apps/blob/e7e54f1a2394eb0a790fdcc8935863fd4087fa45/docs/templates/angular.html#L81

**Comment by blacklizard** [comment]
<code> dosen't work with HTML elements

**Comment by gakimball** [comment]
True that; if you want to put HTML examples in a `<code>` element, you need to escape the angle brackets. So `<div>` becomes `&lt;div&gt;`.

For code blocks, our documentation uses an Angular port of highlight.js. It handles the escaping and syntax highlighting for us.
