### ISSUE TITLE
ui-router installing multiple times because of canonical name mismatch

### ISSUE THREAD

**Issue by xmlilley** [zurb/foundation-apps#426]
This is, admittedly, caused by a number of factors. But I think it's something where foundation-apps could clear it up simply, by switching to the new canonical name for the dependency. This is about projects where foundation-apps is installed via bower, rather than using the CLI. 

In the `bower.json` file for foundation-apps, the dependency on ui-router is specified as `ui-router`. And if you do `bower install ui-router`, it does successfully alias to the project `angular-ui-router`. It installs. The problem is, it installs in the `ui-router` directory, and bower interprets it as a separate item from `angular-ui-router`, even though they're the same code and install from the same repo. This means that if `angular-ui-router` is listed as a dependency anywhere else, you'll get two of them. Totally identical, just with different names.

(I have no idea if `ui-router` was the old name, or is just an alias, or what. Seems like a bad idea to have that behavior. People are going to stumble on that.)

But even though you can't control the existence of the alias, since the ui-router project's own github page currently uses `angular-ui-router` as the canonical bower dependency name, I respectfully suggest foundation-apps use that. (Other consumers, like Yeoman generators, are also using the canonical name, which sets up conflicts.)

**Comment by xmlilley** [comment]
OK. Super odd. I see that in https://github.com/zurb/foundation-apps/commit/88067743053aee4ff5395dbae5bd26e3607eaa10, this was already patched. But when I installed foundation-apps through bower this week, I'm still getting the old bower.json on 1.0.2:

```
  "name": "foundation-apps",
  "version": "1.0.2",
  "main": [
    "scss/foundation.scss",
    "js/angular/app.js"
  ],
  "dependencies": {
    "viewport-units-buggyfill": "~0.4.1",
    "tether": "~0.6.5",
    "fastclick": "~1.0.3",
    "angular": "~1.3.4",
    "ui-router": "~0.2.12",
    "angular-animate": "~1.3.4",
    "angular-touch": "~1.3.7",
    "hammerjs": "~2.0.4"
  },
```

**Comment by gakimball** [comment]
1.0.2 is the newest version of the framework. We're looking to put another version out next week.
