### ISSUE TITLE
Feature (cli): Add jshint to watch task

### ISSUE THREAD

**Issue by escapedcat** [zurb/foundation-apps#431]
I added [js-hint](https://www.npmjs.com/package/gulp-jshint) and [jshint-stylish](https://github.com/sindresorhus/jshint-stylish) (to make it look nice) to the `watch` task.

gulpfile changed like this:
```
gulp.task('lint', function() {
  return gulp.src(appJS)
    .pipe(jshint())
    .pipe(jshint.reporter('jshint-stylish'));
});


...


// Default task: builds your app, starts a server, and recompiles assets when they change
gulp.task('default', ['build', 'server:start'], function() {
  
  ...
  
  // Watch JavaScript
  gulp.watch(['./client/assets/js/**/*', './js/**/*'], ['lint', 'uglify']);

  ...

}
```

Not sure if that's the best way to handle it. I can create a PR if someone is interested.

**Comment by gakimball** [comment]
What you're thinking of is the [template stack](https://github.com/zurb/foundation-apps-template), which is a separate repo. However, we're trying to keep the build process on that thing as slim as possible, or at least as slim as a complete build process can be. With that in mind, we don't want to add any more plugins to that thing at the moment.

That being said, *this* repo would certainly benefit from having linters to check the Sass and JavaScript. I started fixing up the Sass to conform to one standard, but I haven't finished it yet.

**Comment by escapedcat** [comment]
That's exactly where I modified it:
[https://github.com/zurb/foundation-apps-template/blob/master/gulpfile.js](https://github.com/zurb/foundation-apps-template/blob/master/gulpfile.js)
But yeah, I get it, no need to overcomplicate things.

Regarding linting in general, I agree, a default way of linting JS and Sass would be great.
I will add [scss-lint](https://github.com/causes/scss-lint) as well to our own stack.

**Comment by birchcode** [comment]
Newb question here.

If I add the jslint like above, or other changes to my gulpfile.js, like other files to watch like my own js files. When FA updates (I haven't done this yet - I don't know if there are updates) - what happens? Does my gulpfile.js get overridden?

**Comment by escapedcat** [comment]
I would try something like this:

1. update the cli
2. bump the foundation-apps version in the the [bower file](https://github.com/zurb/foundation-apps-template/blob/master/bower.json) of your project and do `bower update`, which should update the bower components
3. check the changes for the gulpfile etc. directly at the updated [template stack](https://github.com/zurb/foundation-apps-template) or by creating a new test project and diff that.

How do you solve this at the moment @gakimball ?
Is there a tutorial or a threat for this already?

**Comment by escapedcat** [comment]
All good, I don't think it's a big problem either. Just wanted to ask to see if there's something already.
You're right, mentioning it in the changelog is enough.

**Comment by escapedcat** [comment]
FYI
Somehow this breaks/stops the watch process, which is annoying. I might try to add plumber as well. Keep you posted.
