### ISSUE TITLE
Height is higher than actual viewport height

### ISSUE THREAD

**Issue by PsykoSoldi3r** [zurb/foundation-apps#434]
On iPad with iOS8 and iOS7 the height of the page is slightly (approximately 12px, this is exactly the height of the statusbar) higher than the actual visible viewport height. This results in a scroll-able application.

At the attachment you can see when the page is scrolled down, the top of the page is behind the address bar. (Example: http://foundation.zurb.com/apps/app-templates/email/#!/ )

![screen shot 2015-02-03 at 13 55 28](https://cloud.githubusercontent.com/assets/2241262/6020537/498d2a9c-abad-11e4-91a1-dcf2e6240ba4.png)

**Comment by gakimball** [comment]
After doing some research, we found that the solution might have to be iPad-specific CSS that uses `calc()` to cut those extra pixels off the height of the grid frame. So, hooray for user agent sniffing?

**Comment by gakimball** [comment]
#456 could solve this, basically using `height: 100%` instead of `height: 100vh` to size things. It needs more testing, though.

**Comment by gakimball** [comment]
I've got a new PR open (#603) which appears to be a better solution.

We *will* make iOS play nice with web apps.

**Comment by gakimball** [comment]
Last solution, promise! bc01826c7bd1eb8e4ed6fb3bf293fcb0aebcaf9f fixes this issue. Tested in iOS 7 and 8 on the iPhone and iPad, and it works great.

**Comment by iandanforth** [comment]
For reference, the buggy fill did not work for me, however I am not using the angular components of the framework (I am using the CSS with React). The fix from #456 did however. iOS / Mobile Safari now has the correct height for the grid-frame.
