### ISSUE TITLE
front matter params not correctly linked

### ISSUE THREAD

**Issue by robotaoyuan** [zurb/foundation-apps#437]
Sorry if I appear newbie... I am new to this framework.

If I try to access url params from partials like below:
![screen shot 2015-02-04 at 3 18 23 pm](https://cloud.githubusercontent.com/assets/4868985/6036526/2571d62e-ac81-11e4-81c7-fe716d3922da.png)
{{param}} will resolve to an empty array eventually. Like this:
![screen shot 2015-02-04 at 3 19 15 pm](https://cloud.githubusercontent.com/assets/4868985/6036532/3b55d40e-ac81-11e4-9dcc-70164d29a5be.png)

I looked into the DefaultController which comes with using you guys' F4A CLI tool.
![screen shot 2015-02-04 at 3 24 16 pm](https://cloud.githubusercontent.com/assets/4868985/6036568/ee6a9d5e-ac81-11e4-9d33-b7b8f8e62131.png)
Looks like the way params is initialized to be an array is the culprit?
After modifying so params init to be a {} it sorta works.
![screen shot 2015-02-04 at 3 28 35 pm](https://cloud.githubusercontent.com/assets/4868985/6036605/87b07d8a-ac82-11e4-8421-8cf327eeefbd.png)

Is my workaround valid or is there another way to access url params?

**Comment by jeaniec** [comment]
@robotaoyuan This workaround is fine, but you can also create your own controller specific to that view and extend the default controller to access the params that way by using the $stateParams scope variable.
```
---
name: algo
controller: MyAlgoController
---
params: {{params}}
```
```
MyAlgoController.$inject = ['$scope', '$stateParams', '$state'];

function MyAlgoController($scope, $stateParams, $state) {
    $scope.params = $stateParams;
}
```
