### ISSUE TITLE
Form <select> arrow does not display

### ISSUE THREAD

**Issue by quook** [zurb/foundation-apps#438]
Firefox (v30.0.1) doesn't support hex values for the style="fill: [color]" attribute on SVG images. Changing the fill to rgb() or moving the color definition into a style fixes the problem e.g.:

background-image: url("data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" width=\"32\" height=\"24\" viewBox=\"0 0 32 24\"><polygon points=\"0,0 32,0 16,24\" style=\"fill:rgb(50,50,50)\"></polygon></svg>");

**Comment by gakimball** [comment]
As of Firefox 35 this doesn't appear to be an issue anymore. Since Firefox auto-updates, this shouldn't be a huge problem.

**Comment by quook** [comment]
Sorry—the defect report contained a typo. This does occur in Firefox 35.0.1 (latest version) on OS X Mavericks and OS X Yosemite.

**Comment by gakimball** [comment]
Alright, fixed it by converting the hex value to an RGB one on the fly.
