### ISSUE TITLE
Notifications re-appear after being closed

### ISSUE THREAD

**Issue by quook** [zurb/foundation-apps#439]
This double-close behavior has been observed in two cases:

1) Always: when the position or transform style attributes are changed e.g. position: relative. Feature request: make inline notifications a configurable option.
2) Sometimes: if the notification is dismissed immediately after it appears.

Notifications are being invoked in this way:

Markup:
<zf-notification-set id="main-notifications" class="custom-notification"></zf-notification-set>

Javascript:
$scope.$on('showAlert', function(event, alertData, keepAlert) {
  $timeout (function () {
    $FoundationApi.publish('main-notifications', { title: alertData.message, content: alertData.cause });
  }, 100);
});

**Comment by jeaniec** [comment]
@quook the notifications are already being style with position: relative. Or are you talking about the notification-container class?

**Comment by quook** [comment]
In F4Apps notifications are pinned to the corner of the viewport with position: fixed and I don't see a notification-container class. With position: fixed, multiple notifications are layered on top of each other, and if we override the position and transform attributes to allow inline or stacked notifications, each notification must be closed twice. This is one of the variations of SCSS we have tried:

.custom-notification {
	@extend %notification;
	
	> .notification {
		@include notification-layout(
			$x: left,
			$y: top,
			$size: auto,
			$offset: $spacevar-1
		);
		@include notification-style(
			$background: $color-5,
			$color: $color-1,
			$padding: 1rem,
			$radius: 0px
		);
	
		/* Restting position or transform causes double-close defect
			position: relative;
			display: block;
			top: 0 !important;
			left: 0 !important;
			margin-top: $spacevar-1;
			transform: none !important;
		*/

		/* Restting position or transform causes double-close defect 
			&.is-active {
				transform: none !important;
			}
		*/
	}
}

**Comment by jeaniec** [comment]
@quook Ah, I see. Since the last release, I've updated the notifications to stack as of https://github.com/zurb/foundation-apps/commit/adeee3439a8e8e409fccc2e5e8e024614935b456 . You could either pull down the latest repo to see if that will fix your current problem or wait until we release our next stable patch! :)

**Comment by quook** [comment]
We'll wait for the stable patch, thanks :-) Will this allow true inline notifications (inserted anywhere in the DOM)? Looks like position: fixed is still the default, just bumped up to the new notification-container parent.

**Comment by jeaniec** [comment]
At the moment, we're still discussion the option of including that in our next release, but you might be able to abstract the alerts from Foundation for Sites as a temporary workaround (http://foundation.zurb.com/docs/components/alert_boxes.html).

We will look into making a configurable option. :)
