### ISSUE TITLE
CSS Minification/Optimization

### ISSUE THREAD

**Issue by tatemz** [zurb/foundation-apps#440]
Naturally, the SASS community is finding better ways to organize and optimize their stylesheets, but the thought on everyone's mind is, "When will duplicate media queries be minified into single media queries?"

See feature request [#116](https://github.com/sass/sass/issues/116)

As such, it would be great if Foundation App was able to use a tool like [css-condense](https://github.com/rstacruz/css-condense) to optimize stylesheet size.

I just want to start the discussion on this and perhaps try to incorporate a gulp task into a pull request. Inevitably, complications will arise.

**Comment by gakimball** [comment]
Do these sorts of techniques negatively affect the cascade at all?

**Comment by tatemz** [comment]
Not certain, but probably, the developer says that there is a `--safe-mode` that will aid in most scenarios, but it would be ideal to structure the project in such a way to compress without safe mode in order to combine media queries.

I'll throw a test scenario together and see if I can duplicate the docs without error.

**Comment by tatemz** [comment]
Looks like you guys are already using the `gulp-minify-css` package (which uses clean-css), but is not at it's latest version (which contains considerable enhancements).

**Comment by tatemz** [comment]
I have put together a [gulp plugin](https://github.com/tatemz/gulp-css-condense/tree/develop) as well as a [feature branch](https://github.com/tatemz/foundation-apps/tree/feature/css-condense) to show how `css-condense` could be used.

For now, the functionality is only applied to the `dist` set of tasks, but a quick test condensed the 121 media queries from Foundation down to 17. Also, the rest of the css-condense [features](https://github.com/rstacruz/css-condense/#what-it-does) were applied.

Quickly glancing at the compiled docs, I did not see any initial problems, but this is a good place for us to start. Anyone want to audit this for us?

**Comment by tatemz** [comment]
Here's a gist of css-condense in action. I have turned on line break, but the styles are still mangled.

https://gist.github.com/tatemz/bde16d9fa5f75ff6091c

**Comment by tatemz** [comment]
While exploring some benchmarking techniques (that go beyond browser inspectors), I found this:

https://github.com/axemclion/perfjankie 

Any thoughts on implementing this CSS (and AngularJS component) performance tool into a gulp task and travis test?

**Comment by kurt-integral** [comment]
Yes

**Comment by tatemz** [comment]
Here's a first attempt at some browser testing. Looks like `perfjankie` is a pretty good browser testing tool, but looks like there are some errors to get sorted out.

Since this is off this issue's topic, I'll open a pull request and get started on a gulp module as well as a a test config for `perfjankie` tests.

![perfjankie test example](http://ibin.co/1rn2YP4ag8u1)

As to this issue's topic, I have tested `css-condense` locally and have found that there are no css errors I have run into. If there is interest in using the proposed gulp task to condense and optimize media queries and css rulesets then I suppose I can open up a PR for that as well, else this issue may be closed.
