### ISSUE TITLE
grid-container doesn't nest well inside grid-block

### ISSUE THREAD

**Issue by etcook** [zurb/foundation-apps#443]
The grid-container class doesn't nest well inside a grid-block. Using a fresh version of F4A and the following body html:

```html
<body>
<div class="grid-frame vertical">
  <div class="grid-block" style="background-color: green;">
    <div class="grid-container">
      <div class="grid-block" style="background-color: yellow;">
        Yellow
      </div>
      <div class="grid-block" style="background-color: blue;">
        Blue
      </div>
    </div>
  </div>
  <div class="grid-block" style="background-color: black;">
    <div class="grid-container">
      <div class="grid-block" style="background-color: yellow;">
        Yellow
      </div>
      <div class="grid-block" style="background-color: blue;">
        Blue
      </div>
    </div>
  </div>
</body>
```

produces this

![2015-02-07 at 4 24 pm](https://cloud.githubusercontent.com/assets/2329397/6094208/d462e0b8-aee5-11e4-82db-762ca15aeb68.png)

Is this intended behavior? The docs show the container within a grid-block. I'm trying to use foundation to create bars that span full width with contained content according to max-width.

Am I doing it wrong?

**Comment by gakimball** [comment]
Containers should be nested inside content blocks. Using your existing code, I can just swap out the first `grid-block` and make it `grid-content` instead. The two are totally interchangeable.

```html
<body>
<div class="grid-frame vertical">
  <div class="grid-content" style="background-color: green;">
    <div class="grid-container">
      <div class="grid-block" style="background-color: yellow;">
        Yellow
      </div>
      <div class="grid-block" style="background-color: blue;">
        Blue
      </div>
    </div>
  </div>
  <div class="grid-block" style="background-color: black;">
    <div class="grid-container">
      <div class="grid-block" style="background-color: yellow;">
        Yellow
      </div>
      <div class="grid-block" style="background-color: blue;">
        Blue
      </div>
    </div>
  </div>
</body>
```

Since `grid-block` is a flex container, it's children don't behave like normal flow content. `grid-content` is *not* a flex container, which means its children will function normally. `grid-container` is just a `margin: 0 auto;` container with a maximum width, so it has to be inside `grid-content` to function properly.

**Comment by etcook** [comment]
@gakimball Good to know! The docs might do well with a slight amount of clarification both as to how grid-container works, as well as the fact that they are interchangeable. Although you describe what grid-container should be used for, it isn't clear what it actually does, or how it relates to grid-block. Thanks a million!

**Comment by gakimball** [comment]
We're working on an official tutorial for the framework, which clarifies these concepts, and then some of that should make it back into the main documentation.

This grid is a complex beast, so questions like this are very helpful to us :) Thanks!
