### ISSUE TITLE
Prebuilt CSS via Bower?

### ISSUE THREAD

**Issue by loki2302** [zurb/foundation-apps#447]
The README clearly says that Foundation for Apps is "an Angular-powered framework for building powerful responsive web apps". Even though Angular is very popular nowadays, I would suggest the authors to consider extracting the CSS-only part and making it available via Bower for those who don't use Angular for some reason. I'm firmly convinced that Foundation for Apps' CSS library does have a value even without the rest of the framework.

So far, I've only discovered that CSS is available via CDN [here](http://cdn.jsdelivr.net/zurb/foundation-apps-1.0.2.min.css). Are there any plans for making it available via Bower?

**Comment by tatemz** [comment]
Just run this command and change `~/Development/your-project/vendor/`:
```
git clone https://github.com/zurb/foundation-apps.git && cd foundation-apps && npm install && bower install && gulp deploy:dist && cp dist/css/foundation-apps.css ~/Development/your-project/vendor/
```

I agree that there needs to be a foundation apps bower for dist css, but it's still under development and not fully implemented as a standalone library. That is what Foundation Sites is for.

**Comment by loki2302** [comment]
@tatemz , thank you for responding. I believe that the "regular" Foundation doesn't provide any tools for full-window layouts like Foundation for Apps does, that's why I'm curious about having Foundation for Apps available via Bower. I sure can git clone and build it manually, but there's quite a large difference between `bower install --save ...` and the `... && ... && ...` thing you've suggested. And I sure don't mean the number of keystrokes.

**Comment by tatemz** [comment]
Agreed. Maybe further implementation of the Foundation Sites concepts will be integrated into Foundation Apps. Though #441 is primarily referring to CSS modules, I think implementation techniques might also be merged.

**Comment by gakimball** [comment]
We have the pieces in place, so for future releases the compiled CSS and JS will be available in a `dist` directory of the Bower folder. (It's [here](https://github.com/zurb/foundation-apps/blob/master/gulpfile.js#L316) in the Gulpfile.) We're planning on releasing version 1.0.3 by the end of the week, which will be the first version of the framework to include distribution files.

In the mean time, the source Sass files are available in the Bower package. A good number of them, most importantly the Flexbox grid, can be used without any JavaScript.

**Comment by loki2302** [comment]
@gakimball Thank you - that's a good news. Waiting for the release.
