### ISSUE TITLE
Separate view motion module from routing module

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-apps#449]
This should be done after #386 is finished.

Right now `foundation.dynamicRouting.animations` is dependent on `foundation.dynamicRouting`, and if you create routes by hand in the JavaScript, even if you add motion classes, they won't be applied to the views when state changes. Here's an example of a vanilla route with motion classes:

```js
$stateProvider
  .state('home', {
    url: '/',
    templateUrl: 'templates/home.html',
    data: { vars: {
      animationIn: 'fadeIn'
      animationOut: 'fadeOut'
    } }
  });
```

These won't be applied, because the routes weren't defined by the dynamic routing module.

@jeaniec was able to monkey patch a fix onto a project for me, so I think we know how to solve this, we just need the sweeping changes to view animation in master first.

**Comment by jeanieshark** [comment]
Closed with #386.
