### ISSUE TITLE
Guide lines for contributing?

### ISSUE THREAD

**Issue by antonkandersson** [zurb/foundation-apps#450]
Hi! I've Googled for guide lines for contributers but haven't found any. Do you have these up somewhere? I'm especially interested in the Angular ones. :)

Thanks, and sorry if I've missed them. :)

**Comment by gakimball** [comment]
We have a [contributing document](https://github.com/zurb/foundation-apps/blob/master/CONTRIBUTING.md) which has some recommendations for how to submit issues and pull requests. We don't currently have any Angular-specific guidelines, though. Was there a question you had on how to modify the codebase?

**Comment by antonkandersson** [comment]
I was looking for a style guide and restrictions for code, to make the potential contributions consistent with the project's code style. Do you follow any guide lines?

**Comment by gakimball** [comment]
We really need to set up linters for this codebase, we just haven't gotten to it yet. The broad strokes are already there; all of our Angular modules are written in the same style, so following those general conventions is a good start. As far as specifics, hopefully we can get JSHint set up at some point, but in the mean time, just try to match our coding style as best you can. If we think something is suspect in a PR, we'll point it out :)
