### ISSUE TITLE
Foundation Icons in ZFA?

### ISSUE THREAD

**Issue by Dillie-O** [zurb/foundation-apps#451]
I really like what Iconic is providing, but I'm migrating an app over that I had built with Zurb to ZFA and really enjoyed the Zurb Foundation Icons. Is there any reason why I can't use Zurb Icons in ZFA? I figure I just need to do the appropriate bower install and update my sass to include the icon library, yes?

**Comment by gakimball** [comment]
They'll work just fine! Since there's no JavaScript component to them, like with Iconic, you can just drop in the Sass and the icon fonts no problem.
