### ISSUE TITLE
indicating active menu-item

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#457]
Can we add the feature to indicate active menu item ?

This might require adding javascript component for menu-bar to handle is-active class of active menu-item.

**Comment by escapedcat** [comment]
Good idea, would also be great to have that kind of class on the buttons for components like [off-canvas](http://foundation.zurb.com/apps/docs/#!/off-canvas).

**Comment by escapedcat** [comment]
Just found #249. I think adding the `FoundationApi` to your controller could solve this, but I think it would be great to handle this within the framework.

**Comment by gakimball** [comment]
Menu bar includes an `.is-active` class which can highlight an active item.

You can also use `ui-sref-active` to apply a class when a specific state is the current one.

```html
<ul class="menu-bar">
  <li ui-sref-active="is-active"><a ui-sref="home">Home</a></li>
  <li ui-sref-active="is-active"><a ui-sref="about">About</a></li>
</ul>
```

**Comment by escapedcat** [comment]
Right, that works.
Any idea for the the off-canvas menu?

**Comment by gakimball** [comment]
The off-canvas menu has no built-in styles; it's just an empty box. If you're nesting a vertical menu bar inside of it, you can do what I described above. If you have your own custom component, you can use `ui-sref-active` and make your own custom active state class.

**Comment by escapedcat** [comment]
Cool, thanks. Will check.

**Comment by gakimball** [comment]
@akiran, I think `ui-sref-active` would cover the use-case you're describing, where you have a menu and the current item (the current view) is highlighted. If it's not a state-specific thing you're targeting, you can still use the `is-active` class to highlight things based on other criteria.

Let us know if you have any more questions :)
