### ISSUE TITLE
Variable for customizing button background in hover state

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#461]
I am trying to build a theme for foundation-apps with material design and found it hard to customize background of button in hover state. Can we add a variable for it ($button-background-hover) ?

**Comment by gakimball** [comment]
Are you trying to write the theme just with the settings variables, or are you adding your own CSS overrides as well?

**Comment by akiran** [comment]
@gakimball, I am doing both: setting variables and writing custom css.
$button-background-hover will be helpful for customizing buttons.

**Comment by jcallery** [comment]
I'd be interested in this, too. I can't seem to find an easy way to change the background color without creating custom CSS overrides.
