### ISSUE TITLE
Orphaned foundation subscriptions cause errors

### ISSUE THREAD

**Issue by maxcook** [zurb/foundation-apps#464]
E.g. modals subscribe for the fa api. 
Unfortunately on destroy the dont unsubscribe.
so there will be subscription callbacks that rely on no longer avaiable vars.
that causes:

    Cannot read property '$$phase' of null

**Comment by jeaniec** [comment]
Hey @maxcook, do you have a code snippet to show the callback you're trying to use with the directive?

**Comment by gakimball** [comment]
Related: #397

**Comment by jeanieshark** [comment]
@maxcook should be solved with https://github.com/zurb/foundation-apps/commit/05663c96b2dc538959342fffdfe4dbe9e8892531. Let me know if this issue is still persisting for you.
