### ISSUE TITLE
_settings file in incorrect order ? | unknown variable line 397 $button-radius

### ISSUE THREAD

**Issue by jjdemitriUk** [zurb/foundation-apps#467]
So was using the settings file uncommented the whole page and got to this

```scss
// 9. Button Group
// - - - - - - - - - - - - - - -

 $btngroup-background: $primary-color;
 $btngroup-color: #fff;
 $btngroup-radius: $button-radius; 

// 10. Button
// - - - - - - - - - - - - - - -

 $button-padding: 0.85em 1em;
 $button-margin: 0 $global-padding $global-padding 0;
 $button-style: solid;
 $button-background: $primary-color;
 $button-color: auto;
 $button-radius: 0;
 $button-sizes: (
   tiny: 0.7,
   small: 0.8,
   medium: 1,
   large: 1.3,
 );
 $button-font-size: 0.9rem;
 $button-opacity-disabled: 0.5;
 $button-tag-selector: true; 
```

It produces an error when compiling saying unknown variable line 397 $button-radius but button radius isnt declared untill further down the page ?

**Comment by gakimball** [comment]
Looks to be a side effect of how our settings parser works, since it prints out each set of variables in the order the files come. Thankfully button group is the only component with a dependency on another component's variables.
