### ISSUE TITLE
Feature request: Datepicker

### ISSUE THREAD

**Issue by moondawg69** [zurb/foundation-apps#474]
Every (most) app needs a date picker, surprised this is not in as standard. Sure we can add one like:

https://github.com/nverba/pikaday-angular

But it should be in the core I feel to complete the 'set' of FA components.

**Comment by circlingthesun** [comment]
+1

**Comment by gakimball** [comment]
We've gotten a lot of requests to create a datepicker for Foundation for Sites, so for version 6 of that framework we're going to do it, as an external plugin. Once that work is done, we could definitely wrap that functionality in an Angular module.

**Comment by soumak77** [comment]
Perhaps this is just my lack of knowledge speaking, but isn't this already achievable by the date and month HTML5 input types?

**Comment by circlingthesun** [comment]
Not in all browsers. Last time I checked it only worked on Chrome.

**Comment by gakimball** [comment]
<http://caniuse.com/#feat=input-datetime>

**Comment by bastienJS** [comment]
+1

**Comment by gakimball** [comment]
Going to close this as a known feature request. We're working on a date/time picker for Foundation 6, and whatever we come up with there, we could definitely port over to Angular.

**Comment by philippeluickx** [comment]
+1

**Comment by manfrin** [comment]
This doesn't appear to have made it in to Foundation 6. +1ing the feature request.
