### ISSUE TITLE
Actionsheet not toggling if button outside actionsheet declaration

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#477]
I'm using an actionsheet in combination with the title-bar on large devices so I can have a dropdown menu (a hack for now until title bars can provide such functionality).  In version 1.0.2, this worked fine, however, in 1.0.3 support was added to autoclose actionsheets.  The logic used to determine whether an actionsheet should be opened or closed requires the button used to trigger the opening/closing of the actionsheet to be inside the actionsheet declaration.  As such, the code under the Additional Options section of the [docs](http://foundation.zurb.com/apps/docs/#!/action-sheet) does not work.  Only the "my button goes here" button will trigger opening/closing of the actionsheet, but the "toggle" button will not.

**Comment by moondawg69** [comment]
Ah that's annoying, I was planning to do the same until such functionality was implemented. Big issue for me and my planning/wireframing :(

**Comment by soumak77** [comment]
I currently have code in production that uses this functionality and would really like to consume the 1.0.3 changes, so I need this to be fixed or find an alternate solution.  I need to publish an update tonight, so I'm looking into a fix for this right now.  I'll post back to this thread with my findings.

**Comment by moondawg69** [comment]
Ok thanks, appreciated.

**Comment by soumak77** [comment]
Just found a hotfix.  Adding the **action-sheet-container** class to the element that toggles the actionsheet will allow it to work.  The one caveat is that I have two dropdowns in my titlebar, so if I click the second dropdown trigger while the first actionsheet is displayed, the second actionsheet is displayed as well without hiding the first actionsheet.  This happens regardless of whether I use zf-toggle or zf-hard-toggle.  I'll see if I can fix that, though regardless of what hotfix I come up with, a robust solution to this issue will still be needed.

**Comment by moondawg69** [comment]
Completely agree, as I had one for 'settings' and one for changing views based on context. What a pain.

**Comment by soumak77** [comment]
Ok found the final hotfix I'll be using until this gets fixed.  In addition to adding the **action-sheet-container** class, I added a click handler to the dropdown trigger which closes all other dropdowns:
```
foundationApi.publish(dropdown, 'close');
```
Now if you try to click the second dropdown while the first is open, it will close the first and vice versa.  The hotfix doesn't require any changes to the framework, so I'm happy with this for now.

**Comment by moondawg69** [comment]
Cool, good work :+1:
