### ISSUE TITLE
TypeError: scope.$root is null for modal

### ISSUE THREAD

**Issue by toranaga** [zurb/foundation-apps#480]
This is a blocker for my app, could you please check this out.
foundation-apps 1.0.3
Switching twice between templates with modal window causes JS error for open action: 	
...e.hide():"toggle"===msg&&scope.toggle(),scope.$root.$$phase||scope.$apply()})}va...
foundation.js (line 29, col 1526)

Easy to replicate: myApp sample from the tutorial, implement news and about with simple modal. Go to news, go to about, back to news click modal (in news) and you will get error.

**Comment by gakimball** [comment]
Fixed with this pull request: #478 Sorry for the hassle!
