### ISSUE TITLE
Grid Frame Mixing not working (iPad Also not working)

### ISSUE THREAD

**Issue by yashilanka** [zurb/foundation-apps#482]
i'm testing the F4A code by using class based and sass mixing. i just got error when we create a app using " grid-frame vertical" class it work well but when we add that by using sass mixing ( @include grid-frame(vertical);) it doesn't work.. i check it every devices (pc, tablet, phone) and not working.. hope this will fix near future..

##### test.html
``` html

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test</title>
    <link href="/assets/css/app.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="wrapper grid-frame vertical">
    <header class="grid-block shrink wrap">
       <div class="left grid-content medium-6 large-6"></div>
       <div class="right grid-content medium-6 large-6"></div>
      </header>
      <section class="appbody grid-block">
      </section>
    </div>
    
    <script src="/assets/js/foundation.js"></script>
    <script src="/assets/js/app.js"></script>
  </body>
</html>

```

##### Preview 

![screenshot 2015-02-20 22 42 37](https://cloud.githubusercontent.com/assets/866524/6305522/e5622b0a-b951-11e4-9ccb-02cc92c5805a.png)

##### test.html
``` html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Microimage HCM</title>
    <link href="/assets/css/app.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="wrapper">
      
      <header>
       <div class="left"></div>
       <div class="right"></div>
      </header>

      <section class="appbody">
        
      </section>
    </div>
    
    <script src="/assets/js/foundation.js"></script>
    <script src="/assets/js/app.js"></script>
  </body>
</html>
```
##### app.scss
``` sass
.wrapper{
	@include grid-frame(vertical);
	header{
		@include grid-block(shrink, $wrap:true);
		.left{
			@include grid-content(6);
			padding: 0px;
			height: 72px;
			background: #EEE;
		}
		.right{
			@include grid-content(6);
			padding: 0px;
			height: 72px;
			background: #666;
		}
	}
}
.appbody{
	@include grid-block();
	background: #CCC;
}
```
##### Preview 

![screenshot 2015-02-20 22 38 56](https://cloud.githubusercontent.com/assets/866524/6305463/58e8744a-b951-11e4-96d9-cf6721ad5423.png)

also none of the above codes not working in the localhost ipad view (Tested on iPad Air v8.1.3) i don't know why, but it happen. we need to fix these issues quickly i think.. because at the end of the day. we are creating the app using F4A because of the amazing grid system and it should be compatible with the all the devices. not IE i mean portable devices. so please please fix these issues. 

##### Preview 

![img_0239](https://cloud.githubusercontent.com/assets/866524/6305611/9aca31f4-b952-11e4-92f4-3759006673a9.PNG)

**Comment by gakimball** [comment]
Alright, luckily this is an easy fix. You're passing the wrong parameter to the `grid-frame()` mixin.

```scss
// Wrong
@include grid-frame(vertical);

// Right
@include grid-frame($orientation: vertical);
```

Making this one change fixes the issue, so the layout looks like the first screenshot, including on the iPad. The documentation was incorrect, as the first parameter of that mixin is `$size`, not `$orientation`. Size shouldn't even be an option, though, since you shouldn't be changing the width or height of the app frame, so we need to refactor that mixin slightly.
