### ISSUE TITLE
Lots om mixings and values not working.

### ISSUE THREAD

**Issue by yashilanka** [zurb/foundation-apps#485]
i Just notice lots of F4A mixings are not working while working with sass, but class based layout it perfectly work. as expected. can you check that. grid frame, grid-layout ... etc..

**Comment by gakimball** [comment]
All of the classes are built using the mixins. Could you give some specific examples of mixins that don't work? I'm also taking a look at your other issue (#482) today, so I'll see what's up there.

**Comment by gakimball** [comment]
We're working on improving the grid documentation, and we'll also be releasing a tutorial soon which will describe certain elements of the grid in better detail. If you have any specific feedback or issues with a Sass mixin, let us know in a new issue. :)
