### ISSUE TITLE
zf-panel animation variable no effect

### ISSUE THREAD

**Issue by escapedcat** [zurb/foundation-apps#489]
I didn't recognise any effect when setting `$panel-animation-speed` in my `settings.scss`.
I searched where it's used in the generated css-file and couldn't find my value. Or any value related to the speed of the panel.

I checked [_panel.scss](https://github.com/zurb/foundation-apps/blob/master/scss/components/_panel.scss) and it looks like, that the variable for panel speed (`$panel-animation-speed: 0.25s !default;`) is not used at the moment.

Let me know if I missed something.

**Comment by gakimball** [comment]
Ah, that's a legacy variable and shouldn't be in the codebase anymore. You can control the speed of animations with our built-in classes, or with your own CSS.

With our classes:
```html
<div zf-panel animation-in="slideInUp" class="[fast slow]"></div>
```

With your own code:
```html
<div zf-panel animation-in="slideInUp" class="panel-thing"></div>
```
```scss
.panel-thing {
  transition-duration: 500ms;
}
```
