### ISSUE TITLE
Is there a way to align a single '.grid-block' on the horizontal axis indepently from its siblings ?

### ISSUE THREAD

**Issue by lchabela** [zurb/foundation-apps#491]
I know in the framework there are several alignment classes that go on the parent that affect the alignment of the children, but is there something i am missing for if you want to align a single element indepently from what the parent is setting it children to. I was expecting to find some kind of class setup that utilised the 'align-self' property of flex.

**Comment by gakimball** [comment]
I think I know what you're describing, but there's another use case you might be talking about as well.

`align-items` and `align-self` align elements on the *cross-axis* of the flex container. So if you have a horizontal grid, your cross-axis goes up and down, and so the `align-` properties shift elements up and down. If you had four elements on your horizontal grid, there's no way to make two stick to the left and two stick to the right. The `justify-content` property controls that behavior, and it can't be set on individual flex children.

I *think* that's the behavior you're describing. But you're right that we don't currently have an abstraction for the `align-items` and `align-self` properties in the grid.
