### ISSUE TITLE
Modal will not open after loading template

### ISSUE THREAD

**Issue by bdavidsonnyl** [zurb/foundation-apps#497]
index.html contains a menubar with links that load templates.

<pre>
  &lt;div class="grid-content shrink" style="padding: 0;"&gt;
    &lt;ul class="primary condense menu-bar"&gt;
      &lt;li&gt;&lt;a&gt;&lt;strong&gt;Foundation for Apps&lt;/strong&gt;&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a ui-sref="home"&gt;Home&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a ui-sref="about"&gt;About&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a ui-sref="news"&gt;News&lt;/a&gt;&lt;/li&gt;
      &lt;li&gt;&lt;a ui-sref="contacts"&gt;Contact&lt;/a&gt;&lt;/li&gt;
    &lt;/ul&gt;
  &lt;/div&gt;
...
  &lt;div class="grid-container"&gt;
    &lt;div ng-class="['ui-animation']" ui-view&gt;&lt;/div&gt;
  &lt;/div&gt;
</pre>
My home template (which loads by default when index.html loads) contains a modal:

<pre>
  &lt;a class="button success" href="#" zf-open="subscribeModal"&gt;Subscribe&lt;/a&gt;
  &lt;div zf-modal id="subscribeModal"&gt;
    &lt;a href="#" zf-close&gt;x&lt;/a&gt;
    &lt;section class="grid-content"&gt;
      &lt;h3&gt;Test site&lt;/h3&gt;
      &lt;p&gt;Please subscribe!&lt;/p&gt;
      &lt;form&gt;
        &lt;label&gt;Enter your email!
          &lt;input type="text" placeholder="Email"&gt;
        &lt;/label&gt;
        &lt;a href="#" class="button" zf-close&gt;Submit&lt;/a&gt;
      &lt;/form&gt;
      &lt;/section&gt;
  &lt;/div&gt;
</pre>

When the page first loads, the modal displays correctly. However, if I click any of the menu-bar links to load a different template, then return to the home template, the modal will no longer open. The console shows the following error:

![image](https://cloud.githubusercontent.com/assets/3749545/6393376/753b731e-bd97-11e4-95cd-7b2e888c0492.png)

I'm using OS X 10.9.5. I've also tried a Windows 7 machine with the same result.

**Comment by gakimball** [comment]
Might be fixed by #478

**Comment by jeanieshark** [comment]
I am now finding this error fixed. @bdavidsonnyl please let me know if this issue still persists with you.
