### ISSUE TITLE
Bower/standalone JS is referencing templates on wrong path

### ISSUE THREAD

**Issue by xmlilley** [zurb/foundation-apps#498]
(Ref for similar issues: #428)

I'm installing foundation-apps 1.0.3 via Bower, into an existing Angular project. The javascript and CSS are injected successfully, using the files specified in bower.json. Notably, the path to the JS is: 

    dist/js/foundation-apps.js

I'm trying to implement a panel. The directive is getting called. But it appears to error out when it can't find the template file:

    Error: [$compile:tpload] Failed to load template: components/panel/panel.html

As far as I can tell by inspecting the whole `foundation-apps` folder in bower components, that's a relative path that *would* work, if we were instead using the JS file in the seed project folder at:

    js/angular/foundation.js

For this standalone version of the library, I'm thinking the cleanest solution would be to inline the templates, so the javascript is self-contained in a single file, and paths become moot?

(In the meantime, until there's a solution to this in release, does anyone else have a solution that will work in the short-term, without hacking what's in /bower-components? For now, I'll probably have to make a copy and <gasp> "inject" it MYSELF. : -) )

**Comment by xmlilley** [comment]
The short-term solution to the templates problem seems to be copying `/components` to my project's root. I can leave the JS where it is, managed by Bower. But, anyone else using generator-gulp-angular will want to delete all the .js from the copy of /components, or generator-gulp-angular's build scripts will hoover it all up and duplicate what you already have.

**Comment by gakimball** [comment]
Yep, right now you're supposed to copy the partials as a part of your build process—that's what we do in our [template stack](https://github.com/zurb/foundation-apps-template/blob/master/gulpfile.js#L69), using a glob that only targets HTML files.

Starting with 1.1, though, we're going to be distributing a compiled templates file (#463), so then you can just add one JavaScript file and get all of the templates. We're hoping to have 1.1 out in a week or so.
