### ISSUE TITLE
Suggestion: keep front matter and not extend when overriding CTRL

### ISSUE THREAD

**Issue by mannyhenri** [zurb/foundation-apps#499]
It would be great to keep front matter and not needing to extend the default controller when we override the controller. In most cases, especially when we come from MEAN or need to connect to external APIs or backend we will need to override the controller or/and create custom services.

**Comment by gakimball** [comment]
Is it possible to change a state after it's already been defined? The `foundation.dynamicRouting` module will create a set of states, and then in your bootstrapping code you'll define the states again. Can they be overwritten?

**Comment by soumak77** [comment]
@gakimball It doesn't appear as though states can be redefined.  I get this error when I tried to define a state with the same name as the front matter:
```
Error: State 'home' is already defined
````
I think you may be able to extend the states using the [$stateProvider.decorator](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider) method.  In my case it's just easier for me to remove the front matter and manage the states myself when I need a more complex state, though the decorator may be a solution for @mannyhenri's use case.

**Comment by mannyhenri** [comment]
closing as this is an old request
