### ISSUE TITLE
 Module 'ui.router' is not available

### ISSUE THREAD

**Issue by kevinhorek** [zurb/foundation-apps#500]
I get this error right after I run npm start:

 Uncaught Error: [$injector:modulerr] Failed to instantiate module application due to:
Error: [$injector:modulerr] Failed to instantiate module ui.router due to:
Error: [$injector:nomod] Module 'ui.router' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.14/$injector/nomod?p0=ui.router
    at http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:655
    at http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:14151
    at ensure (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:13406)
    at http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:13919
    at http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:29149
    at forEach (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:1299)
    at loadModules (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:28675)
    at http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:29052
    at forEach (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:1299)
    at loadModules (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:28675)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=ui.router&p1=Error…%2F%2Flogo-mixer.codio.io%3A8080%2Fassets%2Fjs%2Ffoundation.js%3A5%3A28675)
    at http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:655
    at http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:29494
    at forEach (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:1299)
    at loadModules (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:28675)
    at http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:29052
    at forEach (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:1299)
    at loadModules (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:28675)
    at createInjector (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:31932)
    at doBootstrap (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:10255)
    at bootstrap (http://logo-mixer.codio.io:8080/assets/js/foundation.js:5:10784)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=application&p1=Err…%2F%2Flogo-mixer.codio.io%3A8080%2Fassets%2Fjs%2Ffoundation.js%3A5%3A10784)

You can see what I get here: http://logo-mixer.codio.io:8080/, and you can view the code here: https://codio.com/kevinhorek/emw-prototype. I have deployed the same code to Digital Ocean and I have the same issue. If I run the same project locally on my mac, it looks like this: http://cl.ly/image/3t440f2b1F2g

**Comment by escapedcat** [comment]
We had a similar issue after accidentally upgrading from 1.0.2 to 1.0.3.
Seems to be the same issue here.

Check the path to ui-router in:
https://codio.com/kevinhorek/emw-prototype/tree/gulpfile.js
to this file:
https://codio.com/kevinhorek/emw-prototype/tree/bower_components/angular-ui-router/release/angular-ui-router.js

**Comment by kevinhorek** [comment]
@escapedcat Thanks so much! That fixed my issue.

**Comment by gabrielacosta** [comment]
I'm having this issue and the project was removed from codio. Could you please tell me how to fix it.

**Comment by escapedcat** [comment]
Make sure the path to your `angular-ui-router.js` is correct.

**Comment by gabrielacosta** [comment]
I checked the configuration in gulpfile.js

// These files include Foundation for Apps and its dependencies
var foundationJS = [
  'bower_components/fastclick/lib/fastclick.js',
  'bower_components/viewport-units-buggyfill/viewport-units-buggyfill.js',
  'bower_components/tether/tether.js',
  'bower_components/angular/angular.js',
  'bower_components/angular-animate/angular-animate.js',
  'bower_components/ui-router/release/angular-ui-router.js',
  'bower_components/angular-local-storage/dist/angular-local-storage.js',
  'bower_components/foundation-apps/js/vendor/**/*.js',
  'bower_components/foundation-apps/js/angular/**/*.js',
  '!bower_components/foundation-apps/js/angular/app.js'
];

I compared with the code in https://github.com/Dillie-O/z4a-dotnet-scaffold-auth

gulpfile.js

// These files include Foundation for Apps and its dependencies
var foundationJS = [
  'bower_components/fastclick/lib/fastclick.js',
  'bower_components/viewport-units-buggyfill/viewport-units-buggyfill.js',
  'bower_components/tether/tether.js',
  'bower_components/angular/angular.js',
  'bower_components/angular-animate/angular-animate.js',
  'bower_components/ui-router/release/angular-ui-router.js',
  'bower_components/angular-local-storage/dist/angular-local-storage.js',
  'bower_components/foundation-apps/js/vendor/**/*.js',
  'bower_components/foundation-apps/js/angular/**/*.js',
  '!bower_components/foundation-apps/js/angular/app.js'
];

They are the same and the second project works fine.

Could you please take a look and give me some feedback.

Kind regards, 

Juan
