### ISSUE TITLE
Disabling Front Matter so Developer Can Use Own Routing

### ISSUE THREAD

**Issue by tjnine** [zurb/foundation-apps#501]
How does one disable front matter routing so that I can take advantage of UI-Router myself? Any known solutions? I looked over the docs but couldn't find anything, and I don't know how the front matter is tied into how the states work with the controllers and such.  In the Foundation for Apps docs it says "This app depends on the use of front matter". Is there a way to disable this? If not can we make it a Feature Request?

Thank You for any feedback, information, or suggestions.

**Comment by escapedcat** [comment]
Maybe someone from this issue knows:
[Is it possible to use the resolve functionality of angular routes #387](https://github.com/zurb/foundation-apps/issues/387)

**Comment by escapedcat** [comment]
This works for me:

`gulpfile.js`: comment out the FA router part:
```js
// Copies your app's page templates and generates URLs for them
gulp.task('copy-templates', ['copy'], function() {
  return gulp.src('./client/templates/**/*.html')
    // .pipe(router({ 
    //   path: 'build/assets/js/routes.js',
    //   root: 'client'
    // }))
    .pipe(gulp.dest('./build/templates'))
  ;
});
```

`index.html`: remove the `routes.js`
```html
    <script src="/assets/js/foundation.js"></script>
    <!-- <script src="/assets/js/routes.js"></script> -->
    <script src='//maps.googleapis.com/maps/api/js?sensor=false'></script>
    <script src="/assets/js/app.js"></script>
```

`app.js`: modify the config part:
```js
 angular.module('application', [
    .....
    ])
    .config(
      function($stateProvider, $urlRouterProvider) {
        $stateProvider
          .state('yourstate', {
              url: '/yoururl',
              templateUrl: 'templates/yourTemplate.html',
              controller: 'YourController',
              resolve: {
                  // you can use resolve here, yay!
                  // promiseCustomerData: ['Restangular', function(Restangular) {
                  //     return Restangular.one('foo').get();
                  // }]
              }
          });
    })
  .run(run)
;
```

You need a `.state` entry for each route/template you had before.
In this example the part before looked like this:
```html
---
name: yourstate
url: /yoururl
controller: YourController
---
```

Hope this helps.

**Comment by gakimball** [comment]
What @escapedcat said will work. The module `foundation.dynamicRouting` is what handles the creation of states from Front Matter, so if you don't include it, no states will be generated. We're doing exactly that for a client right now at ZURB—using all of the framework's UI components, but writing our own states.

There's one caveat right now, which is that view animation doesn't work without the `foundation.dynamicRouting` module. This will change in version 1.1 of the framework, which we're hoping to have out soon. Then you'll be able to add animation to your states like this:

```js
$stateProvider
  .state('home', {
    url: '/',
    templateUrl: 'templates/home.html',
    animation: {
      enter: 'slideInDown',
      leave: 'fadeOut'
    }
  });
```

The change is already in master if you want to mess around with it.

**Comment by mikestecker** [comment]
I'm interested in this also. I have Foundation Apps integrated into a Rails project, and I would like to use all of the UI components but continue to use the Rails routing functionality, at least through initial development, after which I'll probably want to build out the Rails app's API and convert over to Angular for all front-end.

**Comment by gakimball** [comment]
@mikestecker The front matter routing is totally optional, and we took out the line saying it's required from the documentation.

We're trying to put out v1.1 today, which will make view animation work without the router plugin, so you can write your own states but still set up transitions between them.

**Comment by mikestecker** [comment]
@gakimball great thanks. I'll wait for v1.1 today and see how I can modify the project to only use the UI components.

**Comment by mikestecker** [comment]
@gakimball can you please update the thread when v1.1 is released? Also, could you update the thread with what changes can be made to disable the Angular router while still allowing the UI to function correctly?

I have updated my app.js file with my best guesses for how to do this, clicking around seems to work but the foundation UI features such as the tabs, accordions, etc only work if I press reload on my browser, not by clicking from page to page.

Also, my other JS seems to break when navigating by clicking around the pages, but if I press reload in the browser then it works. I'm not seeing any javascript errors in my console either.

This is my app.js:

```javascript
(function() {
  'use strict';

  angular.module('application', [
    'ui.router',
    'ngAnimate',

    //foundation
    'foundation',
    // 'foundation.dynamicRouting',
    // 'foundation.dynamicRouting.animations'
  ])
    .config(config)
    .run(run)
  ;

  config.$inject = ['$urlRouterProvider', '$locationProvider'];

  function config($urlProvider, $locationProvider) {
    $urlProvider.otherwise('/');

    $locationProvider.html5Mode({
      enabled: false,
      requireBase: false
    });

    $locationProvider.hashPrefix('!');
  }

  function run() {
    FastClick.attach(document.body);
  }
})();
```

**Comment by mikestecker** [comment]
@gakimball I haven't seen the v1.1 update yet today but I did pull the latest from the repo. This on it's own still didn't work the way I want it to, but removing `$urlProvider.otherwise('/');` from the app.js file allowed me to click around (kind of). It would change the URL in the browser and I would have to reload my browser to load the new page.

**Comment by olegpolyakov** [comment]
I have disabled the dynamicRouting and dynamicRouting.animations modules and configured my own states with the animation property, but there are no animations. Any advice?

**Comment by gakimball** [comment]
@olegpolyakov So, the awkward thing right now is that you still need those modules enabled to make view animation work, even if you're not using the Front Matter stuff. We were able to separate the functionality, but we haven't yet separated the modules themselves, to maintain backwards compatibility. We'll do that in a future version when we can properly deprecate it.

**Comment by mattobee** [comment]
I've followed what @escapedcat described but without success. It's failing to load any views and instead returning `WARNING: Tried to load angular more than once` and then `Cannot read property 'contains' of null`.

Here's my routing config:

``` javascript
        $stateProvider
            .state('app', {
            abstract: 'true',
            templateUrl: 'templates/app.html'
            })
            .state('app.account', {
            url: '^/account',
            templateUrl: 'templates/account.html'
            })
            .state('app.session', {
            url: '^/sessions/:sessionid',
            templateUrl: 'templates/session.html'
            })
            .state('app.sessions', {
            url: '^/sessions',
            templateUrl: 'templates/sessions.html'
            })
            .state('welcome', {
            url: '/',
            templateUrl: 'templates/welcome.html'
            });
```

Can anyone suggest a likely cause of this?
