### ISSUE TITLE
Wrong grid height calculation in Safari iPad

### ISSUE THREAD

**Issue by laurent-le-graverend** [zurb/foundation-apps#503]
When tabs are displayed on iPad, it seems like the grid calculation is wrong.

I attached 2 examples:
* One with one tab open = can see all the grid blocks
* One with more than one tab open = cannot see the footer (player block)

I an facing exactly this issue, an important element is not displayed, and since you scroll directly in different grid-content blocks, you don't scroll the body and therefore never hide the tab bar.

*Player visible*

![The player is visible](https://cloud.githubusercontent.com/assets/332246/6454602/ca673520-c185-11e4-96b0-db8890acc3ac.png)

*Player not visible*

![The player is not visible](https://cloud.githubusercontent.com/assets/332246/6454601/ca65fb74-c185-11e4-9e2d-a980f3475e04.png)

**Comment by gakimball** [comment]
This is an issue with how iOS interprets the viewport height (`vh`) unit. Mobile Safari calculates `100vh` without taking into account the height of the tabstrip. On iPhone, it doesn't account for the height of the status bar. So in both cases, the grid frame exceeds the "real" height of the viewport.

We're working on a solution but we don't have anything concrete yet. #456 addresses the issue by ditching the `vh` unit entirely, but it also introduces problems related to scrolling.

**Comment by gakimball** [comment]
I'm going to close this in favor of #434, which is very similar. We definitely need a solution to this, so we'll find one.
