### ISSUE TITLE
Unnecessary off-canvas scrollbars

### ISSUE THREAD

**Issue by calmass** [zurb/foundation-apps#505]
Regardless of the <zf-offcanvas> content, there are scrollbars.  Is there anyway to remove the greyed-out/empty scrollbars for an off-canvas menu that doesn't need the scrolling action?  An example can be found on the Foundation for Apps docs page: http://foundation.zurb.com/apps/docs/#!/off-canvas.  This behavior is also occurring in my small test app, for both Chrome and Firefox.

**Comment by gakimball** [comment]
What OS are you using?

**Comment by calmass** [comment]
Sorry, I should have been more specific:

OS: Both Windows 7 and Windows 8.1,
on Mozilla Firefox 36, and Chrome 39.xxxxx, 40.xxxxxx

**Comment by calmass** [comment]
I don't know why I didn't see it earlier, but the .off-canvas class extends the only-extendable %off-canvas, which has it's overflow explicitly set:

    overflow: scroll;

Therefore, in my foundation-overrides.scss I added a simple: 

    .off-canvas {
        overflow: auto;
    }

This removed the greyed-out scroll-bars and has the desired behavior (active scrolling) on a resized-to-smaller off-canvas container.   How come the "overflow: scroll" was chosen as a default?  Will this modification produce unexpected or odd behavior in a non-obvious way?  Thanks.

**Comment by gakimball** [comment]
@calmass It must have been an oversight. Blocks and panels use `overflow: auto`, which prevents scroll bars from showing up by default, so off-canvas should as well. Off-canvas and panel are more or less the same component, just positioned differently.
