### ISSUE TITLE
How does this work with custom build systems?

### ISSUE THREAD

**Issue by marnen** [zurb/foundation-apps#506]
Short version: I'd like to use foundation-apps with my own build system. How do I do that?

Long version: I've really enjoyed plain Foundation on other projects, and I'd like to use foundation-apps on a [node-webkit](http://nwjs.io) project. Since this is a desktop application, it requires a somewhat different build process than either a client-side or server-side Web application. I've got Grunt set up to process Haml, Sass, and CoffeeScript and put them where they need to go (http://github.com/marnen/sms-exporter, if you're curious about the setup), but I'm not sure how to get foundation-apps to play nice with that. It seems that foundation-cli has its own build system that won't work with this particular project (right?), and if I install the foundation-apps Node module, I'm not sure what I should be picking up from there for building into my app. Help?

**Comment by marnen** [comment]
Waitaminute...I had missed the `includePaths` option on node-sass. That might help.

**Comment by marnen** [comment]
Still leaving this open till I get a better answer or figure this out myself, though.

**Comment by gakimball** [comment]
There's no reason you can't use all of the framework files in another build process. The Foundation CLI is just running `gulp`, so you could look at the [template stack's Gulpfile](https://github.com/zurb/foundation-apps-template/blob/master/gulpfile.js) and just re-fit that for Grunt.

Our build process:
- Copies static content like HTML partials, images, etc.
- Copies HTML view templates and generates routes
- Compiles Sass
- Ugilifies and concatenates JavaScript

The only thing you can't do without Gulp is use our routing plugin, which allows you to generate ui.router-compatible states from Yaml in each view template. But that's largely optional; if you're writing your own states in the JavaScript you don't need it.

**Comment by marnen** [comment]
@gakimball I'll take a look at the `Gulpfile`; thanks. I've actually been thinking of a much simpler build process; does the following seem practical to you, or am I abusing foundation-apps if I try to shoehorn it in like this? (I hope I'm not being too long-winded; feel free to ignore or tell me to shut up. :) )

Background information:
* ~~node-webkit~~ NW.js runs Node and a Webkit browser on a directory or zipfile of HTML/CSS/JS files.
* I'm writing everything in Haml, Sass, and CoffeeScript.

Current setup:
* grunt-contrib-watch continuously watches `source` and compiles `source/*.[haml,scss,coffee]` to `build/*.[html,css,js]`.
* The NW application runs from the `build` directory.

Foundation additions:
* **Already implemented**: node-sass/grunt-sass uses option `includePaths: ['node_modules/foundation-apps/scss/']` so that `@import` statements from Foundation work pretty much as if the Sass files were in the local directory.
* **Not implemented**: create `grunt dist` task that basically duplicates the `build` directory but then runs `npm install`. This would make `require('some-foundation-module')` work right in my CoffeeScript files, I think. Alternative idea: use Mincer or something to get Sprockets-like behavior in my CoffeeScript files. Hmm. Now that I write this, I realize that I don't know if Node `require` works on the Webkit side of NW.js, so I may *have* to use Mincer.

You're right that I probably don't need Foundation's Angular front-matter routing, but I'm not sure. Actually, I wasn't necessarily going to use Angular at all for this project, but foundation-apps is the only Sass-based app CSS framework I was able to find.

BTW, minification would be nice (but not essential); concatenation isn't an issue. I don't like to concatenate all my JavaScript or CSS into one file even for Web applications; I certainly see no need to do so for a desktop application.

**Comment by gakimball** [comment]
At the end of the day the Foundation frameworks are just a collection of CSS/JS components, which means they can pretty much go anywhere. Foundation for Apps gets more restrictive because it requires Angular, but if you're just using our CSS components then you're probably fine. And we *definitely* want people to abuse the framework, because we need it to be as flexible as possible. :) We don't have a lot of experience here with doing web-to-native ports, but your build process seems totally fine.

**Comment by marnen** [comment]
Yeah, the CSS is the easy part. I guess I'll play around with the JS and see what works. 

I'm not sure anyone has much experience with things like NW; it's a fairly new niche and I think we're all making it up as we go along.

**Comment by gakimball** [comment]
If you build something cool that you can publish, send it our way! We're starting to develop internal projects and do work for clients with the framework, and we're learning a lot about how a fully-responsive web app is built.

**Comment by marnen** [comment]
I certainly will! I've already offered my app as an example to the NW team of how I got Cucumber and Mocha.js working. Hopefully I'll have the patience to stick with this project... :)
