### ISSUE TITLE
Additional Options feature not working in the action-sheet

### ISSUE THREAD

**Issue by CityRay** [zurb/foundation-apps#507]
http://foundation.zurb.com/apps/docs/#!/action-sheet
About Foundation for Apps > NAVIGATION > Action Sheet feature,
Basic HTML feature can operate, but Additional Options feature not working, at DOC version "1.0.3".

**Comment by soumak77** [comment]
Related: #477

**Comment by jeanieshark** [comment]
I'm closing this issue for now in favor of #477. I've updated the docs for now to reflect a more accurate version of how to use the directive as is, but I'll look into the issue of an outside anchor not triggering the action sheet to toggle.
