### ISSUE TITLE
inline list inside block list

### ISSUE THREAD

**Issue by akiran** [zurb/foundation-apps#508]
Do you want to support inline-list inside block list

```html
<ul class="block-list">
  <li>
    <ul class="inline-list">
      <li><a href="">link1</a></li>
      <li><a href="">link2</a></li>
      <li><a href="">link3</a></li>
    </ul>
  </li>
  <li>
    <ul class="inline-list">
      <li><a href="">link1</a></li>
      <li><a href="">link2</a></li>
      <li><a href="">link3</a></li>
    </ul>
  </li>
</ul>
``` 

With the current implementation, first child of inline-list is having double borders.

**Comment by gakimball** [comment]
Block lists are for menus, so each `<li>` should hold a single menu item. Putting an inline list inside a single menu item (essentially nesting the menus) turns it into something of a non-standard pattern, so we probably won't add CSS to make this work out of the box. But of course, you can definitely write those overrides yourself for your own project.
