### ISSUE TITLE
Accordion title styling too limited

### ISSUE THREAD

**Issue by escapedcat** [zurb/foundation-apps#509]
The Apps variant of the [Accordion](http://foundation.zurb.com/apps/docs/#!/accordion) is using the `title` attribute of the item to create the header. Therefor styling is very limited.

The [Accordion of Foundation 5](http://foundation.zurb.com/docs/components/accordion.html) is using an `a`. Which is more flexible cause you can stuff other HTML code inside. For instance add a `badge` span.

Not a biggy, but would be great if this could be considered in the future. I know you want to align these components with [Foundation](http://foundation.zurb.com) anyway. So yeah, would be awesome!

**Comment by gakimball** [comment]
Angular converts those attributes into more standard HTML, which you can then style. It looks like this:

```html
<div class="accordion">
  <div class="accordion-item">
    <div class="accordion-title"></div>
    <div class="accordion-content"></div>
  </div>
</div>
```

So you can select `.accordion-title` in CSS to change the styles.

We probably need to make this more clear in the documentation, though. Developers who haven't used Angular might not know that it renders these directives as HTML templates.

**Comment by escapedcat** [comment]
But what if I want to split things into spans with classes to style these differently?

from the mobile

**Comment by gakimball** [comment]
Could you explain in more detail what you want to do? Do you want to style individual items in an accordion?

**Comment by escapedcat** [comment]
I would like to have the option to achieve something like this (for example):
```html
<div class="accordion-title">
  <span class="badge">B</span>
  <span class="item">My item</span>
</div>
```

**Comment by gakimball** [comment]
Right! Yes, we need to add this, because right now accordion titles only support plain text. If you're just doing, say, an image, you could use a pseudo-element to add an icon.

```scss
.accordion-title::before {
  content: url('');
}
```

This won't work if you need to add dynamic content, though, like an unread count or a label. It's on our list of things to add.

**Comment by escapedcat** [comment]
Cool!
Yeah, also a good idea to use `:before`.
For now we just use HTML characters like `title="&radic; {{::foo.bar}}"`. It's ok for prototyping.

**Comment by Joe-5mith** [comment]
I'd also very much like to be able to use dynamic content and HTML as accordion titles.

**Comment by gakimball** [comment]
Going to close this out, but it's still on our list of things to do. :)
