### ISSUE TITLE
question: How to use Model in Modal-Template

### ISSUE THREAD

**Issue by webnugget** [zurb/foundation-apps#515]
Hi Guys,

i'm creating a modal programmaticly within my controller like this:

                    
    var option ={
    id:'12312313123',
    name:'optionname'
    };
    var modal = new ModalFactory({
          id: option.id + '-modal',
          templateUrl: 'templates/lenslist/optionsModal.html'
    });
    modal.activate();

How can i pass my option-object to the modal as scope variable?
In the end i want to display the name of the option in optionsModal.html like this:

    <h3>{{option.name}}</h3>
    <p>This is some Text for {{option.id}}</p>

Any ideas?

**Comment by jeanieshark** [comment]
For now, the way to do it would be to set your `option` variable as an object of $rootScope.

Your controller would look something like this. ('stuffffffffff' being your other dependency injections)

```
MyController.$inject = ['stuffffffff', 'ModalFactory', '$rootScope'];

  function MyController(stuffffffff, ModalFactory, $rootScope) {
 
    $rootScope.option ={
      id:'12312313123',
      name:'optionname'
    };
    var modal = new ModalFactory({
          id: $rootScope.option.id + '-modal',
          templateUrl: '../../templates/test-modal.html'
    });
    modal.activate();
```

**Comment by webnugget** [comment]
i solved this problem by using [angular-modal-service](https://github.com/dwmkerr/angular-modal-service) instead of ModalFactory, because i didn't like the idea to add everything to $rootScope.

Angular-Modal-Service is able to provide inputvalues, a modalController and can return a result.

    var modalOptions = {
                    templateUrl: 'templates/auth/login-modal.html',
                    controller: 'LoginModalController',
                    inputs: {
                        roles: requiredRoles
                    }
                };

                ModalService.showModal(modalOptions).then(function(modal) {

                    modal.close.then(function(result) {

                        if (result === 'signup') {
                            $state.go('signup');
                        } else if (result) {
                            $state.go(toState.name);
                        } else {
                            $state.go(fromState.name);
                        }
                    });
                });


[LoginModalController](https://github.com/webnugget/fapp-stack/blob/master/client/assets/modules/auth/controller/LoginModalController.js)
[LoginModalTemplate](https://github.com/webnugget/fapp-stack/blob/master/client/assets/modules/auth/templates/login-modal.html)

**Comment by tunecino** [comment]
why not a child page with its own controller where html content will just be inserted inside a modal, it worked for me, i just replaced the Close and/or Cancel button with a go back to parent link, check this: 
http://foundation.zurb.com/forum/posts/23322-open-apps-modal-on-page-load?page=2#comment-21214
