### ISSUE TITLE
Using Foundation-apps on a different stack

### ISSUE THREAD

**Issue by anik786** [zurb/foundation-apps#517]
I'm a big fan of Foundation, so was keen to use Foundation Apps as I am using Angular JS. However I am struggling to adapt it to use with my project and directory structure and my own server (Java not NodeJs). 

For example, I installed the bower version of this framework and then made links to "foundation-apps.min.js", however then I get errors about not finding the components folder (as the framework assumes the component folder is in the root). So I had to copy the entire components folder into the root of my directory, which I really did not want to do, as now all bower updates are no longer in sync. 

I'm sure other problems will soon crop up later, so I wish to find out is there an easier way to use Foundation for Apps using your own directory structure. I.e. is there like some kind of config property to allow me to specify my directories. 

If not, can anyone give me some pointers in how to use FA using my own directory structure the "correct" way. Should I have copied the entire components folder into my directory for example?

Please note, I am not concerned with using the the Gulp stuff.

**Comment by gakimball** [comment]
We've got a big improvement coming in v1.1, which will hopefully be out tomorrow. For the directive templates, we're using ng-html2js to pack them all into a single JavaScript file, meaning you won't need to copy those HTML files from the Bower package.

We also added a new feature to the Iconic directive which allows you to specify the path your icon files are in.

Are there any other specific concerns you have related to directory structure?

**Comment by anik786** [comment]
Awesome. Please do. I think FA can be a really good project, but there's definitely a lot of improvements that can be made, and not forcing how the user uses FA I think is key!

**Comment by gakimball** [comment]
Definitely! Thanks for your feedback. Other than which Angular add-ons we use (namely ui-router and ngAnimate), we want to avoid being prescriptive with regards to how people design or code. That'll always be a goal for all three of the Foundation frameworks.

Also, 1.1 got pushed to tomorrow (Monday), but it'll get there.
