### ISSUE TITLE
Having a sass-only option for Foundation

### ISSUE THREAD

**Issue by Globegitter** [zurb/foundation-apps#518]
I am [EmberJS](http://emberjs.com/) Web Developer and using Foundation for Apps on one of my prototype apps successfully so far.

I don't really need any of the Angular specific stuff, i.e. components and animations, since ember has a lot of this stuff by itself but it would be great to still get the great grid system, helper classes, menubar, fonts etc.

It is quite easy to customise the needed components through https://github.com/zurb/foundation-apps/blob/master/scss/foundation.scss. But it would be great to get a bower version that is angular-dependency free.

**Comment by gakimball** [comment]
You can still install the package and just ignore everything in the `js` folder. If you're using a tool like wiredep, you can configure it to ignore all of the JavaScript that our library depends on.

To be sure, Foundation for Apps has *quite a few* dependencies, so it is sort of lame that you have to install seven other things you probably won't use. (Although FastClick and the viewport units buggyfill are both nice.) If you check your dependencies into version control, you can ignore them in `.gitignore`, and if you don't, simply ignoring the folders is easy enough.

Bower 1.4 might add the ability to ignore dependencies, although there's been no word on it recently. Here's the pull request: bower/bower#1394
