### ISSUE TITLE
 icon-left does not work in menu-group

### ISSUE THREAD

**Issue by Joe-5mith** [zurb/foundation-apps#519]
In order to have icons appear to the left of links in a Menu Bar (as opposed to the top, as is the default), one adds the `icon-left` class to the Menu Bar container. However, when using the `menu-group` component to wrap two menu bars in a container, the `icon-left` class does not work and the icon always appears at the top.

This is the case no matter whether the `icon-left` class is added to the `menu-group` container, the `menu-group-right` container or the `menu-bar` container.

The same applies to `icon-bottom`.

**Comment by gakimball** [comment]
The `icon-*` classes should be used on the menu bar itself, not the menu group. However, a selector specificity issue was preventing the class from being applied properly. Fixed!
