### ISSUE TITLE
Bottom of text gets cut off in form inputs on Firefox (Chrome is okay)

### ISSUE THREAD

**Issue by Joe-5mith** [zurb/foundation-apps#521]
Here's a screenshot from the [docs form page] (http://foundation.zurb.com/apps/docs/#!/forms), using Firefox 36.0.1:

![f4a cut off text](https://cloud.githubusercontent.com/assets/11408683/6578037/b6255bf0-c739-11e4-8c9f-b893fc2a851a.png)

**Comment by gakimball** [comment]
That Firefox `<input>` line height issue, what a fun one.
