### ISSUE TITLE
offcanvas menu navigation seems to break modals

### ISSUE THREAD

**Issue by alejandro-londono** [zurb/foundation-apps#522]
I am using off canvas menu with reveal. when ever I navigate from one page to the other, it seems that the modal reveal is affected by the navigation

**Comment by gakimball** [comment]
Could you describe the issue you're having in more detail? Maybe include a screenshot?

**Comment by alejandro-londono** [comment]
![screen shot 2015-03-12 at 4 56 18 pm](https://cloud.githubusercontent.com/assets/10235887/6628111/43e3db60-c8d9-11e4-87b2-a269fa268293.png)

this is a feed i am working on for an app. I have nested the card component inside an ng-repeat which prints each post as a card. at the bottom of the card I have nested a modal so i can show the information in more detail. 
![screen shot 2015-03-12 at 4 58 19 pm](https://cloud.githubusercontent.com/assets/10235887/6628113/465752c8-c8d9-11e4-8985-58d9b13cd7ff.png)
this is the index file that includes the ui-view where all of my routes show up. this is where i placed the off canvas menu. 

![screen shot 2015-03-07 at 10 50 05 pm](https://cloud.githubusercontent.com/assets/10235887/6628312/bf5845e6-c8da-11e4-827e-8dc9c050ba11.png)

here is a rendering of the user profile area of the site. I have the offcanvas menu open and you can see one of the posts that uses the card component and the option to use open the model by clicking on the icon in the lower left corner. 

MY ISSUE

I found that when I navigated the off canvas menu from the feed to the user profile page, the modals work. but when I navigate back to the feed, the reveal modals stop working. i receive an error 

"Uncaught TypeError: Cannot read property '$$phase' of null" (foundation.js line 29)

The same thing occurs when I navigate from the user profile page and back again If I navigate to any other area of the website actually, I get the same error. I am unsure is this is something that i have missed in my own code or if its an issue with F4A. 

I am referencing javascript objects that contains the fake data that you see. Could it be an issue with the way I am referencing my objects? 

![screen shot 2015-03-12 at 5 23 52 pm](https://cloud.githubusercontent.com/assets/10235887/6628528/a7258ff4-c8dc-11e4-8faa-a817e81de382.png)

here is the code i have added to the app js file. its just a few controllers and the javascript objects i created to emulate a database. 

I hope i was more clear. if there is some way I can provide more resources i would be happy to do so as this issue is a big problem in my app development.

**Comment by jeanieshark** [comment]
@alejandro-londono are you experiencing this using the up-to-date master branch of Foundation for Apps? I'm going to try to recreate the issue you're having, but in the meantime, if you're not currently on the most recent commit, can you pull down from there? I think we recently fixed an issue similar to this.

**Comment by gakimball** [comment]
Also, does the error happen when you change to a new view, or when you perform some other action like a click?

```
"Uncaught TypeError: Cannot read property '$$phase' of null" (foundation.js line 29)
```

**Comment by alejandro-londono** [comment]
it happens when the event is a click. when i click to open a modal I recieve that error. I am about to try the most recent commit. I will let you know what happens

**Comment by gakimball** [comment]
Yeah, let us know if the changes on the master branch fix your issue.

But just so we're sure, the series of events that cause the error are:
 - Navigate to a state that has modals inside it
 - Navigate away from that state
 - Navigate back to the state
 - Click the modal open trigger
 - Error

We had bugs reported related to modals that are inside of a `ui-view`, and we were able to implement some fixes. See: #464

**Comment by alejandro-londono** [comment]
I followed the instructions on the read me file and installed the app in a different folder, however I think can't tell if I am pulling from the correct branch or not. I also tried cloning the repo but had trouble installing it. I think i need further instruction to make sure I am correctly pulling from the master repo. please excuse my ignorance.

**Comment by gakimball** [comment]
Do you use Bower to manage dependencies? If you do, switching to the master branch is easy. Just make this change in your `bower.json`.

```js
{
  "dependencies": {
    "foundation-apps": "master"
  }
}
```

**Comment by alejandro-londono** [comment]
Fantastic! my issue was resolved! should I just stay on the master branch from now on?

**Comment by gakimball** [comment]
We don't recommend it, because we actively develop on it. We maintain a `stable` branch as well that's always pointed at the last version we released.

However, we're releasing v1.1 tomorrow, which will include this fix, so you can just upgrade when that comes out. Glad we could help!

**Comment by alejandro-londono** [comment]
I look forward to v1.1!
