### ISSUE TITLE
static notification color doesn't obey the attribute

### ISSUE THREAD

**Issue by gusbicalho** [zurb/foundation-apps#523]
Static notifications always have the primary color as their background, no matter what you put in the `color` attribute of the directive. The right color class is being added to the notification container, but it doesn't cause the background to change.
Adding the `notification` class to the container (via the DOM inspector) solves the problem - currently, the static notification only has the `static-notification` class.

**Comment by jeanieshark** [comment]
Is this on the current master branch? This issue was previously reported (https://github.com/zurb/foundation-apps/issues/472) and subsequently fixed.

**Comment by gusbicalho** [comment]
Sorry, I'm working on the stable release. I had not seen that #472 report.
