### ISSUE TITLE
Open Modal on Startup

### ISSUE THREAD

**Issue by designchief** [zurb/foundation-apps#525]
Hi, I have been struggling with the Foundation Apps Modal.

How can I open a Modal on startup of App. It is for holding Terms and Conditions so I only need it to display once and never again once the Modal has been closed.

In foundation for sites you could:
$(document).ready(function(){$('#myModal').foundation('reveal', 'open')});
so I guess I am looking for something similar in Apps.

I have been on the Forum and Twitter with this query too, but I wan’t getting anywhere so said I would try you on github...

thanks, Kieran.

**Comment by escapedcat** [comment]
https://github.com/zurb/foundation-apps/issues/249
This might help.

Should work if you use your own controller instead of the default one.
Read 'Controllers' here http://foundation.zurb.com/apps/docs/#!/angular

**Comment by designchief** [comment]
Thanks escapedcat,

I have seen the Controllers documentation but the JS is beyond my understanding,
I have been trying to get it to work but not having any joy.
So I would need to create a custom controller for my Start page?
Is there somehwere in my JS that I could grab the current controller for that page so i can see what I need to do?

Sorry, JS novice here!!

**Comment by escapedcat** [comment]
No time come up with a full example at the moment, but I think this could work:

`app.js` add:
```js
angular.module('application')
.controller('MyController', MyController)
;
MyController.$inject = ['$scope', '$stateParams', '$state', '$controller', 'FoundationApi'];
function MyController($scope, $stateParams, $state, $controller, fa) {
angular.extend(this, $controller('DefaultController', {$scope: $scope, $stateParams: $stateParams, $state: $state}));
  // your code...
  // using the fa.publish() method described in issue #249
}
```

In your Start page template you add this to the `front matter` part:
```html
controller: MyController
```

Give it a try.
When I have time I might do a full example.

**Comment by designchief** [comment]
I tried the custom controller and got it to work ok - "StartController"
My Modal is #tcModal
--
angular.module('application')
.controller('StartController', StartController)
;
StartController.$inject = ['$scope', '$stateParams', '$state', '$controller'];
function StartController($scope, $stateParams, $state, $controller) {
angular.extend(this, $controller('DefaultController', {$scope: $scope, $stateParams: $stateParams, $state: $state}));
  // your code...
}
--
But when I add the "FoundationApi.publish('tcModal', 'open');" line below
it does not work, I just get a page with some elements missing which makes me think it is breaking the controller
--
angular.module('application')
.controller('StartController', StartController)
;
StartController.$inject = ['$scope', '$stateParams', '$state', '$controller'];
function StartController($scope, $stateParams, $state, $controller) {
angular.extend(this, $controller('DefaultController', {$scope: $scope, $stateParams: $stateParams, $state: $state}));
  // your code...
  FoundationApi.publish('tcModal', 'open');
}
--

**Comment by escapedcat** [comment]
Well done!
Compare the code I pasted to your code :)
You missed the reference to `FoundationApi`.
Inside the code you use `fa`.
Look at my code in detail. It's a bit different from the code of the docs. Just a bit.

**Comment by designchief** [comment]
Hi, I meant to say i had tried that, and then i had tried one like the one in the docs

Here is the code that I tried first that is the same as yours..

angular.module('application')
.controller('StartController', StartController)
;
StartController.$inject = ['$scope', '$stateParams', '$state', '$controller', 'FoundationApi'];
function StartController($scope, $stateParams, $state, $controller, fa) {
angular.extend(this, $controller('DefaultController', {$scope: $scope, $stateParams: $stateParams, $state: $state}));
  // your code...
  foundationApi.publish('tcModal', 'open');
}

**Comment by escapedcat** [comment]
Within the controller you should use `fa` not `foundationApi`

**Comment by designchief** [comment]
Wow, thanks for that,
it is loading up fine on startup now

**Comment by designchief** [comment]
Only problem now is that 
- the Modal content does not scroll (thought I fixed this with overflow:scroll) but obviously not so i cannot actually scroll to the end of the content 
and
- it looks like the Modal will show now every time that page is loaded, whereas I want the modal to only appear until the user presses the close button, in which case it will not appear again when they open or re-launch the app

I really appreciate your help, 
I have not been able to find an answer to this anywhere.

I was told on the Forum (Rafi) that the Modal was the best way to go for a Mandatory Terms and Conditions Page (user clicks to agree and then they don’t see the modal again unless we change something like update the app etc)

I thought that some of this functionality was built into the Modals? but I”m not sure how to do it

**Comment by webnugget** [comment]
If you wan't to save the result of the modal check out my issue on that topic.
[#515](https://github.com/zurb/foundation-apps/issues/515)

Just include [Angular-Modal-Service](https://github.com/dwmkerr/angular-modal-service) , open a new modal in your Controller with:

    ModalService.showModal({
      templateUrl: "yesno/yesno.html",
      controller: "YesNoController"
    }).then(function(modal) {
      modal.element.modal();
      modal.close.then(function(result) {
        $scope.yesNoResult = result ? "You said Yes" : "You said No";
      });
    });

Modalcontroller:

     var app = angular.module('sampleapp');
     app.controller('YesNoController', ['$scope', 'close', function($scope, close) {
     $scope.close = function(result) {
     	  close(result, 500); // close, but give 500ms for bootstrap to animate
      };
     }]);

ModalTemplate:

    <div class="modal-overlay is-active" id="login-modal"  >
        <aside id="login-modal-content" class="modal is-active">
            <a data-ng-click="closeModal()" class="close-button">×</a>
                <div class="grid-content">
                  <p> your terms and conditions</p>
                  <button type="submit" class="button medium" ng-click="close(true)">Submit</button>
               </div>
            </div>
         </aside>
      </div>

**Comment by designchief** [comment]
Hi webnugget, thanks for your comment.
I really dont know how to implement what you have there, and how it applies to my issue.

I am not familiar with JS and saving results etc,
so I guess I need more "How to.." type help...

thanks again

**Comment by rafibomb** [comment]
The <a href="http://foundation.zurb.com/forum">Foundation forum</a> would be a great place to seek some help. Jeanie from our team responded to your question there: http://foundation.zurb.com/forum/posts/23322-open-apps-modal-on-page-load

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by designchief** [comment]
Hi Rafi, thanks for your comment, I saw Jeanies’s comment and I have replied.

I know this has drifted off the original topic, but is there a defect with the Modal that prevents the scrolling of content that is larger than the height of the device. My modal wont scroll at all, so is that a defect?
