### ISSUE TITLE
How to add compass to a Foundations for Apps project?

### ISSUE THREAD

**Issue by Joe-5mith** [zurb/foundation-apps#526]
How should one add compass to a Foundations for Apps project that: 

1. is installed using `foundation-apps new` with the CLI, 
2. will allow one to use compass mixins, for example, in custom .scss files located at "clients/assets/scss"?

**Comment by escapedcat** [comment]
What functionality do you need/miss from Compass?

**Comment by Joe-5mith** [comment]
For example, I am using `ng-show` and I would like the elements to fade in and out (or slide in and slide out etc). I am thus using an approach similar to that described in issue [#414](https://github.com/zurb/foundation-apps/issues/414) by [jeanieshark](https://github.com/jeanieshark). In essence, I am overriding the angularjs-provided css classes: `.ng-hide-add` and `.ng-hide-remove`.

I would like to use compass to describe the transition/animation. Examples of mixins I might use are:
```
@include transition-property(left);
@include transition-duration(1s);
@include transition-timing-function(ease)
```

I might also wish to style my pages using compass mixins  - do you think there is a better way or do you think this is a bad idea?

**Comment by escapedcat** [comment]
Just use default CSS to achieve this and use [Autoprefixer](https://github.com/sindresorhus/gulp-autoprefixer) if you need to support older browsers with prefixes or different syntax.

Here is a good article about what it does:
https://css-tricks.com/autoprefixer

If those mixins are the only functions you use from Compass I'm sure you can stop using it after this.

**Comment by Joe-5mith** [comment]
I'm happy using Autoprefixer for vendor prefixes but I do use many other Compass functions like Compass Sprites. Are you suggesting one should avoid Compass if possible, generally speaking?

**Comment by escapedcat** [comment]
Hm, yes, I try to avoid Compass.
The last time I actually used old school png sprites I used https://github.com/Ensighten/spritesmith
For things like icons nowadays I would [use SVGs](https://css-tricks.com/svg-sprites-use-better-icon-fonts).

**Comment by Joe-5mith** [comment]
Okay, I understand why you wouldn't post how to add Compass to FA then. I might do without it anyway.

Thanks for your quick replies.

Referring to the example I gave above, it would be great if the Foundation for Apps Motion UI classes could be used with directives like `ng-show`.

**Comment by gakimball** [comment]
There's a [gulp-compass](https://www.npmjs.com/package/gulp-compass) plugin that you can swap into your project. Run `npm install gulp-compass --save-dev` to get it in your project, and then follow the instructions on the readme to get it set up. You'll be replacing the call to `$.rubySass` in the Gulpfile to `$.compass`, under the `sass` task.

Your project will also need a `config.rb` file, like a normal Compass project would. The config file needs to reference the Foundation for Apps Sass as an import path:

```ruby
add_import_path "bower_components/foundation-apps/scss"
```

**Comment by soumak77** [comment]
As alluded to above, are there plans to integrate animations with ng-show or ng-hide?  So far everything I want to use animations on requires using ng-if.

**Comment by gakimball** [comment]
@soumak77 The classes follow ngAnimate's format; what would we need to change to make them work? I know they work with `ng-repeat`.

**Comment by soumak77** [comment]
@gakimball I started using F4A when it first came out and couldn't get the ng-show or ng-hide animations to work out of the box like I did with ng-if.  The apps I build are used to run my business and being the only developer at my company, I haven't had much time to investigate alternate solutions. Animations are not critical to my apps since I just need them to work and not necessarily be flashy (though that is always a plus).  I'll let you know when I find the time to investigate this issue more in detail.

@Joe-5mith Do you have any examples you can share that showcase ng-show animations not working?  If so, could you create another issue with those details?  I'd do this myself at some point, but I don't foresee being able to get around to it in the near future.

**Comment by soumak77** [comment]
@gakimball In your testing of v1.1 and the rework done to animations, did you try using ng-show or ng-hide in any of your tests/examples?  I know this is a lot to ask, but it would be extremely helpful if there was a page in the docs that showed how to integrate the Motion UI into angular, with examples of ng-if, ng-show, ng-hide, ng-repeat, and others if there are more.  Perhaps just integrating some animations into the existing [examples](http://foundation.zurb.com/apps/resources.html) would help to clarify exactly how the Motion UI classes should be used with angular directives.

**Comment by gakimball** [comment]
@soumak77 Okay, so the reason is that there are five types of Angular transition classes: enter, leave, move, add, and remove. Our motion classes support the first two: enter and leave. We should be able to add support for the rest just by chaining those other classes to the existing selectors. By adding at least add/remove, we get support for `ng-show` and `ng-hide`.

**Comment by soumak77** [comment]
@gakimball Awesome!  Thanks for figuring that out!  Are you thinking that could get into v1.1 or is it too close to your desired deadline?

**Comment by gakimball** [comment]
@soumak77 It's possible, I'll see how quickly we can put together a test case. It's a relatively simple Sass change, though.

**Comment by gakimball** [comment]
@soumak77 And done!

**Comment by soumak77** [comment]
@gakimball If only they were all that easy!  Can't wait to get my hands on v1.1!
