### ISSUE TITLE
FoundationApi.publish('..', 'toggle') causes $digest already in progress error

### ISSUE THREAD

**Issue by excessivedemon** [zurb/foundation-apps#528]
I'm using dist/foundation-apps.js and calling FoundationApi.publish('[id_of_my_panel_goes_here]', 'toggle') on one of my controllers causes a $digest already in progress error. Digging through the codes, line number 2452 (of dist/foundation-apps.js) should be wrapped in an if(!scope.$root.$$phase) like so:

          if(!scope.$root.$$phase) {
            scope.$apply();
          }

**Comment by jeanieshark** [comment]
@excessivedemon This issue is currently fixed in master, so you are free to pull that down and see if your controller is functioning as expected there.

Otherwise, we're releasing our 1.1 patch today that resolves this issue and will have a new foundation-apps.js file available.

Thanks!
