### ISSUE TITLE
Document v-align

### ISSUE THREAD

**Issue by Globegitter** [zurb/foundation-apps#529]
I think being able to vertically align elements is a great feature, which is quite hard to do without flexbox. I was quite surprised to not find anything in the docs, but I did find http://stackoverflow.com/questions/27385545/vertical-align-div-in-zurb-foundation-for-apps which I got to work.

Would be great to have in the official documentation as well :)

**Comment by gakimball** [comment]
Definitely, we'll see about getting it in soon.

**Comment by Globegitter** [comment]
Thank you - very much appreciated.
