### ISSUE TITLE
show-for-*, hide-for-* doesn't obey ng-hide

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#530]
Showing and hiding elements using ng-show/ng-hide directives does not work on elements that use show-for-* as the show-for-* forces the elements to be displayed.  I'll submit a PR once I get it fixed.

**Comment by soumak77** [comment]
My original title was correct, this also doesn't work for hide-for-*.  I'll submit another PR for that fix.

**Comment by gakimball** [comment]
Merged with 40abb575efde27fcff8c59b8ee18fff417a9919c

Thanks! :)
