### ISSUE TITLE
Why use custom pub/sub instead of $rootScope?

### ISSUE THREAD

**Issue by circlingthesun** [zurb/foundation-apps#536]
A custom pub/sub implementation is slightly more performant than if one were to use $rootScope to pass messages. However, it makes it easier to leak memory when one forgets to unsubscribe to an event when a scope is destroyed. The pub/sub also adds to learning curve of Foundation for Apps as someone will have to wrap their heads around the Foundation pub/sub system in addition to the Angular event system. Using $rootScope would also reduce the degree component coupling to the core.

Here is an interesting article by Ben Nadal that illustrates the benefits better than I can: http://www.bennadel.com/blog/2734-using-the-scope-tree-as-a-publish-and-subscribe-pub-sub-mechanism-in-angularjs.htm

As a side note, in your contribution guide it states that contributors should tag their issues. I'm not sure non collaborators have permission to do that.

**Comment by soumak77** [comment]
I agree with @circlingthesun.  I recently switched all the internal messaging in my apps to use the angular pub/sub method as it greatly simplified sending messages and data from one part of the app to another.  One additional benefit of using the angular sub/pub, is that you can broadcast messages to your children elements only as well as emit from your child elements to the parent, which could be useful in some of the foundation components.

**Comment by circlingthesun** [comment]
Also, if every angular library implemented its own pub/sub system, using more than a few in a project would quickly become a headache.

**Comment by gakimball** [comment]
You think there's any way to make improvements that are backwards-compatible, or would we need to wait for a major release to work on this?

It's also likely that v2 of this framework will be written in Angular 2, so then all of this is out the window anyway ;)

**Comment by soumak77** [comment]
I think it is possible to come up with a solution for backward compatibility (e.g. turn foundation sub/pub into wrapper for $rootScope $on/$broadcast and internally switch to using only angular sub/pub), however, in agreement with your last statement, it's all throw away work if the framework is converted to angular 2 (which I'm all for!).  Unless there are limitations in the foundation sub/pub that must be fixed to develop certain features, I'm not sure converting to use the angular sub/pub system would be worth the cost.  Having used F4A for awhile now, I rarely use the foundation sub/pub in my JS code as the F4A directives take care of most cases where it's needed, so being required to continue to use the foundation sub/pub in those rare cases isn't a huge deal for me.

**Comment by gakimball** [comment]
Sounds solid. We have no timeline for a v2 of Foundation for Apps, but there's also no real timeline for Angular 2's release. We're keeping a close eye on it, though.

With that in mind, I'm going to close this out. There are some big things that we have to wait until a major version to change. But we're always keeping track of this stuff, so we love the feedback. Keep it coming! :)
