### ISSUE TITLE
bower.json main entry should include dist/js/foundation-apps-templates.js

### ISSUE THREAD

**Issue by excessivedemon** [zurb/foundation-apps#537]
bower.json main entry should include dist/js/foundation-apps-templates.js. Lines 4-8 on bower.json should read like so:

  "main": [
    "dist/css/foundation-apps.css",
    "dist/js/foundation-apps.js",
    "dist/js/foundation-apps-templates.js"
  ],  

To allow for tools like wiredep to properly include foundation app component's templatecache.

**Comment by gjungb** [comment]
also see #534

**Comment by gakimball** [comment]
Merged with this commit: ab6303639d8b2bc26dd77d758d91746111c3996b
