### ISSUE TITLE
Question: Swipe close notifications in notification set

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#543]
Is there a way to configure the notifications added by the notification set to swipe close?  I'm looking through the code and it doesn't seem possible as is, though adding it shouldn't take too long.

**Comment by soumak77** [comment]
I see that swipe close is already hooked up for all notifications.  Unfortunately there doesn't seem to be a way to configure the animation, though it nicely defaults to fadeIn/fadeOut.

**Comment by jeanieshark** [comment]
@soumak77 The swipe configuration is hooked up to the hide method, so if you set the attributes of animation-in/animation-out to the desired animations, the notifications should use those animations to hide.

Let me know if this isn't the case!
