### ISSUE TITLE
Why is forms the only component not utilizing exports

### ISSUE THREAD

**Issue by localnerve** [zurb/foundation-apps#544]
I have a question: Why doesn't the forms component use the exports mixin?

I noticed that the "forms" scss component is the only one that does not utilize the exports mixin. It's output is not controllable using $include-css in settings.

I know I can just manually control this, rather than just importing foundation and using settings to control it. However, I'm curious why this exception was made (It looks deliberate).

Thanks for publishing such a great tool, and thanks for taking the time to read this question.

**Comment by gakimball** [comment]
Well, unfortunately it was an oversight, but it's been fixed now. No CSS output in the framework should be hardcoded, except the `<meta>` styles we use to pass the media queries to the JavaScript.

**Comment by localnerve** [comment]
Excellent. Thank you. I noticed you did not update the package semver. Any idea when this update will be available via npm?

**Comment by gakimball** [comment]
We try to put out patches every few weeks, depending on how many crazy bug fixes we need to get out the door. So at best I can say "a week or two", but we don't have a date right now.
