### ISSUE TITLE
Feature request: ng-repeat move animations

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#546]
I like how easy F4A makes animating the enter and leave states when using ng-repeat.  I would really like to also be able to animate move states as well.  I tried adding this to the existing motion SCSS and it works, however, it uses the same animations as enter and leave, which is not desirable.  I have a vertical list that dynamically changes and I hooked up the enter/leave to slide items left or right based on whether they were entering or leaving the list.  I want to be able to perform a slide up animation when something is moved in the list.

**Comment by gakimball** [comment]
The move process seems to be very similar to enter, except that the class is different. Is there any real difference, or can we just chain `.ng-move` to `.ng-enter` and `.ng-show`?

**Comment by soumak77** [comment]
Yeah you should be able to hook it up the same way as ng-enter and ng-show.  I did that and it worked when I gave a fake class for the out animation in the SCSS, but I didn't take it future as some redesign is needed since you'll have to require another animation class.  As I mentioned in my example, I want to be able to use a different animation for move than in/out as the move animation is along a different axis than the in/out animation.

**Comment by gakimball** [comment]
Ah I see, so we need to prevent collision between enter/show and move. Ideally we find a way to do that without outputting a ton of extra CSS. Or we relegate it to a mixin-only feature, to keep our file size down.

I also need to eventually take a look at how we store all these animation classes, if there has to be three sets of them. It would be better if the Sass variables looked like this:

```scss
$motion-classes-enter: 'ng-enter', 'ng-show', 'ng-move';
$motion-classes-leave: 'ng-leave', 'ng-hide';
```

There are some nice selector manipulation functions in Sass 3.4 that would probably help, but they aren't in libsass yet (and probably won't be for a while), so I might write something that recreates what I need.

**Comment by gakimball** [comment]
I opened a pull request that implements `ng-move` here: #560 

The Sass variable situation is becoming messy, but we'll roll with it for now. You can test this branch on an existing project with `bower install foundation-apps#ng-move-motion`
