### ISSUE TITLE
Panel: undefined srcElement

### ISSUE THREAD

**Issue by laurent-le-graverend** [zurb/foundation-apps#548]
Not sure why there is this check, getting a JS error when clicking somewhere in the panel:

Getting error: `Uncaught TypeError: Cannot read property 'href' of undefined`

https://github.com/zurb/foundation-apps/blob/master/js/angular/components/panel/panel.js#L130

```
  element.on('click', function(e) {
    //check sizing
    var srcEl = e.srcElement;
    [...]
```

srcElement seams to be something for IE?
https://developer.mozilla.org/en-US/docs/Web/API/Event/target

**Comment by gakimball** [comment]
Yep, that should be `e.target` instead of `e.srcElement`.
