### ISSUE TITLE
What is the best way to update an existing app?

### ISSUE THREAD

**Issue by Dillie-O** [zurb/foundation-apps#553]
Apologies if this is published elsewhere, I seem to have missed it.

I jumped on early with Z4A and am still loving it! I noticed that 1.1 is out and I know there have been fixes aplenty, so I'm thinking it is time for me to update my existing app. What's the recommended way of doing this?

I see I need to do an `npm update -g foundation-cli` to update the CLI, but from there do I do a `foundation update` to update my existing app, or would it be better to do a more standard `bower update` since all of the foundation packages are referenced there.

Thanks in advance!

**Comment by gakimball** [comment]
The CLI will work with your current projects, so you can update it no problem.

As you correctly guessed, most of the CLI's commands are wrappers for Bower and npm functions. So `foundation-apps update` is the same as `bower update`, and `foundation-apps watch` is running `npm start`, which runs a local copy of Gulp. (This means you don't need Gulp installed globally for it to work.)

This abstraction will make more sense when we move Foundation 6 and Ink 2 onto this CLI, and then all three frameworks will use the same tool. The command name will also change to just `foundation`.

Glad you're loving it! We feel really good about 1.1, it's *way* more stable than 1.0. :)
