### ISSUE TITLE
Implementing foundation-apps on existing rails app

### ISSUE THREAD

**Issue by jolenekernick** [zurb/foundation-apps#557]
I don't want to create a brand new app, I want to take my existing rails app and throw foundation-apps into it. I have node and gulp installed, just not sure how to get foundation-apps working without creating a new app.

**Comment by gakimball** [comment]
If you're fine with it not being a single-page app, then you should be able to just drop in the CSS, and the JavaScript for Angular and Foundation and it'll work. We distribute the files on npm and Bower, so you can get the compiled CSS and JS from there.

If you want it to be an actual single-page app, though, that's a whole new can of worms. Normally Rails handles your URL routing, and serves up all the HTML. With Angular, however, your app has to have one entry point (an `index.html` file), and Angular handles all of the routing and rendering of HTML.

We recently redesigned the [ZURB Library](http://zurb.com/library), which is a Rails application that uses Angular on the front-end. The server redirects all requests to `index.html`, and Angular handles the route from there. Also, Rails doesn't serve up any HTML; the backend is just an API that sends data to the client as JSON, and Angular uses it to write the HTML for each page.
