### ISSUE TITLE
Allow pass-through properties in dynamic routing

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#562]
I'm using an angular module that provides route security by performing authentication on states if the ```authRequired``` property of the state set to true.  In order to use this module with F4A and dynamic routing, I need to pass the ```authRequired``` property from the front matter to the state object.  Is there a generic solution that could be used to pass data from the front matter to the state versus having to hard code specific use cases that may or may not be valid for all developers?

**Comment by mkrakowski** [comment]
I'm assuming that what you're asking is how to pick up the authRequired variable from the front matter within your app. 

Front matter,
---
name: secure=page
url: /secure/page
animationIn: fadeIn
data:
  authRequired: true
---

Then in "$rootScope.$on" you can grab the authRequired param, "toState.data.authRequired".  Be sure to pass in toState into the .$on function,

$rootScope.$on('$stateChangeStart', function (event, toState, toParams, sessionService) { 
  toState.data.authRequired
});

**Comment by soumak77** [comment]
@mkrakowski thanks for the tip!  Luckily I had control over the module I was using so I could change the state references to use data.authRequired instead. BTW, in order to get it working I had to use the following notation in my front matter:
```
---
name: app.search
url: /search
controller: SearchCtrl
data: { authRequired: true }
---
```
