### ISSUE TITLE
Bottom of text gets cut off in block-list form inputs on Firefox

### ISSUE THREAD

**Issue by Joe-5mith** [zurb/foundation-apps#566]
Here's a screenshot from the [docs block list page] (http://foundation.zurb.com/apps/docs/#!/block-list), using Firefox 36.0.1:

![screen shot 2015-04-01 at 17 32 29](https://cloud.githubusercontent.com/assets/11408683/6945973/263a6356-d895-11e4-8cf9-a3f00bf25e27.png)

**Comment by gakimball** [comment]
I'm amazed how complicated the math for this turned out to be.
