### ISSUE TITLE
No scrolling for .grid-content.shrink

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#568]
When using the code below I often get a scroll bar shown for the element
```html
<div class="grid-content shrink">
...
</div>
```
I'm wondering if scrolling can be disabled for the ```.grid-content.shrink``` selector.  I'll add it to my own SCSS but I'm wondering if it would be good to include by default as I'm not sure when you would want a scrollbar to appear in that case.

**Comment by gakimball** [comment]
There shouldn't be a scroll bar if a grid element is shrunk, because "shrink" means "this element should only take up the space it needs". So using `overflow: hidden` (or `overflow: visible` to make using dropdown menus easier) as a default would make sense.
