### ISSUE TITLE
Custom Controller Error 'DefaultController' is not a function

### ISSUE THREAD

**Issue by NicoBleh** [zurb/foundation-apps#576]
Hi,

implementing a custom controller.

    angular.module('application').controller('SignInCtrl', SignInCtrl);
    SignInCtrl.$inject = ['$scope', '$stateParams', '$state', '$controller'];

    function SignInCtrl($scope, $stateParams, $state, $controller, $auth) {
      angular.extend(this, $controller('DefaultController', {
          $scope: $scope,
          $stateParams: $stateParams,
          $state: $state
      }));

      $scope.handleLoginBtnClick = function () {
          $auth.submitLogin($scope.loginForm)
              .then(function (resp) {
                  console.log('Logged in');
              })
              .catch(function (resp) {
                  // handle error response
              });
      };

    }

When i call up the page the console output gives me:

Error: [ng:areq] Argument 'DefaultController' is not a function, got undefined

Edit:

It seems to have something to do with not using 'foundation.dynamicRouting'.
I followed https://github.com/zurb/foundation-apps/issues/501#issuecomment-76715381 because dynamic routing does not expose resolve functionality https://github.com/zurb/foundation-apps/issues/387 but i need this for using ng-token-auth https://github.com/lynndylanhurley/ng-token-auth

**Comment by gjungb** [comment]
@NicoBleh If you do not want / need to use the ```foundation.dynamicRouting``` module, there is not need at all to extend the ```DefaultController``` which is part of the above mentioned module. So simply delete the ```angular.extend(...)``` rows and everything should work fine.
BTW: you forgot to include ```$auth``` as last element in the ```$inject``` array.

**Comment by NicoBleh** [comment]
@gjungb thanks i really forgot to inject $auth. I deleted the extend rows and moved on.

The main problem was that
    
    $scope.handleLoginBtnClick = function () {
    ...
    }
was not handled. So i guessed that it had something to do with not extending the SignIn controller with the DefaultController.
I turns out that it has to be done like that:

    $scope.$on('auth:login-success'), function (ev, user) {
    ...
    }

**Comment by jeanieshark** [comment]
Closing this issue since it seems like it had something to do with the ng-token-auth API usage. :)
