### ISSUE TITLE
How can I use autocomplete in foundation app 

### ISSUE THREAD

**Issue by dipongkor** [zurb/foundation-apps#577]
in the document site http://foundation.zurb.com/apps/docs/#!/ there is autocomplete box. But can I use it in my app.
![autocomplete](https://cloud.githubusercontent.com/assets/4987425/7061131/2ae4adec-deaf-11e4-8cdf-6c9ba969cc35.png)

**Comment by gakimball** [comment]
The plugin is called [allmighty-autocomplete](https://github.com/JustGoscha/allmighty-autocomplete) if you want to use it. It's not developed by us; we just use it in our documentation.

**Comment by dipongkor** [comment]
Shall we get it from you in any upcoming update?

**Comment by gakimball** [comment]
We don't plan to include it with the framework by default, but it's pretty easy to integrate into an existing project. Run `bower install allmighty-autocomplete --save`, then add the path to the array of JavaScript paths in your Gulpfile. The library also includes a CSS file with some default styles you can use.
