### ISSUE TITLE
More clarification on grid docs

### ISSUE THREAD

**Issue by Globegitter** [zurb/foundation-apps#579]
I love using foundation apps, but the docs for the grid are quite bare right now, which imo makes the bahviour hard to understand. For example here

![screen shot 2015-04-09 at 22 06 55](https://cloud.githubusercontent.com/assets/2580254/7076926/c83967b8-df04-11e4-8ceb-cb2b92de4911.png)

it shows a simple example, which seems easy to understand. But further down you get to `grid-content`:

![screen shot 2015-04-09 at 22 07 29](https://cloud.githubusercontent.com/assets/2580254/7076945/df67eac2-df04-11e4-97f7-65214afb2983.png)

So does this mean now that in the first example I would put another `grid-content` once I put in some actual content? Does that mean you basically put `grid-content` always at the very last level?

Playing with that in my current app and it is sometimes really changing how things look, if they are aligned vertically or horizontally just by adding `grid-content`. IT would be great to extend the example by actually adding links, buttons, text in them. To make it more clear how this would look on an actual website.

Otherwise great work so far on foundation-apps. Keep it going :)

**Comment by gakimball** [comment]
We're working on improvements to the grid documentation, namely using... y'know, *actual examples*, so look forward to that.

We've had some trouble explaining the difference between the three grid elements—the frame, block, and content block. Recently though, we've found an easier way to frame it. (But you're right, `.grid-content` is always the lowest-level.)

Here's a no-frills grid. It only uses two of the elements.

```html
<div class="grid-frame">
  <div class="small-3 grid-content"></div>
  <div class="small-3 grid-content"></div>
  <div class="small-6 grid-content"></div>
</div>
```

Here's that same grid if we nested a new grid inside the first element. It adds a new, third element for nesting purposes.

```html
<div class="grid-frame">
  <div class="small-3 grid-block">
    <div class="grid-content"></div>
    <div class="grid-content"></div>
  </div>
  <div class="small-3 grid-content"></div>
  <div class="small-6 grid-content"></div>
</div>
```

The main difference from a typical float grid is that you can add sizing, source ordering, etc. classes to block *and* content.

**Comment by Globegitter** [comment]
Thanks for the clarification @gakimball and that is great news! Keep up the good work :)
