### ISSUE TITLE
Animating ui views without FM

### ISSUE THREAD

**Issue by dioklecijan** [zurb/foundation-apps#583]
I am not sure am I doing something wrong or there is an issue with animating view transitions.
To get it work without FM, I had to load `foundation.dynamicRouting.animations` and define global `foundationRoutes` array to prevent an error *foundationRoutes is not defined at DynamicRoutingConfig*. Wihout using FM, I expect that following should work:

```javascript
  //var foundationRoutes = [];
  angular.module('theApp', [
      'ui.router',
      'ngAnimate',
      'foundation'
      //,'foundation.dynamicRouting.animations'
    ])

  angular.module('theApp')
    .config(function ($stateProvider) {
      $stateProvider
        .state('main', {
          url: '/',
          templateUrl: 'app/main/main.html',
          controller: 'MainCtrl',
          controllerAs: 'main',
          animation: {
            enter: 'slideInRight',
            leave: 'slideOutRight'
          },
          ...
```
but I had no success without uncommented code.
I'm using foundation-apps 1.1.0 and custom (full stack) grunt file.

**Comment by gakimball** [comment]
It's a little awkward right now, but you do need both the `foundation.dynamicRouting` and `foundation.dynamicRouting.animations` modules to make it work, even if you're not using our routing plugin.

When we released 1.0, view animations only worked with the routing plugin. We fixed this in 1.1, but to maintain backwards compatibility, we didn't want to change the names of the modules. Unless there's a way for us to create a module alias, so we can change the name, we'll have to keep the naming convention as-is for the time being.

**Comment by dioklecijan** [comment]
Thank you for the quick answer. 
However, I still have to define global `foundationRoutes` array to prevent an error. 

It would eliminate need for this weird array definition (and spare some time investigating why code recipe from official documentation does not work) if you test is `foundationRoutes`array defined before using it in registering dynamic routes .

Something like:

```javascript
function DynamicRoutingConfig(FoundationStateProvider) {
    if(typeof foundationRoutes === 'undefined') {
      foundationRoutes = [];
    }
    FoundationStateProvider.registerDynamicRoutes(foundationRoutes);
  }
```

**Comment by gakimball** [comment]
Seems like that fix will work fine for now. [There's been talk](https://github.com/zurb/foundation-apps/pull/550#issuecomment-88192466) about making the routing plugin's process a little more robust than dropping an array into the `window` object, so look forward to that!
