### ISSUE TITLE
Animating Views with Motion UI Overlap

### ISSUE THREAD

**Issue by huphtur** [zurb/foundation-apps#585]
When setting up animated views on 2 pages (according to the instructions from the [Motion UI doc](http://foundation.zurb.com/apps/docs/#!/motion-ui)) a weird stacked overlap seems to occur.

I've set up a simple [test case](http://foundation-apps-motion-ui.s3-website-us-east-1.amazonaws.com/). Is this a bug or incorrect use of Motion UI on my behalf? 

Front matter used:
```
---
name: home
url: /
animationIn: slideInRight
animationOut: slideOutRight
---
```
and
```
---
name: about
url: /about
animationIn: slideInRight
animationOut: slideOutRight
---
```

**Comment by gakimball** [comment]
The ghosting issue is a WebKit bug, but we have a workaround in the CSS. However, the setup for the animation isn't working properly. The first parent of the views should temporarily get a class called `.position-absolute`, but here it's not. We'll look into it.

**Comment by gakimball** [comment]
Could you try reworking your HTML so that the `ui-view` element is wrapped by a `grid-block`? So it would look something like this:

```slim
.grid-frame.vertical
  .grid-content.shrink
  .grid-block
    .grid-content ui-view
      .grid-container
```

**Comment by huphtur** [comment]
[Same result](http://foundation-apps-motion-ui.s3-website-us-east-1.amazonaws.com/#!/).

Chrome seems to mimic Firefox behavior more, however Firefox now shows a scrollbar for a brief moment.

**Comment by austinmbrown** [comment]
I'm running into this same issue. Anyone turn up a good workaround? Or is a fix close?

**Comment by gakimball** [comment]
Try adding the class `.ui-animation` to the view and see if that fixes it. That won't be necessary in the next version of the framework (e64d2eee89ac7f4b7e9b5cecea17b68d2b6c460c).

**Comment by austinmbrown** [comment]
Cool, thanks. That resolved the overlap issue, but now it seems like the view gets taken out of the flow while the animation runs - it jumps up to the top of the screen while running. I'll see if I can sort out why. Really appreciate the quick help :)

**Comment by gakimball** [comment]
This happens because both views are temporarily `position: absolute`. But the wrapper element around the `ui-view` container is what should prevent the two views from shifting around. If the wrapper and the view are the same size, you shouldn't be able to tell.

**Comment by austinmbrown** [comment]
Aha - wrapped it in a .grid-block and now it's perfect. Thank you so much! :rocket:

**Comment by gakimball** [comment]
Nice! We know it's a little confusing ;) In a future version of the framework we'll just build in the container class, like `.ui-view-container` or something like that. We're also currently writing a tutorial on Foundation for Apps that will cover view animation.

@huphtur, let me know if these fixes work. There's two parts to setting up view animation:
1. Give the `ui-view` a class of `.ui-animation`.
2. Wrap the view in a parent container that has the same size. Usually this is just another `.grid-block`.

**Comment by philippeluickx** [comment]
+1, looking forward to the guide!

**Comment by DeanSolecki** [comment]
Could someone post a working example of this somewhere?  I get different types of inexplicable behavior no matter what sequence of block/container/content/frame I use.  It either stacks during the animation, falls in from the top left corner, or shifts violently left to right after the animation runs.

**Comment by DeanSolecki** [comment]
Nevermind, this pattern works.

<div class="grid-frame vertical">
	<div class="grid-block">
		<div class="grid-content ui-animation" ui-view></div>
	</div>
</div>

**Comment by gakimball** [comment]
The markup @DeanSolecki wrote is the right way to do it. If anyone has any more problems let me know!
