### ISSUE TITLE
Documentation on how to add external libraries

### ISSUE THREAD

**Issue by philippeluickx** [zurb/foundation-apps#590]
Hey!
Thanks for a great framework, feels good.

As a beginner, I am struggling with something that I thought would be basic: adding external libraries. Let's say I want to add https://github.com/chieffancypants/angular-loading-bar and have this working. I changed the gulpfile to include the js just so:

```javascript
  // These files are for your app's JavaScript
  appJS: [
    'client/assets/js/app.js',
    'bower_components/angular-loading-bar/src/loading-bar.js'
  ]

```

And for the js part, that does the job, incl minimizing.

However, how to do something similar for the *css*? In no case this shows up in my build folder... I tried importing it in my  app.scss and adding it to the sass path, but no good.

```javascript
  // Sass will check these folders for files when you use @import.
  sass: [
    'client/assets/scss',
    'bower_components/foundation-apps/scss',
    'bower_components/angular-loading-bar/src'
  ],
```

As this is so fundamental, would be great to have some docs about this.
Thanks!

**Comment by soumak77** [comment]
@philippeluickx I recently had to do this with my own project when incorporating [Prism](http://prismjs.com/).  My build is more complex than the one that ships with F4A, however, I took the relevant parts related to copying 3rd party CSS and pasted them below.  No guarantee the code works as is, but should give you enough info to do the same in your project.

First I added a new variable to hold raw CSS files like so:
```js
var appCss = [
    './bower_components/prism/themes/prism.css',
    './bower_components/prism/plugins/line-numbers/prism-line-numbers.css',
    './bower_components/prism/plugins/line-highlight/prism-line-highlight.css'
];
```
Then I used this new variable in a separate gulp task:
```js
gulp.task('css', function() {
  return gulp.src(appCss)
    .pipe(gulp.dest('./build/assets/css/'));
});
```
Finally I added the new task to be run as part of the existing build task:
```js
gulp.task('build', function() {
  runSequence('clean', 'jshint', ['copy', 'sass', 'css', 'uglify'], 'copy-templates', function() {
    console.log("Successfully built.");
  })
});
```

The above does not combine the 3rd party css into the app.css file generated by the ```sass task```.  As such, **you'll need to explicitly include the 3rd party css in your index.html file**.  You could easily rewrite the gulp task that combines the app.css with your 3rd party css so you only need to have a single css file referenced in your index.html.  If you did do this, you would have to make sure to run the ```css task``` AFTER the ```sass task```, which could easily be done by changing the location of the ```css task``` in the ```runSequence``` call like so:
```js
gulp.task('build', function() {
  runSequence('clean', 'jshint', ['copy', 'sass', 'uglify'], 'css', 'copy-templates', function() {
    console.log("Successfully built.");
  })
});
```

**Comment by philippeluickx** [comment]
That makes sense, thanks for sharing!
The alternative for explicitely including the css files in the index.html is to import them in the app.scss.

Keeping this open still, would like to know if there are any best practices. Should css be minified and compiled into one giant css file, incl. 3rd party styles? Or copy the minified css files from the 3rd packages and then referencing them (either in css or html)?

**Comment by gakimball** [comment]
Sass can't import plain CSS files using `@import`, only other Sass files. Thankfully, it's pretty easy in Gulp to just insert those extra CSS files.

To add external CSS to your main CSS file (which was compiled from Sass), there's two steps to take.

First, add the plain CSS files to `gulp.src`. The files will be combined in the order you list them.

```js
return gulp.src(['path/to/file.css', 'path/to/sass.scss'])
  .pipe(/* ... */)
```

Next, add a concatenation step to the stream. gulp-sass will ignore your plain CSS, only processing the Sass files. But now we have two CSS files, and we need to combine them into one. gulp-concat will do this for us, and the template project includes it.

You can insert concat before or after autoprefixer, just make sure you do it before `gulp.dest()`.

```js
// Compiles Sass
gulp.task('sass', function () {
  gulp.src(['path/to/other/file.css', 'client/assets/scss/app.scss'])
    .pipe($.sass({
      includePaths: paths.sass,
      outputStyle: (isProduction ? 'compressed' : 'nested'),
      errLogToConsole: true
    }))
    .pipe($.autoprefixer({
      browsers: ['last 2 versions', 'ie 10']
    }))
    .pipe($.concat('app.css'))
    .pipe(gulp.dest('./build/assets/css/'))
  ;
});
```

In the future we'll see about adding more documentation on how the template stack actually works. The Gulp team itself doesn't publish any best practices for how to structure a Gulpfile, but if you want to see how "the big kids" do it, I'd recommend you check out Google's [Web Starter Kit](https://github.com/google/web-starter-kit/blob/master/gulpfile.js) and the [HTML5 Boilerplate](https://github.com/h5bp/html5-boilerplate/blob/master/gulpfile.js).

Hope this helps!

**Comment by philippeluickx** [comment]
Great, thanks for the info!
