### ISSUE TITLE
ZF-modal doesn't always open

### ISSUE THREAD

**Issue by mannyhenri** [zurb/foundation-apps#593]
In many cases I have to refresh the page before the modal opens. If you need an exemple you can look at thomas.mannydesigns.co

**Comment by gakimball** [comment]
Which control on the page should open the modal? And could you post the code for the modal and the element with `zf-open` that triggers the modal?

**Comment by mannyhenri** [comment]
Here is the code...
      <div ng-repeat="servicesItem in servicesItems">
        <a zf-open="#{{$index}}">
          <div class="grid-content">
            <img src="http://cpanel.mannydesigns.co:3000/api/containers/container4/download/{{servicesItem.image}}"
                 class="imgTeam">
          </div>
          <div class="grid-content textBlock">
            <div class="grid-container">
              <h3>{{servicesItem.title}}</h3>

              <p>{{servicesItem.details | limitTo: 125}}...(Plus d'info cliquez)</p>
            </div>
          </div>
        </a>

        <div zf-modal="" id="#{{$index}}">
          <a zf-close="#{{$index}}" class="close-button">×</a>

          <h3>{{servicesItem.title}}</h3>

          <p>{{servicesItem.details}}</p>
        </div>
      </div>
