### ISSUE TITLE
Foundation Apps/Browserify

### ISSUE THREAD

**Issue by philglen** [zurb/foundation-apps#599]
Hi I am new to Foundation, I am migrating from Bootstrap because your style foundation seems awesome and as I am using a single page Angular App, the foundation-apps seemed to be perfect CSS framework to work with directives.

However when I installed it and tried to require in my main.js file which sets up the Angular App:

'use strict';

var $ = require('jquery'),
    angular = require('angular');

// angular modules
require('angular-ui-router');
require('foundation-apps'),
require('./templates');
require('./controllers/_index');
require('./services/_index');
require('./directives/_index');

// create and bootstrap application
angular.element(document).ready(function() {

  var requires = [
    'ui.router',
    'foundation-apps'.charAt,
    'templates',
    'app.controllers',
    'app.services',
    'app.directives'
  ];

  // mount on window for testing
  window.app = angular.module('app', requires);

  angular.module('app').constant('AppSettings', require('./constants'));

  angular.module('app').config(require('./routes'));

  angular.module('app').run(require('./on_run'));

  angular.bootstrap(document, ['app']);

});

I get a gulp error:

Cannot find module 'foundation-apps' from '/Users/philglen/Sites/Totemic/app/js'

Any ideas??

- Phil

**Comment by gakimball** [comment]
We don't support Browserify, or any other module loaders right now, but it's something we'll look into eventually. In the mean time, the correct name of the Angular module is just `foundation`, not `foundation-apps`.

The `foundation` module gets you every UI component at once, but you can also only import individual elements, like `foundation.panel` or `foundation.accordion`. The [Angular modules](http://foundation.zurb.com/apps/docs/#!/angular-modules) page in our documentation breaks down every module and what they all do. You can also check out the [bootstrapping code](https://github.com/zurb/foundation-apps-template/blob/master/client/assets/js/app.js) for our template project to see what we're loading specifically.
