### ISSUE TITLE
Question: release schedule

### ISSUE THREAD

**Issue by gjungb** [zurb/foundation-apps#608]
Hi,

first of all, thanks for this great project!

I was wondering about your release schedule. Since the 1.1.0 release a bunch of fixes have been merged into master but not yet put into an official release.
Since the project I am working on e.g. relies on the fix for #547 I have do do the ```gulp deploy:dist``` manually on master for now, which doesn't integrate well with our ```bower``` based workflow.

To put things short: do you plan to do some minor releases (e.g. 1.1.1) soon or do you work towards version 1.2.0?

Thx

**Comment by gakimball** [comment]
We're about ready for a patch release, just need to close down a few of the more pressing issues. View animation specifically is something we want a little more solid.

**Comment by gjungb** [comment]
Thanks for keeping us updated!
