### ISSUE TITLE
Compress app.js?

### ISSUE THREAD

**Issue by ryanburnett** [zurb/foundation-apps#614]
My `gulpfile.js` contains:
```
appJS: [
  'client/assets/js/**/*.*'
]
```
This grabs all my JavaScript files and outputs them into one file: `app.js`

Awesome!

My question is, how can I compress the app.js file? 

Looks like this is the relevant section in `gulpfile.js` - I'm just not sure what to edit:

```
// Compiles and copies the Foundation for Apps JavaScript, as well as your app's custom JS
gulp.task('uglify', ['uglify:foundation', 'uglify:app']);

gulp.task('uglify:foundation', function(cb) {
  var uglify = $.if(isProduction, $.uglify()
    .on('error', function (e) {
      console.log(e);
    }));

  return gulp.src(paths.foundationJS)
    .pipe(uglify)
    .pipe($.concat('foundation.js'))
    .pipe(gulp.dest('./build/assets/js/'))
    ;
});

gulp.task('uglify:app', function() {
  var uglify = $.if(isProduction, $.uglify()
    .on('error', function (e) {
      console.log(e);
    }));

  return gulp.src(paths.appJS)
    .pipe(uglify)
    .pipe($.concat('app.js'))
    .pipe(gulp.dest('./build/assets/js/'))
    ;
});
```

Any ideas how to compress `app.js`?

**Comment by gakimball** [comment]
Add the `--production` flag to the command you're running. This enables compression for the CSS and JavaScript.

The plugin gulp-if controls the process of compression. If it sees the `--production` flag, the JavaScript runs through the `uglify` transform. Otherwise, it skips over it.
