### ISSUE TITLE
Modal for social media sharing

### ISSUE THREAD

**Issue by bbcreatv** [zurb/foundation-apps#615]
Hi I was wondering Is it possible to use a Modal to open for example http://www.facebook.com/sharer.php?

**Comment by gakimball** [comment]
You'd need to use an iframe inside of a modal, but I don't know that Facebook allows their share screens to be loaded in iframes—they have to be in their own window. (See more [here](http://stackoverflow.com/questions/9302023/load-facebook-sharer-in-iframe).)

There are a few ways to trigger this screen, which Facebook details in their [developer documentation](https://developers.facebook.com/docs/sharing/reference/share-dialog).
