### ISSUE TITLE
Error when creating new app

### ISSUE THREAD

**Issue by nroper** [zurb/foundation-apps#622]
Hi,

I'm trying to create a new app on my Mac (running OSX 10.10.3 Yosemite)

First I ran:

sudo npm install -g foundation-cli bower gulp

This gave some warnings as follows:

npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/prompt/node_modules/winston requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1

Then I tried to create a new app:

foundation-apps new ballparkApp

This gave:

There were some problems during the installation.

 ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.

Any help greatly appreciated.

Thanks,

Nick

**Comment by gakimball** [comment]
What version of Node and npm are you running?

```
node -v
npm -v
```

As for the project you tried to make, the files are all there. Can you try running `npm install` manually from within the project's folder?

**Comment by nroper** [comment]
Hi,

Versions as follows:

node: v0.12..3
npm: 2.9.1

I ran npm install from inside the project directory and then npm start and I've got the index page up OK now. It says 

Welcome to Foundation for Apps!
This is version 1.1 Weisshorn.

I assume that's what I should be seeing?

Question:

On this page: http://foundation.zurb.com/apps/docs/#!/installation

It says to run:  $ foundation-apps watch

but on this page: http://foundation.zurb.com/apps/getting-started.html

it says: $ npm start

What's the difference?

Thanks

**Comment by gakimball** [comment]
The commands are identical. `foundation-apps watch` is just running `npm start`. But for the sake of consistency we'll make sure that it lists the same command.

Just so we can close this out, could you try running the `foundation-apps new` command again? You should get a list npm errors above the text at the end where it says "There were some problems during the installation."

**Comment by nroper** [comment]
HI

Just tried ```foundation-apps new testApp``` and got this:

```
foundation-apps new testApp

           /|
          | |  /| .
     .  /\|  \/ |/|
     |\/          |
     ||\__/\____/||         Thanks for using Foundation for Apps!
  ___|| ======== ||___      -------------------------------------
 /___||  O    O  ||___\     Let's set up a new project.
     ||  ______, ||         It shouldn't take more than a minute.
     /|          |\ 
    /_/\\/\  /\//\_\ 
        \/\\//\/
           \/


Downloading the Foundation for Apps template...
Done downloading!

Installing dependencies...

/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/locker.js:66
    throw new Error(
          ^
Error: Attempt to unlock /Library/WebServer/Documents/vhosts/foundation4apps/testApp/node_modules/gulp, which hasn't been locked
    at unlock (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/locker.js:66:11)
    at cb (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/install.js:1017:5)
    at /usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/install.js:1021:20
    at /usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/locker.js:40:9
    at cb (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
    at /usr/local/lib/node_modules/foundation-cli/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
    at OpenReq.Req.done (/usr/local/lib/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/local/lib/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:63:22)
    at OpenReq.Req.done (/usr/local/lib/node_modules/bower/node_modules/bower-registry-client/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/local/lib/node_modules/bower/node_modules/bower-registry-client/node_modules/graceful-fs/graceful-fs.js:63:22)
Nicks-MBP:foundation4apps nickroper$ 

```

**Comment by gakimball** [comment]
Ah okay, it's a permissions issue with your computer. [Here's an npm issue comment](https://github.com/npm/npm/issues/4815#issuecomment-48080140) that details a fix. (Specifically it's the `sudo chown` commands halfway down the comment.)
