### ISSUE TITLE
grid-content producing sass error after parameters

### ISSUE THREAD

**Issue by mearleycf** [zurb/foundation-apps#623]
Here is the error I'm receiving: 

<pre>
[12:50:35] Starting 'sass'...
[12:50:35] [gulp-sass] error reading values after , on line 10 in /source/mwepd/client/assets/scss/app.scss
[12:50:35] Finished 'sass' after 7.56 ms
</pre>

And this is my full app.scss file, as it currently exists. Line 10 is the `$order: null, //...` line

<pre>
@import "settings";
@import "foundation";

// file content

.navbar {
@include grid-content(
$size: shrink, // Can be expand, shrink, or a number of columns
$offset: null, // Number of columns to offset to the right by
$order: null, // Can be any positive number
);
display: block;
padding: 0 $block-padding;
}</pre>

**Comment by gakimball** [comment]
The `$order` parameter in the mixin has an extra comma. Remove that last comma and you'll be good.

It looks like our documentation has a few formatting issues like these, so we'll make sure they get fixed.
