### ISSUE TITLE
Browserify error with Iconic

### ISSUE THREAD

**Issue by josephfinlayson** [zurb/foundation-apps#625]
Getting the following error while running a browserify bundle. Has this recently been updated?
    [22:38:33] browserify error Unexpected token (10:1228) while parsing                
    /home/joe/www/mm/node_modules/foundation-apps/js/vendor/iconic.min.js while      
    parsing file: /home/joe/www/mm/node_modules/foundation-apps/js/vendor/iconic.min.js

**Comment by gakimball** [comment]
The Iconic file hasn't changed since version 1.0; is this a problem you encountered starting with a specific version?

**Comment by josephfinlayson** [comment]
it's because it's accessing the literal regex like so:  `/iconic-bg-/.test`

fixed by:

                        var bgRegex = new RegExp(/iconic-bg-/);
                        bgRegex.test(a.getAttribute("class")) && g.addBackground(a), m(a), k++, b && b.each && "function" == typeof b.each && b.each(a)

not sure if this is a bug in browserify or iconic

**Comment by onelson** [comment]
Just ran into this myself. Not super sure I want to patch this dep in place... looking for a workaround now.

**Comment by onelson** [comment]
Eh, ok. I am bad and I feel bad but here's what I came up with to get my app bundling again...

I added the following to my `package.json` then immediately balled up and started to cry.
```
+  "scripts": {
+    "postinstall": "sed --in-place=.tmp 's|/iconic-bg-/.test|new RegExp(\"iconic-bg-\").test|' ./node_modules/react-foundation-apps/lib/vendor/iconic.min.js"
+  },
```

**Comment by onelson** [comment]
So, I reported the issue to the babel folks, and I guess the parser they depend on is a separate project called acorn. Issue was re-reported on this other project: marijnh/acorn#289

**Comment by josephfinlayson** [comment]
Good investigation @onelson +1. Finding bugs in babel should be hard

**Comment by gakimball** [comment]
Since it's an issue with Acorn, we'll close this out.
