### ISSUE TITLE
What database backend?

### ISSUE THREAD

**Issue by zorrobyte** [zurb/foundation-apps#627]
This may be the wrong place to ask but with MVC frameworks like Meteor, Django and others - modeling your database is documented and easy to learn. However with Foundation for Apps, this information is absent.

Do I simply figure out how to integrate Foundation for Apps with something like sails.js or would I come up with my own solution using a database like OrientDB?

Related, where is the proper location to post these questions?

**Comment by etcook** [comment]
Foundation for Apps is an AngularJS framework. It's database/model agnostic.

**Comment by zorrobyte** [comment]
Ah, so basically I would follow the same workflow to integrate Foundation for Apps into something like Sails.js just as I would straight Angular.js?

**Comment by etcook** [comment]
Yes sir!

**Comment by zorrobyte** [comment]
Thanks! I just found Yeoman which should make this easy!

Cheers.
