### ISSUE TITLE
modalFactory class should be configurable

### ISSUE THREAD

**Issue by PoyangLiu** [zurb/foundation-apps#637]
It would be nice if the modal dialog created using the modalFactory service can take a class from the config.  I tried to add 'collapse' css style on the modal dialog like the example in foundation-apps docs.

here is my suggested change in ModalFactory service
<code>
 id = config.id || foundationApi.generateUuid(),
modalClass = config.modalClass,
</code>

in assembleDirective function
<code>
html = '\<zf-modal id="' + id + '"' + ' class="' + modalClass + '">' + html + '\</zf-modal>';
</code>

**Comment by soumak77** [comment]
This was fixed with e70eff2d17a5de409e4a58d259c7c8a7e076ee7e.  It'll be in the next release.
