### ISSUE TITLE
Error Updating from 1.0

### ISSUE THREAD

**Issue by Dillie-O** [zurb/foundation-apps#651]
Greetings,

I'm finally getting around to updating my Z4A app from 1.0. I went to my project root, and made a backup copy of my gulpfile.js file to gulpfile.js.orig (to preserve some customizations). I then updated my foundation-cli by running

`npm update -g foundation-cli`

from Powershell as an administrator. That worked fine. After that I ran

`foundation-apps update`

and after a moment I received the following error message:

>C:\Users\Sean\Projects\prayerjournal [master +1 ~0 -0 !]> cd .\prayerjournal\
>C:\Users\Sean\Projects\prayerjournal\prayerjournal [master +1 ~0 -0 !]> foundation-apps update

>C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\node_modules\q\q.js:155
                throw e;
                      ^
angular: Unable to find suitable version for angular
    at createError (C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\lib\util\createError.js:4:15)

 > at Manager._electSuitable (C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\lib\core\Manager.j
s:763:15)
    at C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\lib\core\Manager.js:558:25
    at _fulfilled (C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\node_modules\q\
q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\node_modu
les\q\q.js:796:13)
    at C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\node_modules\q\q.js:556:49
    at runSingle (C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\node_modules\q\q.js:137:13)
    at flush (C:\Program Files\nodejs\node_modules\foundation-cli\node_modules\bower\node_modules\q\q.js:125:13)
    at process._tickCallback (node.js:419:13)`

I checked my bower_components folder and noted that my angular folder is still there and the header in angular.js says I'm running version 1.3.8

Is there something going on that I'm missing?

**Comment by gakimball** [comment]
Hm, try running `bower update` manually and see what happens. You might be asked to manually select a version of Angular to install—just pick the latest one along the 1.3.x line and you should be fine.

**Comment by Dillie-O** [comment]
Okay, I ran bower update, and specified 1.3.16 as the new option. That seemed to update a lot of things. I also was informed I was running an older version of bower, so I updated bower, ran bower update again, and got the same results. 

Looking at my bower.json file, my dependencies section still has `foundation-apps ~1.0.2` listed in the dependencies. Is this the latest version allowed through this process still? I thought 1.1 was released. Or do I need to update the bower.json file to require a newer version?

**Comment by gakimball** [comment]
Yep, you need to manually type in 1.1. Since minor versions can add new features or introduce deprecations, package managers like to safeguard you from making big version leaps automatically.

But if you're cool with that, you can edit your `bower.json` to look like this:

```
"foundation-apps": "~1.1"
```

By taking out the last number, Bower will automatically update the package to 1.1, 1.2, and beyond.

Let us know if you're able to upgrade properly. Unfortunately we introduced a bunch of big structural changes to our code in 1.0.2, which doesn't change how you use the framework, but does affect how your Gulpfile needs to work. The [release notes](https://github.com/zurb/foundation-apps/releases/tag/v1.0.2) for 1.0.2 cover the upgrade process.

**Comment by Dillie-O** [comment]
Good to know. I remember seeing the gulp updates (all good ones) so I'm not too worried about that.

I was able to get things updated. For kicks I ran `foundation-apps update` and after a moment the command prompt returned to me, but nothing seemed to have occurred. So I ran `bower update` again and saw a lot of updates, and it looks like foundation is updated.

I think it's safe to say at this point that I'm updated, now I'll just see if I need to make any tweaks to my code. Thanks!

One final note, running `foundation-apps -v` doesn't seem to return anything but a list of commands to run, I was expecting to see the version somewhere. Is that a bug?

**Comment by gakimball** [comment]
Yep, that's a bug, see zurb/foundation-cli#11. The CLI is overdue for a new patch, so when that gets out it'll have this fix.

Glad the upgrade process worked, though! We don't plan on requiring anything substantial like that again for the v1.x line.
