### ISSUE TITLE
Hammer.js not defined

### ISSUE THREAD

**Issue by Dillie-O** [zurb/foundation-apps#655]
Now that I'm up to date on 1.1, I'm still seeing this error.

I have a view with a form submission. Once the form submission is complete, I use the notification directive (through javascript) to display a message. Here's my JS code:

    FoundationApi.publish('prayer-notifications',
    {
        title: 'Prayer Added',
        content: 'Prayer "' + $scope.prayer.name + '" has been added successfully.',
        color: 'success'
    });

While my message displays fine, I always wind up seeing the following error message in the web console

`Hammer is not defined`

I've checked my gulp scripts and it is bundling up the HammerJS library, so I'm wondering if I'm missing something in my controller or something, do I need to add that as a dependency to my controller dependency injection?

**Comment by gakimball** [comment]
Can you post a stack trace for that error, so we can see where in the code it's being generated?

**Comment by Dillie-O** [comment]
Interestingly enough, a single click triggered the error twice:

>Error: Hammer is not defined
link@http://prayerjournal.dev/assets/js/foundation.js:34:1388
cloneAndAnnotateFn/<@http://prayerjournal.dev/assets/js/foundation.js:9:6028
invokeLinkFn@http://prayerjournal.dev/assets/js/foundation.js:9:6149
nodeLinkFn@http://prayerjournal.dev/assets/js/foundation.js:8:24405
compileTemplateUrl/<@http://prayerjournal.dev/assets/js/foundation.js:9:1995
compositeLinkFn@http://prayerjournal.dev/assets/js/foundation.js:8:14121
compile/<@http://prayerjournal.dev/assets/js/foundation.js:8:12792
createBoundTranscludeFn/boundTranscludeFn@http://prayerjournal.dev/assets/js/foundation.js:8:15476
controllersBoundTransclude@http://prayerjournal.dev/assets/js/foundation.js:8:20509
ngRepeatDirective</<.compile/</<@http://prayerjournal.dev/assets/js/foundation.js:13:29493
$watchCollectionAction@http://prayerjournal.dev/assets/js/foundation.js:10:25791
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://prayerjournal.dev/assets/js/foundation.js:10:27348
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://prayerjournal.dev/assets/js/foundation.js:10:29370
done@http://prayerjournal.dev/assets/js/foundation.js:9:17667
completeRequest@http://prayerjournal.dev/assets/js/foundation.js:9:21382
createHttpBackend/</xhr.onload@http://prayerjournal.dev/assets/js/foundation.js:9:22304
 <div zf-closable="notification" ng-repeat="notification in notifications" title="notification.title" image="notification.image" notif-id="notification.id" color="notification.color" autoclose="notification.autoclose" zf-swipe-close="swipe" class="notification {{ color }} ng-isolate-scope"> foundation.js:10:5014

>Error: Hammer is not defined
postLink@http://prayerjournal.dev/assets/js/foundation.js:38:2082
cloneAndAnnotateFn/<@http://prayerjournal.dev/assets/js/foundation.js:9:6028
invokeLinkFn@http://prayerjournal.dev/assets/js/foundation.js:9:6149
nodeLinkFn@http://prayerjournal.dev/assets/js/foundation.js:8:24405
compileTemplateUrl/<@http://prayerjournal.dev/assets/js/foundation.js:9:1995
compositeLinkFn@http://prayerjournal.dev/assets/js/foundation.js:8:14121
compile/<@http://prayerjournal.dev/assets/js/foundation.js:8:12792
createBoundTranscludeFn/boundTranscludeFn@http://prayerjournal.dev/assets/js/foundation.js:8:15476
controllersBoundTransclude@http://prayerjournal.dev/assets/js/foundation.js:8:20509
ngRepeatDirective</<.compile/</<@http://prayerjournal.dev/assets/js/foundation.js:13:29493
$watchCollectionAction@http://prayerjournal.dev/assets/js/foundation.js:10:25791
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://prayerjournal.dev/assets/js/foundation.js:10:27348
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://prayerjournal.dev/assets/js/foundation.js:10:29370
done@http://prayerjournal.dev/assets/js/foundation.js:9:17667
completeRequest@http://prayerjournal.dev/assets/js/foundation.js:9:21382
createHttpBackend/</xhr.onload@http://prayerjournal.dev/assets/js/foundation.js:9:22304
 <div zf-closable="notification" ng-repeat="notification in notifications" title="notification.title" image="notification.image" notif-id="notification.id" color="notification.color" autoclose="notification.autoclose" zf-swipe-close="swipe" class="notification {{ color }} ng-isolate-scope"> foundation.js:10:5014

Here's a screenshot if it helps any better:

![hammererror](https://cloud.githubusercontent.com/assets/991466/8419517/261619e0-1e6f-11e5-856c-af95fca63e2a.png)

**Comment by Dillie-O** [comment]
Hey guys,

Sorry about this. Turns out this was a non-issue. I had a custom build script (for my .Net project) and so my updated copy of foundation wasn't going to the properly location. I was still loading old foundation code. Once I fixed this and ran it, things were good.

Sorry for the hassle.
