### ISSUE TITLE
foundation-apps -v doesn't work

### ISSUE THREAD

**Issue by djgadd** [zurb/foundation-apps#657]
I just ran: -
npm update -g foundation-cli

and then attempted: -
foundation-apps update

but got "nothing to update" so I tried: -
foundation-apps -v

but I only get the help screen (which says -v should display the client version). Could be that I'm having a bit of a slow Wednesday but something seems amiss.

**Comment by gakimball** [comment]
Just published version 1.1.2 of the CLI which fixes this. See zurb/foundation-apps#11
