### ISSUE TITLE
Impossible to compile scss when setting "notification" is there.

### ISSUE THREAD

**Issue by datadl** [zurb/foundation-apps#664]
Hello,

When you want to enable/disable a foundation component's css module in the map "$include-css" inside _settings.scss and that you uncomment the line for the component "notification" this won't allow you to compile.

This is due to the version of gulp-sass packaged in the foundation-apps that doesn't allow you to have any key in a sass-map to start by "no" without being surrounded by quotes.

A quick fix as of now is to change the version of gulp-sass in the package.json located at the root of your projet.
Change it to: **^2.0.3**

Then run the command 
**bower update gulp-sass**

It will update the version of node-sass to allow keys to start by "no".
See issue https://github.com/sass/libsass/issues/934 about that!

Cheers,
Vincent

**Comment by gakimball** [comment]
Updated all of the devDependencies in the template, and everything looks solid. [Here's the commit.](https://github.com/zurb/foundation-apps-template/commit/d1e0409954aee3cdf19c90d7ca57a719806e73bb)
