### ISSUE TITLE
Not working with meteor

### ISSUE THREAD

**Issue by sumanla13a** [zurb/foundation-apps#667]
Hey, I am trying to use this package with my meteor app, but it is not working for me.
I get the foundation-apps.js and foundation-apps.css on my app but not the foundation-apps-templates.js

On adding foundation-apps-templates to the main section, my app is running successfully.
I am forced to use cdn instead of the bower package.

Can you look into it and/or maybe add foundation-apps-template.js to the main section of .bower.json

**Comment by gakimball** [comment]
It's in there right now, but not in a stable release. We'll see about getting a patch release out in the next week.
