### ISSUE TITLE
Add JS batch to docs menu 

### ISSUE THREAD

**Issue by janusch** [zurb/foundation-apps#668]
It would be nice and convenient to add a batch to the menu items in the foundation-apps documentation, just like in the foundation for sites docs.

This would make it more straight forward for users to see if a component relies on javascript/angular.

**Comment by gakimball** [comment]
Do you mean flagging components that require JavaScript?

**Comment by janusch** [comment]
@gakimball Yes, that would be very useful. What do you think is that something you will add?
I think it is relevant for users that would like to use foundation-apps without adding angular to their apps.
Foundation-apps offers many very nice forward thinking solutions to app design without using angular.
In my case I am already using the grid, would be sweet if there are other parts that I can use as well without adding angular.
Thanks for your quick reply!
Keep up the excellent work!
