### ISSUE TITLE
Newer angular version required when installing angular-cookies

### ISSUE THREAD

**Issue by franbenz** [zurb/foundation-apps#694]
I tried to install the angular-cookies package with `bower install angular-cookies`. I got this prompt:
```
Unable to find a suitable version for angular, please choose one:
    1) angular#~1.3.4 which resolved to 1.3.18 and is required by foundation-apps#1.1.0
    2) angular#1.3.18 which resolved to 1.3.18 and is required by angular-animate#1.3.18
    3) angular#1.4.6 which resolved to 1.4.6 and is required by angular-cookies#1.4.6
    4) angular#>= 1.0.8 which resolved to 1.4.6 and is required by angular-ui-router#0.2.15
```
Does this means the foundation for apps project is fixed/stucked with an old angular version(~1.3.4) and I would break my project if I install a newer one?

**Comment by gakimball** [comment]
We haven't tested the framework on 1.4 yet, so stick with 1.3.x if you can. Although there's a decent chance it'll work with 1.4 right away.

**Comment by kuatsure** [comment]
@gakimball any movement on this issue? my team is also running in to an issue with the lower bound being 1.3.x ... it's the main hurdle for us to move our angular app to foundation-apps away from foundation-sites.

**Comment by soumak77** [comment]
For what it's worth, I've been using F4A with angular 1.4.x in production code for a few months now.  There were a couple problems I had to address in my own code due upgrading angular, but no issues were found in F4A.

**Comment by kuatsure** [comment]
@soumak77 how much of the angular modules do you use?

**Comment by soumak77** [comment]
@kuatsure I use nearly every part of the F4A framework.  It should also be noted that I run a custom build of the framework (https://github.com/fiboacademy/foundation-apps/tree/fibo-master).  Some of my fixes/features have made there way into the F4A master and some haven't.  The forked repo is set to angular 1.4.4, however, my build system is set to use angular 1.4.7 and I haven't noticed any issues.

**Comment by gakimball** [comment]
@soumak77 If you haven't seen any issues, we could introduce a range of 1.3.x to 1.4.x for the Angular dependency.

**Comment by soumak77** [comment]
@gakimball that would be best

**Comment by kuatsure** [comment]
@gakimball + @soumak77 :: let's do that :) are pr's welcome?

**Comment by gakimball** [comment]
@kuatsure Yes! I want to sweep the recent pull requests soon.
