### ISSUE TITLE
Range slider getting stuck to mouse

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#699]
When using the range slider input, I am noticing the mouse is getting stuck to the slider.  This causes the slider to move with the mouse after the mouse has been unclicked.  It also causes no other elements to be clickable on the screen.  I've seen this issue appear on Chrome and Safari.

Unfortunately I cannot reproduce with issue with the input on the docs page (http://foundation.zurb.com/apps/docs/#!/forms).  The markup which is noticing the issue is shown below (param is a scope property):

```html
<input type="range" ng-model="param.value" min="{{ param.min }}"
           max="{{ param.max }}" step="{{ param.type == 'decimal' ? '0.1' : '1' }}">
```

**Comment by soumak77** [comment]
I was able to reproduce this issue in my app using the same markup as in the docs ```<input type="range"/>```.  This issue is intermittent as it works sometimes in my app, but more often than not the slider gets stuck and requires refreshing the browser.

**Comment by STRd6** [comment]
I had a similar problem and it was due to an event handler on document mouseup calling preventDefault, hope this might help.

**Comment by soumak77** [comment]
Appears to be due to another library I'm using not handling mouse events correctly
