### ISSUE TITLE
Build-deploy process and documentation needed

### ISSUE THREAD

**Issue by lee-40square** [zurb/foundation-apps#701]
Works great for development environment but when it's time to deploy it's clunky. Maybe we just need better documentation but seems like we should be able to easily deploy without all the extra stuff and have the server run on a dynamic port as assigned by Heroku.

**Comment by gakimball** [comment]
Are you referring to deploying this repo, or a project you've created with our [project template](https://github.com/zurb/foundation-apps-template)?

**Comment by lee-40square** [comment]
My mistake, I am more interested in the process of building and deploying a complete Foundations for Apps project for which the documentation is thin. I'll head over to the project template repo. Thanks.

**Comment by gakimball** [comment]
Sounds good! zurb/foundation-apps-template#26
