### ISSUE TITLE
npm version out of date

### ISSUE THREAD

**Issue by AnthonyPAlicea** [zurb/foundation-apps#711]
Hello,

Thank you for this terrific work! I have installed foundation-apps from npm and notice the contents of the 'scss' folder are out of date.

The 'components/_forms.scss' file, for example, does not have the exports code added several months ago. 

My preferred approach is installing the source code via npm for version tracking and combining with my own scss files, so was wondering if that folder could get synced to the latest version.

Thanks!

**Comment by gakimball** [comment]
The current version (1.1) is the correct one, it's just been a *while* since we put out a patch.

We're trying to get one out in the next week or two, but the Foundation team is fairly resource-constrained right now working on Foundation for Sites 6, which is launching very soon.
