### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by btwolfe79** [zurb/foundation-apps#715]
I'm sad to see that foundation-apps hasn't received much love in the last year... I fear it may be dead?  Maybe a revival after foundation-sites 6?

Either way, it would be great if we could get a new release tagged with the latest Angular upgrades etc.

Thanks!

**Comment by jeffreznik** [comment]
Agreed!  I can't even add angular-resource because angular-resource wants angular 1.4.7 and foundation-apps is stuck on ~1.3.4.  If I force 1.4.7, foundation-apps errors out when the page loads.

**Comment by btwolfe79** [comment]
I was able to force use of the latest via:
"foundation-apps": "git://github.com/zurb/foundation-apps.git#d5cebfaffe4395ccfc8dd5d6435f427fdb8c290b"

and using
"resolutions": {
  "angular": "1.4.7"
}

Unfortunately I think we need to start investigating alternative frameworks... I love Zurb but I think they have too much on their plate to support foundation-apps.

**Comment by soumak77** [comment]
I started using foundation from the beginning and really love what they did.  I was in the early stages of my company when I decided to go with foundation for apps and now all my apps run on this framework.  It is unfortunate to see the lack of support at this time, however, I foresee being able to do some amazing things with this framework in the future.  Seeing as I am reliant on the framework to maintain my business, I created a [fork](https://github.com/fiboacademy/foundation-apps/tree/fibo-master) where I make necessary updates to the framework to support my needs.  Most of these changes I'm hoping to get merged into foundation for apps once the project picks back up.  Some of which are pending PRs.

While it may not be a viable option to use my forked repo in production, you can try it out by adding the following to your bower file:
`"foundation-apps": "git@github.com:fiboacademy/foundation-apps#fibo-master"`

The fork should be a drop-in replacement with no additional configuration needed, though you will need to build from source.

**Comment by ksr583** [comment]
I stupidly chose this framework to make a soon-to-be production app with, and I'm definitely upset that it basically hasn't been touched.

**Comment by gakimball** [comment]
Hey friends, we're going to be releasing version 1.2.0 on Friday. This week we're going to be asking the community what issues are most critical to get resolved this week, and we'll be reviewing every pull request. On Thursday we're QAing the release, and then on Friday we're tagging and deploying it.

With Foundation 6 out, we're about to shift our focus back to Foundation for Apps. We're thinking about what version 2.0 will be, but we aren't done with version 1.x by any means. I'm opening a new issue to track what people feel is critical to address this week: #725 Thanks for your patience :)
