### ISSUE TITLE
command not found: foundation-apps

### ISSUE THREAD

**Issue by jessepinuelas** [zurb/foundation-apps#718]
I am not able to run the foundation-apps via command line. Ran the following with no luck.
1) npm install -g foundation-cli bower gulp
2) gem install bundler
3) tried to create project on desktop via foundation-apps new myApp
4) Lost some CLI love so gave the Yeti Launch a go and got the following error on startup:
Uncaught Exception:
Error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.: (null) at Error (native)

I was able to run the project through the yeti launcher despite the error but on my system can not run foundation-apps from CLI. Any advice would be great.

OS X El Capitan 10.11
Node Version 4.2.2
Npm Version 3.4.1

Screen shots:

![screen shot 2015-11-23 at 2 01 47 am](https://cloud.githubusercontent.com/assets/425963/11333934/39ba1a2a-9186-11e5-86d3-353ccc124340.png)

![screen shot 2015-11-23 at 1 55 33 am](https://cloud.githubusercontent.com/assets/425963/11333913/103d3b46-9186-11e5-9033-28766066da75.png)

**Comment by LittleHendrix** [comment]
Same issue on Windows 7 x64
![capture](https://cloud.githubusercontent.com/assets/1037065/11342002/fe95e678-91fc-11e5-8277-38d52cbf2430.PNG)

Everything installed (and accessible via CMD) on system as follows:
foundation-cli@2.0.0
bundler 1.10.6
sass 3.4.19
node v0.10.36
npm 1.4.28
ruby 2.1.7p400

**Comment by dredgerman** [comment]
Same in windows x64, installed all dependencies, foundation upgraded and followed instructions to letter in readme, makes software useless as can't even start a project!

[tom@server ~]$ foundation-apps new myapp
bash: foundation-apps: command not found
[tom@server ~]$

**Comment by obonyojimmy** [comment]
@dredgerman @LittleHendrix  @jessepinuelas  Try including an alias for  ' foundation-apps ' to the bash(CLI) config ,Do a simple google search on how to !

**Comment by etcook** [comment]
@dredgerman @LittleHendrix @jessepinuelas 

If you're on a mac, do this

```bash
cd /usr/local/bin
ln -s /usr/local/lib/node_modules/foundation-cli/bin/cli.js foundation-apps
```

Update the paths so they're appropriate for your system

**Comment by dredgerman** [comment]
Hi,

Thanks,

After tearing my hair out for a number of days am moving to meteor instead,

Appreciate the help,

**Comment by myhusam** [comment]
Hi guys, 

I think you just need to type `foundation new'  then you'll choose the one you need App, Site or Mail.

![foundation-cli]
(https://dl.dropboxusercontent.com/u/25503484/foundationApp.png)

**Comment by jessepinuelas** [comment]
@obonyojimmy @etcook creating the alias to foundation-apps did the trick.

**Comment by ansorg** [comment]
Ok, I get the menu. But arrow keys don't allow to select an option, they work on the underlying command line instead (bring up previously entered commands)
This is on Windows 10

**Comment by obonyojimmy** [comment]
@ansorg you need to build you project before you see any changes on your app , did you do `gulp` in CLI ?

**Comment by lanluu** [comment]
I face the same problem like ansorg's one where I cannot select the second option "A web app" with arrow keys. It is on Windows 8. Do you guys have any tip for me?

**Comment by lorenjerickson** [comment]
Same arrow key problem here, windows 10.  not a good first impression....

**Comment by danielemanca1983** [comment]
I am having the same silly problem, I have the foundation cli installed globally, but when I try to run the command foundation-apps new, to create a new project, the command line tells me the command cannot be found, this is on Windows 10 too

**Comment by Sfathy** [comment]
the command changed to foundation not foundation-app

**Comment by cmyk** [comment]
Just installed node 6.11 and did a ```npm install --global foundation-cli```.
The ```foundation``` command is not found.
This is on Sierra 10.12.5.
