### ISSUE TITLE
foundation-apps start server without port

### ISSUE THREAD

**Issue by obonyojimmy** [zurb/foundation-apps#732]
i have successfully installed foundation-apps and its dependencies , id however like to know how to run the server without port ie htttp://localhost and not http://localhost:8080 or http://domain.com and not http://domain.com:8080

**Comment by zurbchris** [comment]
I'm afraid the port is required if using our dev environment. It's part of the gulp-connect plugin.

**Comment by obonyojimmy** [comment]
#SOLVED 
i solved this in Laravel by using ` php artisan serve ` which basically run the php based server and configures server links automatically
