### ISSUE TITLE
zf-action-sheet manual trigger fails to show the content

### ISSUE THREAD

**Issue by soyuka** [zurb/foundation-apps#733]
Using same code as the docs states:

```
<a href="#" zf-hard-toggle="separate-actionsheet">Toggle</a>
<a href="#" zf-hide="separate-actionsheet">Hide</a>
<zf-action-sheet id="separate-actionsheet">
  <zf-as-content position="top">
    <p>Message for you, sir!</p>
  </zf-as-content>
</zf-action-sheet>
```

When clicking "Toggle" the content shows and then fade back out. I was using `1.1.x` and just tried on `master`.

What version are you using in the docs?

Note that when using `zf-as-button` everything works fine.

**Comment by zurbchris** [comment]
Locally, it's working just fine, which is on master. In fact we're browser testing right now.

**Comment by soyuka** [comment]
What could prevent it from working? I'll try again locally!
