### ISSUE TITLE
typescript definitelytyped

### ISSUE THREAD

**Issue by itlizhi** [zurb/foundation-apps#755]
I want to use foundation-apps with typescript, but I could not find  definitelytyped in https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by gakimball** [comment]
This is a newer library, so nobody has written any type definitions for us yet. We don't use TypeScript here at ZURB, so we don't have the knowledge (or time) to put one together ourselves.

If *you* are interested in putting one together, we can promote it on our [Resources wiki page](https://github.com/zurb/foundation-apps/wiki/Resources). :)
