### ISSUE TITLE
vendor prefixes for css

### ISSUE THREAD

**Issue by fortuneteller** [zurb/foundation-apps#779]
Please, help me to understand one thing. Only in case you have time for it. 

The page http://foundation.zurb.com/apps/docs/#!/off-canvas works perfect on all my mobile devices.
But when I check out the latest foundation for apps version I have broken layout (on some mobile browsers) and widgets because of missing of vendor-prefixed css rules like:
```css
-webkit-transform: translateX(-100%);
```

![_067](https://cloud.githubusercontent.com/assets/1685654/13198335/2bbfb6dc-d817-11e5-9f94-eb132c5a761c.png)

What should I do - manually extend your scss files and use them, or wait until you will publish the same version as used for http://foundation.zurb.com/apps/docs/. 

Thanks in advance.

**Comment by circlingthesun** [comment]
Try: https://www.npmjs.com/package/gulp-autoprefixer

**Comment by fortuneteller** [comment]
Thank you very much.

This is exaclty what I need.

2016-02-20 23:03 GMT+03:00 Rickert Mulder <notifications@github.com>:

> Try: https://www.npmjs.com/package/gulp-autoprefixer
>
> On Sat, 20 Feb 2016, 8:22 p.m. Andrey Konstantinov <
> notifications@github.com>
> wrote:
>
> > Please, help me to understand one thing. Only in case you have time for
> > it.
> >
> > The page http://foundation.zurb.com/apps/docs/#!/off-canvas works
> perfect
> > on all my mobile devices.
> > But when I check out the latest foundation for apps version I have broken
> > layout (on some mobile browsers) and widgets because of missing of
> > vendor-prefixed css rules like:
> > -webkit-transform: translateX(-100%);
> >
> > [image: _067]
> > <
> https://cloud.githubusercontent.com/assets/1685654/13198335/2bbfb6dc-d817-11e5-9f94-eb132c5a761c.png
> >
> >
> > What should I do - manually extend your scss files and use them, or wait
> > until you will publish the same version as used for
> > http://foundation.zurb.com/apps/docs/.
> >
> > Thanks in advance.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/zurb/foundation-apps/issues/779>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zurb/foundation-apps/issues/779#issuecomment-186674878>
> .
>



-- 
Андрей
тел.: +7 906 7649153

**Comment by tunecino** [comment]
@fortuneteller You don't have to install it. it is already installed. or maybe you just need to upgrade it. see this : https://github.com/zurb/foundation-apps/blob/master/package.json#L30

**Comment by fortuneteller** [comment]
Thank you. I haven't mention it.

2016-02-23 11:29 GMT+03:00 Salem Ouerdani <notifications@github.com>:

> @fortuneteller <https://github.com/fortuneteller> You don't have to
> install it. it is already installed. or maybe you just need to upgrade it.
> see this :
> https://github.com/zurb/foundation-apps/blob/master/package.json#L30
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zurb/foundation-apps/issues/779#issuecomment-187600379>
> .
>



-- 
Андрей
тел.: +7 906 7649153
