### ISSUE TITLE
Foundation For Apps Files Not Hosted on jsDelivr CDN

### ISSUE THREAD

**Issue by kobekoto** [zurb/foundation-apps#830]
As per your installation page:

CDN
The folks at jsDeliver are hosting the Foundation for Apps CSS and JavaScript on their CDN. Just add the files as <link> or `<script>` tags in the  of your HTML file.

**Comment by soumak77** [comment]
@kobekoto I suggest trying out Angular Base Apps if you want to use this framework (see https://github.com/zurb/foundation-apps/issues/829 for more info)
